---
title: Major League Baseball Home Plate Umpires
author: Abigail Smith
date: July 10, 2024
description: Analyzing various statistics from Major League Baseball home plate umpires dating back to 2008.
categories:
  -  COME BACK TO WHEN IM DONE QUESTIONS
  
editor: 
  markdown: 
    wrap: 72
---

## Motivation

[Baseball](https://en.wikipedia.org/wiki/Baseball){target="_blank"} is a
popular American sport played on a diamond shaped field. Games are 9
innings long and each inning has two halves, the first in which the
visiting team hits and the second where the home team hits. Innings end after three batters are out. Batters aim
to get on base by hitting a ball pitched to them by the pitcher. Batters
can get to first, second, or third base depending on how far they hit
the ball and how fast they run. If a batter hits the ball past the
outfield fences, they along with any runners on base automatically
score, this is called a home run. Runners can also score if another
player hits the ball and then they reach home. The team with the most
runs wins the game.

There are 9 defensive positions in baseball, the layout of these
positions is labeled in the below diagram.

[![SOURCE:
https://en.wikipedia.org/wiki/Baseball_positions](images/images.png){fig-align="center"
width="331"}](https://en.wikipedia.org/wiki/Baseball_positions)

Behind the catcher at home plate is an official known as the home plate
umpire. The umpire's role is to enforce baseball rules and make
decisions during a game. Many of these decisions involve calling balls
and strikes. Pitches that are considered strikes are pitched within the zone outlined below. Anything outside of that zone is called a ball. If a batter gets 3 strikes, they are out which is called a strike out. If the batter gets 4 balls they get to go to first base on what is called a walk. 

[![SOURCE:
https://www.dimensions.com/element/strike-zone](images/5bd08351ae57fd50e3c91538_Dimensions-Guide-Sports-Baseball-Strike-Zone-Dimensions.svg){fig-align="center"
width="300"}](https://www.dimensions.com/element/strike-zone)

## Data

The data set has 954 rows with 11 variables. Each row is an MLB home
plate umpire combined with a `boost_stat` ranking how they compare with
the average umpire. There are 159 umpires in the dataset with 6 rows per
umpire. The data is cumulative from 2008 until 2024.

| Variable     | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|---------------------|---------------------------------------------------|
| `Umpire`     | The name of the umpire.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| `Games`      | The number of games the umpire has umpired since 2008.                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| `k_pct`      | The strike out percentage of batters and pitchers when the umpire is umpiring. (`Career Strike Outs Called`/`Career Plate Appearances Umpired`)                                                                                                                                                                                                                                                                                                                                                                   |
| `bb_pct`     | The walk percentage of batters when the umpire is umpiring. (`Career Walks Called`/`Career Plate Appearances Umpired`)                                                                                                                                                                                                                                                                                                                                                                                            |
| `RPG`        | The career runs scored per game when the umpire is umpiring. (`Career Runs While Umpiring`/`Career Games Umpired`)                                                                                                                                                                                                                                                                                                                                                                                                |
| `BA`         | The batting average of batters in games when the umpire is umpiring. (`Career Hits While Umpiring`/`Career Plate Appearances Umpired`)                                                                                                                                                                                                                                                                                                                                                                            |
| `OBP`        | The on base percentage of batters when the umpire is umpiring. ((`Career Hits While Umpiring` + `Career Walks While Umpiring` + `Career Hit by Pitches While Umpiring`)/(`Career At Bats Umpired` + `Career Walks While Umpired` + `Career Hit by Pitches While Umpiring` + `Career Sacrifice Flies While Umpiring`))                                                                                                                                                                                             |
| `SLG`        | The slugging percentage of batters when the umpire is umpiring. ((`Singles While Umpiring` + (`Doubles While Umpiring` \* 2) + (`Triples While Umpiring` \* 3) + (`Home Runs While Umpiring` \* 2))/`Career At Bats Umpired`)                                                                                                                                                                                                                                                                                     |
| `boost_stat` | The statistic being "boosted" by the umpire when they are behind home plate. This can be strikeouts (`K`), walks (`BB`), runs (`R`), batting average (`BA`), on base percentage (`OBP`), and slugging percentage (`SLG`).                                                                                                                                                                                                                                                                                         |
| `boost_pct`  | The percentage that the `boost_stat` is being boosted. In other words how much the umpire is above or below the average umpire in calling that statistic.                                                                                                                                                                                                                                                                                                                                                         |
| `Rating`     | Whether or not the umpire favors offensive or defensive players in that statistic. The `Rating` is `Defensive` if the umpire has a `boost_pct` above zero and the `boost_stat` is K or if the `boost_pct` is below zero and the stat is `BB`, `R`, `BA`, `OBP`, or `SLG`. The `Rating` is `Offensive` if the umpire has a `boost_pct` below zero and the `boost_stat` is K or if the `boost_pct` is above zero and the stat is `BB`, `R`, `BA`, `OBP`, or `SLG`. It will be `Neither` if the `boost_pct` is zero. |

: [umpires.csv](umpires.csv){target="_blank"}

## Questions

1.  **GO BACK TO WHEN I'M DONE QUESTIONS**

## References

[Website the Data was Scraped
From](https://swishanalytics.com/mlb/mlb-umpire-factors){target="_blank"}
