---
title: "Cycling Exploration"
author: "Gavin Cassidy"
format: html
---

```{r}
library(tidyverse)
library(readr)
library(rvest)
```

```{r}
tdf_stages <- read.csv("/Users/Gavin Cassidy/Desktop/GitHub/stat_289_score2/gacass21/Cycling/data_repo/tdf_stages.csv")

tdf_winners <- read.csv("/Users/Gavin Cassidy/Desktop/GitHub/stat_289_score2/gacass21/Cycling/data_repo/tdf_winners.csv")

```


```{r}
tdf_stages |> summary()

tdf_stages <- tdf_stages |> mutate(Stage = as.numeric(Stage), Date = as.Date(Date))

tdf_stages |> group_by(Winner_Country) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_stages |> filter(Date > 1969-07-02) |> group_by(Winner_Country) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_stages |> arrange(Date)

tdf_stages |> filter(Date < 1945-08-30) |>
  group_by(Winner_Country) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_stages |> group_by(Winner) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_stages |> summary()

tdf_stages |> 
  filter(Date > 2007-08-30) |> 
  group_by(Winner_Country) |> 
  summarise(wins = n()) |> 
  arrange(desc(wins)) 

tdf_stages |>
  filter(Date < 2007-08-30) |> 
  group_by(Winner_Country) |>
  summarise(wins = n()) |> 
  arrange(desc(wins)) 






ggplot(data = tdf_stages, aes(y = time_seconds, x = ind_half)) +
  geom_boxplot()
```

```{r}
tdf_stages |> group_by(Type) |> summarise(avg_distance = mean(Distance))
```



```{r}
tdf_winners <- tdf_winners |> mutate(start_date = as.Date(start_date),
                                     born = as.Date(born),
                                     died = as.Date(died), 
                                     seconds_margin = time_margin*3600) |>
  select(edition, start_date, winner_name, winner_team, distance, time_overall, time_margin, seconds_margin, everything())


tdf_winners |> summary()

tdf_winners |> group_by(nationality) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_winners |> arrange(desc(weight))


tdf_winners |> mutate(seconds_margin = time_margin*3600)


tdf_winners |> group_by(winner_team) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_winners |> arrange(desc(stages_led))


ggplot(data = tdf_winners, aes(y = seconds_margin, x = start_date)) +
  geom_col()

ggplot(data = tdf_winners, aes(x = height, y = weight)) +
  geom_point() +
  geom_label(aes(label = winner_name))

tdf_winners |> filter(stage_wins == 0)


avg_speed <- tdf_winners |> mutate(avg_speed = distance/time_overall) |> select(-9) |> select(edition, start_date, winner_name, winner_team, distance, time_overall, avg_speed, time_margin, everything())




tdf_winners |> filter(start_date < 2005-08-30) |> group_by(nationality) |> summarise(wins = n()) |> arrange(desc(wins))

tdf_winners |> filter(start_date > 2005-08-30) |> group_by(nationality) |> summarise(wins = n()) |> arrange(desc(wins))


winner_boxplot <- tdf_winners |> mutate(ind_half = if_else(start_date > 2005-08-30, true = 2, false = 1))


ggplot(data = winner_boxplot, aes(x = ind_half, y = seconds_margin)) +
  geom_boxplot(aes(group = ind_half))
```


```{r}
tdf_winners |> mutate(era = case_when((edition < 37) ~ "Amphetamine",
                                     (edition >= 37 & edition < 53) ~ "Anti-Doping",
                                     (edition >= 53 & edition < 77) ~ "Steroid",
                                     (edition >= 77 & edition < 97) ~ "EPO",
                                      (edtion >= 97) ~ "Clean"))
```



```{r}
ggplot(data = tdf_winners, aes(x = weight, y = time_margin)) +
  geom_point()

ggplot(data = avg_speed, aes(x = start_date, y = avg_speed)) +
  geom_col(fill = "green", color = "black")

tdf_winners |> slice(80:105)
```


## 2019 Stage Results
```{r}

tdf_url_vec <- c("https://www.procyclingstats.com/race/tour-de-france/2019/stage-1",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-2",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-3",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-4",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-5",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-6",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-7",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-8",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-9",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-10",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-11",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-12",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-13",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-14",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-15",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-16",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-17",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-18",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-19",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-20",
"https://www.procyclingstats.com/race/tour-de-france/2019/stage-21")

```



```{r}

tdf_2019 <- function(tdf_url) {
  tdf_tab <- read_html(tdf_url) |> html_nodes("table")
  tdf_2019 <- tdf_tab[[1]] |> html_table()
  
  return(tdf_2019)
}

tdf_2019_stage <- map(tdf_url_vec, tdf_2019)
tdf_2019_stage

c(19, 18, 17, 16, 14, 13, 12, 11, 9, 8, 6)   
## remove stage 2

```

```{r}
stage1_2019 <- tdf_2019_stage[[1]] |> select(-12) |> mutate(stage = 1)
stage3_2019 <- tdf_2019_stage[[3]] |> select(-12) |> mutate(stage = 3)
stage4_2019 <- tdf_2019_stage[[4]] |> select(-12) |> mutate(stage = 4)
stage5_2019 <- tdf_2019_stage[[5]] |> select(-12) |> mutate(stage = 5)
stage6_2019 <- tdf_2019_stage[[6]] |> select(-12) |> mutate(stage = 6, Rnk = as.integer(Rnk))
stage7_2019 <- tdf_2019_stage[[7]] |> select(-12) |> mutate(stage = 7)
stage8_2019 <- tdf_2019_stage[[8]] |> select(-12) |> mutate(stage = 8, Rnk = as.integer(Rnk))
stage9_2019 <- tdf_2019_stage[[9]] |> select(-12) |> mutate(stage = 9, Rnk = as.integer(Rnk))
stage10_2019 <- tdf_2019_stage[[10]] |> select(-12) |> mutate(stage = 10)
stage11_2019 <- tdf_2019_stage[[11]] |> select(-12) |> mutate(stage = 11, Rnk = as.integer(Rnk))
stage12_2019 <- tdf_2019_stage[[12]] |> select(-12) |> mutate(stage = 12, Rnk = as.integer(Rnk))
stage13_2019 <- tdf_2019_stage[[13]] |> select(-12) |> mutate(stage = 13, Rnk = as.integer(Rnk))
stage14_2019 <- tdf_2019_stage[[14]] |> select(-12) |> mutate(stage = 14, Rnk = as.integer(Rnk))
stage15_2019 <- tdf_2019_stage[[15]] |> select(-12) |> mutate(stage = 15, Rnk = as.integer(Rnk))
stage16_2019 <- tdf_2019_stage[[16]] |> select(-12) |> mutate(stage = 16, Rnk = as.integer(Rnk))
stage17_2019 <- tdf_2019_stage[[17]] |> select(-12) |> mutate(stage = 17, Rnk = as.integer(Rnk))
stage18_2019 <- tdf_2019_stage[[18]] |> select(-12) |> mutate(stage = 18, Rnk = as.integer(Rnk))
stage19_2019 <- tdf_2019_stage[[19]] |> select(-12) |> mutate(stage = 19, Rnk = as.integer(Rnk))
stage20_2019 <- tdf_2019_stage[[20]] |> select(-12) |> mutate(stage = 20)
stage21_2019 <- tdf_2019_stage[[21]] |> select(-12) |> mutate(stage = 21)
```


```{r}
stage_results_2019 <- stage1_2019 |> bind_rows(stage3_2019, stage4_2019, stage5_2019, stage6_2019, stage7_2019, stage8_2019, stage9_2019, stage10_2019, stage11_2019, stage12_2019, stage13_2019, stage14_2019, stage15_2019, stage16_2019, stage17_2019, stage18_2019, stage19_2019, stage20_2019, stage21_2019)

stage_results_2019 <- stage_results_2019 |> mutate(year = 2019)
```


```{r}
stage_results_2019 |> group_by(stage) |> summarise(finishers = n())
```



## Overall GC from 2013-2023 for TDF
```{r}

tdf_past_10 <- c("https://www.procyclingstats.com/race/tour-de-france/2013/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2014/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2015/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2016/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2017/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2018/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2019/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2020/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2021/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2022/gc",
                 "https://www.procyclingstats.com/race/tour-de-france/2023/gc")

```



```{r}


tdf_gc <- function(tdf_gc_url){
    tab_tdf <- read_html(tdf_gc_url) |> html_nodes("table")
  tdf_gc_final <- tab_tdf[[1]] |> html_table() |>
    select(-5,-12)
  return(tdf_gc_final)
}


gc_10 <- map(tdf_past_10, tdf_gc)
tdf_2013 <- gc_10[[1]]
tdf_2014 <- gc_10[[2]]
tdf_2015 <- gc_10[[3]]
tdf_2016 <- gc_10[[4]]
tdf_2017 <- gc_10[[5]]
tdf_2018 <- gc_10[[6]]
tdf_2019 <- gc_10[[7]]
tdf_2020 <- gc_10[[8]]
tdf_2021 <- gc_10[[9]]
tdf_2022 <- gc_10[[10]]
tdf_2023 <- gc_10[[11]]
```


```{r}
tdf_2013 <- tdf_2013 |> mutate(year = 2013, Rnk = as.integer(Rnk))
tdf_2014 <- tdf_2014 |> mutate(year = 2014)
tdf_2015 <- tdf_2015 |> mutate(year = 2015)
tdf_2016 <- tdf_2016 |> mutate(year = 2016, Rnk = as.integer(Rnk))
tdf_2017 <- tdf_2017 |> mutate(year = 2017)
tdf_2018 <- tdf_2018 |> mutate(year = 2018)
tdf_2019 <- tdf_2019 |> mutate(year = 2019)
tdf_2020 <- tdf_2020 |> mutate(year = 2020)
tdf_2021 <- tdf_2021 |> mutate(year = 2021, Rnk = as.integer(Rnk))
tdf_2022 <- tdf_2022 |> mutate(year = 2022, Rnk = as.integer(Rnk))
tdf_2023 <- tdf_2023 |> mutate(year = 2023)


```



```{r}
c(2013, 2016, 2021, 2022)
c(2014, 2015, 2017, 2018, 2019, 2020, 2023)


tdf_gc <- tdf_2013 |> bind_rows(tdf_2014, tdf_2015, tdf_2016, tdf_2017, tdf_2018, tdf_2019, tdf_2020, tdf_2021, tdf_2022, tdf_2023)

tdf_gc <- tdf_gc

```


```{r}
gc_timegap <- tdf_gc |> separate(col = Timelag, into = c("behind", "Gap"), sep = 1) |> 
  separate(col = Gap, into = c("mins", "seconds"), sep = -2) |>
  separate(col = mins, into = c("hrs_mins", "colon"), sep = -1) |>
  separate(col = hrs_mins, into = c("hrs", "minutes"), sep = -2) |>
  separate(col = hrs, into = c("hours", "colon"), sep = -1) |>
  select(-3, -5) |>
  mutate(hours = as.numeric(hours),
         minutes = as.numeric(minutes),
         seconds = as.numeric(seconds)) |>
  mutate(hours = if_else(is.na(hours), 
                         true = 0, 
                         false = hours)) |>
  mutate(tot_seconds = seconds + (60 * minutes) + (3600 * hours))
  
gc_timegap |> select(-13)
```

```{r}
specialty_gap <- gc_timegap |> filter(tot_seconds > 0) |> group_by(Specialty) |> summarise(avg_time = mean(tot_seconds, na.rm = TRUE),
                                                                min_time = min(tot_seconds, na.rm = TRUE))

ggplot(data = specialty_gap, aes(x = min_time, y = Specialty)) +
  geom_col()
```


```{r}
year_gap <- gc_timegap |> filter(tot_seconds > 0) |>
  mutate(year = as.factor(year)) |> 
  group_by(year) |> 
  summarise(avg_time = mean(tot_seconds, na.rm = TRUE),
                            min_time = min(tot_seconds)) |>
  mutate(year = reorder(year, min_time))


ggplot(data = year_gap, aes(x = min_time, y = year)) +
  geom_col()
```


```{r}
sprint_time <- gc_timegap |> filter(Specialty == "Sprint") |> mutate(year = as.factor(year)) |> group_by(year) |> summarise(min_time = min(tot_seconds, na.rm = TRUE)) |> mutate(year = reorder(year, min_time))

ggplot(data = sprint_time, aes(x = min_time, y = year)) +
  geom_col()

```

```{r}
ggplot(data = gc_timegap, aes(x = Specialty, y = tot_seconds)) +
  geom_jitter(aes(group = Specialty, color = Specialty))
```


```{r}
ggplot(data = tdf_gc, aes(x = Specialty, y = GC)) +
  geom_jitter(aes(group = Specialty, color = Specialty))
```

```{r}
ggplot(data = tdf_gc, aes(x = Specialty, y = Rnk)) +
  geom_jitter(aes(group = Specialty, color = Specialty))
```

```{r}
top_time <- gc_timegap |> group_by(Specialty) |> arrange(tot_seconds) |> slice(1:100)

ggplot(data = top_time, aes(x = Specialty, y = tot_seconds)) +
  geom_boxplot()
```












## 2020 Tour de France Stages
```{r}

tdf20_url_vec <- c("https://www.procyclingstats.com/race/tour-de-france/2020/stage-1",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-2",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-3",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-4",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-5",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-6",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-7",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-8",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-9",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-10",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-11",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-12",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-13",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-14",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-15",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-16",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-17",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-18",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-19",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-20",
"https://www.procyclingstats.com/race/tour-de-france/2020/stage-21")

```


```{r}
tdf_2020_stage <- map(tdf20_url_vec, tdf_2019)
tdf_2020_stage

c(1, 2, 3, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)
```

```{r}

stage1_2020 <- tdf_2020_stage[[1]] |> select(-12) |> mutate(stage = 1, Rnk = as.integer(Rnk))
stage2_2020 <- tdf_2020_stage[[2]] |> select(-12) |> mutate(stage = 2, Rnk = as.integer(Rnk))
stage3_2020 <- tdf_2020_stage[[3]] |> select(-12) |> mutate(stage = 3, Rnk = as.integer(Rnk))
stage4_2020 <- tdf_2020_stage[[4]] |> select(-12) |> mutate(stage = 4)
stage5_2020 <- tdf_2020_stage[[5]] |> select(-12) |> mutate(stage = 5)
stage6_2020 <- tdf_2020_stage[[6]] |> select(-12) |> mutate(stage = 6)
stage7_2020 <- tdf_2020_stage[[7]] |> select(-12) |> mutate(stage = 7)
stage8_2020 <- tdf_2020_stage[[8]] |> select(-12) |> mutate(stage = 8, Rnk = as.integer(Rnk))
stage9_2020 <- tdf_2020_stage[[9]] |> select(-12) |> mutate(stage = 9, Rnk = as.integer(Rnk))
stage10_2020 <- tdf_2020_stage[[10]] |> select(-12) |> mutate(stage = 10, Rnk = as.integer(Rnk))
stage11_2020 <- tdf_2020_stage[[11]] |> select(-12) |> mutate(stage = 11, Rnk = as.integer(Rnk))
stage12_2020 <- tdf_2020_stage[[12]] |> select(-12) |> mutate(stage = 12, Rnk = as.integer(Rnk))
stage13_2020 <- tdf_2020_stage[[13]] |> select(-12) |> mutate(stage = 13, Rnk = as.integer(Rnk))
stage14_2020 <- tdf_2020_stage[[14]] |> select(-12) |> mutate(stage = 14, Rnk = as.integer(Rnk))
stage15_2020 <- tdf_2020_stage[[15]] |> select(-12) |> mutate(stage = 15, Rnk = as.integer(Rnk))
stage16_2020 <- tdf_2020_stage[[16]] |> select(-12) |> mutate(stage = 16, Rnk = as.integer(Rnk))
stage17_2020 <- tdf_2020_stage[[17]] |> select(-12) |> mutate(stage = 17, Rnk = as.integer(Rnk))
stage18_2020 <- tdf_2020_stage[[18]] |> select(-12) |> mutate(stage = 18, Rnk = as.integer(Rnk))
stage19_2020 <- tdf_2020_stage[[19]] |> select(-12) |> mutate(stage = 19, Rnk = as.integer(Rnk))
stage20_2020 <- tdf_2020_stage[[20]] |> select(-12) |> mutate(stage = 20)
stage21_2020 <- tdf_2020_stage[[21]] |> select(-12) |> mutate(stage = 21)
```

```{r}
stage_results_2020 <- stage1_2020 |> bind_rows(stage2_2020, stage3_2020, stage4_2020, stage5_2020, stage6_2020, stage7_2020, stage8_2020, stage9_2020, stage10_2020, stage11_2020, stage12_2020, stage13_2020, stage14_2020, stage15_2020, stage16_2020, stage17_2020, stage18_2020, stage19_2020, stage20_2020, stage21_2020,)

stage_results_2020 <- stage_results_2020 |> mutate(year = 2020)
```

```{r}
stage_results_2020 |> group_by(Team) |> filter(Rnk == 1) |> summarise(wins = n())

stage_results_2020 |> group_by(Specialty) |> filter(Rnk == 1) |> summarise(wins = n())

stage_results_2020 |> group_by(Rider) |> slice(1)

stage_results_2020 |> group_by(stage) |> summarise(finishers = n()) |> slice(3:21)

```


## 2021 Tour de France

```{r}
tdf21_url_vec <- c("https://www.procyclingstats.com/race/tour-de-france/2021/stage-1",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-2",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-3",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-4",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-5",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-6",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-7",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-8",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-9",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-10",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-11",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-12",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-13",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-14",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-15",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-16",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-17",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-18",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-19",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-20",
"https://www.procyclingstats.com/race/tour-de-france/2021/stage-21")

```

```{r}
tdf_2021_stage <- map(tdf21_url_vec, tdf_2019)
tdf_2021_stage

c(19, 17, 16, 15, 14, 13, 12, 11, 10, 9, 4, 3, 2, 1)
```

```{r}

stage1_2021 <- tdf_2021_stage[[1]] |> select(-12) |> mutate(stage = 1, Rnk = as.integer(Rnk))
stage2_2021 <- tdf_2021_stage[[2]] |> select(-12) |> mutate(stage = 2, Rnk = as.integer(Rnk))
stage3_2021 <- tdf_2021_stage[[3]] |> select(-12) |> mutate(stage = 3, Rnk = as.integer(Rnk))
stage4_2021 <- tdf_2021_stage[[4]] |> select(-12) |> mutate(stage = 4, Rnk = as.integer(Rnk))
stage5_2021 <- tdf_2021_stage[[5]] |> select(-12) |> mutate(stage = 5)
stage6_2021 <- tdf_2021_stage[[6]] |> select(-12) |> mutate(stage = 6)
stage7_2021 <- tdf_2021_stage[[7]] |> select(-12) |> mutate(stage = 7)
stage8_2021 <- tdf_2021_stage[[8]] |> select(-12) |> mutate(stage = 8)
stage9_2021 <- tdf_2021_stage[[9]] |> select(-12) |> mutate(stage = 9, Rnk = as.integer(Rnk))
stage10_2021 <- tdf_2021_stage[[10]] |> select(-12) |> mutate(stage = 10, Rnk = as.integer(Rnk))
stage11_2021 <- tdf_2021_stage[[11]] |> select(-12) |> mutate(stage = 11, Rnk = as.integer(Rnk))
stage12_2021 <- tdf_2021_stage[[12]] |> select(-12) |> mutate(stage = 12, Rnk = as.integer(Rnk))
stage13_2021 <- tdf_2021_stage[[13]] |> select(-12) |> mutate(stage = 13, Rnk = as.integer(Rnk))
stage14_2021 <- tdf_2021_stage[[14]] |> select(-12) |> mutate(stage = 14, Rnk = as.integer(Rnk))
stage15_2021 <- tdf_2021_stage[[15]] |> select(-12) |> mutate(stage = 15, Rnk = as.integer(Rnk))
stage16_2021 <- tdf_2021_stage[[16]] |> select(-12) |> mutate(stage = 16, Rnk = as.integer(Rnk))
stage17_2021 <- tdf_2021_stage[[17]] |> select(-12) |> mutate(stage = 17, Rnk = as.integer(Rnk))
stage18_2021 <- tdf_2021_stage[[18]] |> select(-12) |> mutate(stage = 18)
stage19_2021 <- tdf_2021_stage[[19]] |> select(-12) |> mutate(stage = 19, Rnk = as.integer(Rnk))
stage20_2021 <- tdf_2021_stage[[20]] |> select(-12) |> mutate(stage = 20)
stage21_2021 <- tdf_2021_stage[[21]] |> select(-12) |> mutate(stage = 21, Rnk = as.integer(Rnk))
```

```{r}
stage_results_2021 <- stage1_2021 |> bind_rows(stage2_2021, stage3_2021, stage4_2021, stage5_2021, stage6_2021, stage7_2021, stage8_2021, stage9_2021, stage10_2021, stage11_2021, stage12_2021, stage13_2021, stage14_2021, stage15_2021, stage16_2021, stage17_2021, stage18_2021, stage19_2021, stage20_2021, stage21_2021)

stage_results_2021 <- stage_results_2021 |> mutate(year = 2021)
```


```{r}
stage_results_2021 |> group_by(Team) |> filter(Rnk == 1) |> summarise(wins = n())

stage_results_2021 |> filter(stage == 1)

stage_results_2021 |> group_by(Specialty) |> filter(stage == 1) |> summarise(riders = n())

stage_results_2021 |> group_by(stage) |> summarise(finishers = n()) |> slice(3:21)
```



## 2022 Tour de France
```{r}
tdf22_url_vec <- c("https://www.procyclingstats.com/race/tour-de-france/2022/stage-1",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-2",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-3",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-4",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-5",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-6",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-7",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-8",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-9",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-10",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-11",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-12",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-13",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-14",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-15",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-16",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-17",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-18",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-19",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-20",
"https://www.procyclingstats.com/race/tour-de-france/2022/stage-21")

```

```{r}
tdf_2022_stage <- map(tdf22_url_vec, tdf_2019)
tdf_2022_stage

c(21, 20, 19, 18, 17, 16, 15, 13, 11, 10, 9, 8, 6, 5)
```

```{r}

stage1_2022 <- tdf_2022_stage[[1]] |> select(-12) |> mutate(stage = 1)
stage2_2022 <- tdf_2022_stage[[2]] |> select(-12) |> mutate(stage = 2)
stage3_2022 <- tdf_2022_stage[[3]] |> select(-12) |> mutate(stage = 3)
stage4_2022 <- tdf_2022_stage[[4]] |> select(-12) |> mutate(stage = 4)
stage5_2022 <- tdf_2022_stage[[5]] |> select(-12) |> mutate(stage = 5, Rnk = as.integer(Rnk))
stage6_2022 <- tdf_2022_stage[[6]] |> select(-12) |> mutate(stage = 6, Rnk = as.integer(Rnk))
stage7_2022 <- tdf_2022_stage[[7]] |> select(-12) |> mutate(stage = 7)
stage8_2022 <- tdf_2022_stage[[8]] |> select(-12) |> mutate(stage = 8, Rnk = as.integer(Rnk))
stage9_2022 <- tdf_2022_stage[[9]] |> select(-12) |> mutate(stage = 9, Rnk = as.integer(Rnk))
stage10_2022 <- tdf_2022_stage[[10]] |> select(-12) |> mutate(stage = 10, Rnk = as.integer(Rnk))
stage11_2022 <- tdf_2022_stage[[11]] |> select(-12) |> mutate(stage = 11, Rnk = as.integer(Rnk))
stage12_2022 <- tdf_2022_stage[[12]] |> select(-12) |> mutate(stage = 12)
stage13_2022 <- tdf_2022_stage[[13]] |> select(-12) |> mutate(stage = 13, Rnk = as.integer(Rnk))
stage14_2022 <- tdf_2022_stage[[14]] |> select(-12) |> mutate(stage = 14)
stage15_2022 <- tdf_2022_stage[[15]] |> select(-12) |> mutate(stage = 15, Rnk = as.integer(Rnk))
stage16_2022 <- tdf_2022_stage[[16]] |> select(-12) |> mutate(stage = 16, Rnk = as.integer(Rnk))
stage17_2022 <- tdf_2022_stage[[17]] |> select(-12) |> mutate(stage = 17, Rnk = as.integer(Rnk))
stage18_2022 <- tdf_2022_stage[[18]] |> select(-12) |> mutate(stage = 18, Rnk = as.integer(Rnk))
stage19_2022 <- tdf_2022_stage[[19]] |> select(-12) |> mutate(stage = 19, Rnk = as.integer(Rnk))
stage20_2022 <- tdf_2022_stage[[20]] |> select(-12) |> mutate(stage = 20, Rnk = as.integer(Rnk))
stage21_2022 <- tdf_2022_stage[[21]] |> select(-12) |> mutate(stage = 21, Rnk = as.integer(Rnk))
```

```{r}
stage_results_2022 <- stage1_2022 |> bind_rows(stage2_2022, stage3_2022, stage4_2022, stage5_2022, stage6_2022, stage7_2022, stage8_2022, stage9_2022, stage10_2022, stage11_2022, stage12_2022, stage13_2022, stage14_2022, stage15_2022, stage16_2022, stage17_2022, stage18_2022, stage19_2022, stage20_2022, stage21_2022)

stage_results_2022 <- stage_results_2022 |> mutate(year = 2022)
```

```{r}
stage_results_2022 |> group_by(stage) |> summarise(finishers = n()) |> slice(3:21)
```



## 2023 Tour de France



```{r}
tdf23_url_vec <- c("https://www.procyclingstats.com/race/tour-de-france/2023/stage-1",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-2",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-3",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-4",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-5",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-6",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-7",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-8",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-9",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-10",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-11",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-12",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-13",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-14",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-15",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-16",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-17",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-18",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-19",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-20",
"https://www.procyclingstats.com/race/tour-de-france/2023/stage-21")

```

```{r}
tdf_2023_stage <- map(tdf23_url_vec, tdf_2019)
tdf_2023_stage
```

```{r}

stage1_2023 <- tdf_2023_stage[[1]] |> select(-12) |> mutate(stage = 1, Rnk = as.integer(Rnk))
stage2_2023 <- tdf_2023_stage[[2]] |> select(-12) |> mutate(stage = 2, Rnk = as.integer(Rnk))
stage3_2023 <- tdf_2023_stage[[3]] |> select(-12) |> mutate(stage = 3)
stage4_2023 <- tdf_2023_stage[[4]] |> select(-12) |> mutate(stage = 4)
stage5_2023 <- tdf_2023_stage[[5]] |> select(-12) |> mutate(stage = 5, Rnk = as.integer(Rnk))
stage6_2023 <- tdf_2023_stage[[6]] |> select(-12) |> mutate(stage = 6)
stage7_2023 <- tdf_2023_stage[[7]] |> select(-12) |> mutate(stage = 7)
stage8_2023 <- tdf_2023_stage[[8]] |> select(-12) |> mutate(stage = 8, Rnk = as.integer(Rnk))
stage9_2023 <- tdf_2023_stage[[9]] |> select(-12) |> mutate(stage = 9, Rnk = as.integer(Rnk))
stage10_2023 <- tdf_2023_stage[[10]] |> select(-12) |> mutate(stage = 10)
stage11_2023 <- tdf_2023_stage[[11]] |> select(-12) |> mutate(stage = 11)
stage12_2023 <- tdf_2023_stage[[12]] |> select(-12) |> mutate(stage = 12, Rnk = as.integer(Rnk))
stage13_2023 <- tdf_2023_stage[[13]] |> select(-12) |> mutate(stage = 13, Rnk = as.integer(Rnk))
stage14_2023 <- tdf_2023_stage[[14]] |> select(-12) |> mutate(stage = 14, Rnk = as.integer(Rnk))
stage15_2023 <- tdf_2023_stage[[15]] |> select(-12) |> mutate(stage = 15, Rnk = as.integer(Rnk))
stage16_2023 <- tdf_2023_stage[[16]] |> select(-12) |> mutate(stage = 16, Rnk = as.integer(Rnk))
stage17_2023 <- tdf_2023_stage[[17]] |> select(-12) |> mutate(stage = 17, Rnk = as.integer(Rnk))
stage18_2023 <- tdf_2023_stage[[18]] |> select(-12) |> mutate(stage = 18, Rnk = as.integer(Rnk))
stage19_2023 <- tdf_2023_stage[[19]] |> select(-12) |> mutate(stage = 19)
stage20_2023 <- tdf_2023_stage[[20]] |> select(-12) |> mutate(stage = 20, Rnk = as.integer(Rnk))
stage21_2023 <- tdf_2023_stage[[21]] |> select(-12) |> mutate(stage = 21)
```

```{r}
stage_results_2023 <- stage1_2023 |> bind_rows(stage2_2023, stage3_2023, stage4_2023, stage5_2023, stage6_2023, stage7_2023, stage8_2023, stage9_2023, stage10_2023, stage11_2023, stage12_2023, stage13_2023, stage14_2023, stage15_2023, stage16_2023, stage17_2023, stage18_2023, stage19_2023, stage20_2023, stage21_2023)

stage_results_2023 <- stage_results_2023 |> mutate(year = 2023)
```


## 5 Years of Stage Results

```{r}
stage_results <- stage_results_2023 |> bind_rows(stage_results_2022, stage_results_2021, stage_results_2020, stage_results_2019)
stage_results <- stage_results |> select(-5)
```

```{r}
stage_results |> group_by(Rider) |> summarise(average_place = mean(GC), n()) |> arrange(average_place)

stage_results |> group_by(Rider) |> slice(1)

stage_results |> group_by(Team) |> filter(Rnk == 1) |> summarise(wins = n()) |> arrange(desc(wins))

stage_results |> filter(BIB == 1, Rnk == 1)

stage_results |> filter(Specialty == "TT", Rnk == 1)
```

```{r}
stage_results |> filter(Rnk == 1) |> group_by(Specialty) |>
   summarise(n())

winners <- stage_results |> filter(Rnk == 1)

ggplot(data = winners, aes(x = Specialty)) +
  geom_bar(aes(fill = Specialty)) 
```

```{r}
stage_results |> filter(!is.na(Avg)) |> group_by(stage, year) |> summarise(n())
```

```{r}
time_stage_res <- stage_results |> separate(col = Timelag, into = c("behind", "Gap"), sep = 1) |> 
  separate(col = Gap, into = c("mins", "seconds"), sep = -2) |>
  separate(col = mins, into = c("hrs_mins", "colon"), sep = -1) |>
  separate(col = hrs_mins, into = c("hrs", "minutes"), sep = -2) |>
  separate(col = hrs, into = c("hours", "colon"), sep = -1) |>
  select(-3, -5) |>
  mutate(hours = as.numeric(hours),
         minutes = as.numeric(minutes),
         seconds = as.numeric(seconds)) |>
  mutate(hours = if_else(is.na(hours), 
                         true = 0, 
                         false = hours)) |>
  mutate(tot_seconds = seconds + (60 * minutes) + (3600 * hours))
  
```


```{r}
gaps <- time_stage_res |> group_by(stage, year) |> 
  filter(GC != 1) |> 
  summarise(min_gap = min(tot_seconds)) |>
  arrange(min_gap) |>
  filter(min_gap > 0)
  
  
```



