---
title: Synergistic Interactions in League of Legends
author: "George Charalambous"
date: "February 29, 2024"
description: This module focuses on examining the synergistic relationships between champions in the AD Carry and Support roles within the popular video game, League of Legends. Through Chi-Squared analysis, we will assess potential interactions among the top five most-selected champions in these positions to determine if any statistically significant relationships exist.

categories:
  - Chi-Squared
  - Predictor Categories
  - Relationship
---

## Motivation

League of Legends is a popular multiplayer online battle arena (MOBA) game where two teams of five players compete on a map called Summoner's Rift. Each player selects a champion with unique abilities and plays a specific role on the team.

Summoner's Rift is divided into three lanes: top, middle, and bottom. The bottom lane, also known as the bot lane, is where you typically find the ADC (Attack Damage Carry) and Support champions.

The ADC's primary objective is to deal sustained damage throughout the game. They rely on items and experience to scale their damage output and become late-game threats. Conversely, the Support champions focus on providing utility, crowd control, and protection to enable the ADC to thrive. This includes abilities that heal, shield, or buff their ADC, as well as crowd control spells to disrupt enemies.

Analyzing gameplay data allows us to identify the most successful ADC and Support champion combinations based on their win rates. By assessing these statistics, we can determine the top 5 ADC and Support champions, and beyond those, other ADC and Support champions fall into the "other" category. Hence, using Chi-Squared analysis, we will evaluate if specific pairings exhibit exceptional synergy. This synergy between ADC and Support is crucial for securing objectives, winning team fights, and ultimately achieving victory on the battlefield.

## Data

The data used in this study comprises three distinct data sets, each representing popular champions in the Attack Damage Carry (ADC) and Support roles, along with less significant combinations grouped under the "Rest" category. The ADC dataset includes information on the most frequently chosen champions from a pool of 17, while the Support dataset covers 19 such champions. The remaining 36 combinations are categorized as "Rest". As a result, the study incorporates the five most selected ADC and Support champions, alongside the remaining champions grouped under the "Rest" category, resulting in a 6x6 table.

| Variable | Description                            |
|----------|----------------------------------------|
| ADC      | The ADC champion used in the match     |
| SUP      | The Support champion used in the match |
| count    | The number of games for each champion  |

: [filename.csv](~/Desktop/Sixth%20Semester/Stat289Spring2024/gchar21/ADC.csv) (\~/Desktop/Sixth%20Semester/Stat289Spring2024/gchar21/SUP.csv) (\~/Desktop/Sixth%20Semester/Stat289Spring2024/gchar21/Rest.csv)

## Questions

1.  Identify the variables of interest in this study. Are they categorical or numerical? If categorical, identify the levels of each variable.

2.  What percent of games did the combination of Jinx in the ADC role and Braum in the Support role appear?

3.  Is there evidence that the selection of a specific champion in the Support role is related to the selection of a specific champion in the ADC role?

4.  What combination of champions contributes the most to the test statistic?

## References

Riot Games Developer Portal. Accessed \[February 29, 2024\]. Available at: `https://developer.riotgames.com/apis`

Ramler, I, Lee, C.S., and Schuckers, M. (2019) "Identifying Symbiotic Relationships between Champions in League of Legends." Proceedings for the 2019 Joint Statistical Meetings, Sports Statistics Section. Alexandria, VA: American Statistical Association. 2362 -- 2369.
