---
title: "SkiData"
format: html
---

Load needed libraries

```{r}
library(rvest)
library(chromote)
library(tidyverse)
library(lubridate)
```

Pick a page to scrape from and read it with embedded chrome browser

```{r}
url <- "https://live.fis-ski.com/cc-2257/results-pda.htm"

newpage <- ChromoteSession$new()
{
  newpage$Page$navigate(url)
  newpage$Page$loadEventFired()
}
newpage$view()
```

Extract all the html elements

```{r}
elements <- newpage$Runtime$evaluate("document.querySelector('html').outerHTML")$result$value |>
  read_html()
```

```{r}
newpage$close()
```

Get everything with a certain "tag" and extract any of the text in those elements

```{r}
Dist= c(2,5.2,7.5,11)

Bib <- elements |>
  html_elements(".col_bib") |>
  html_text2()

Rank <- elements |>
  html_elements(".col_rank") |>
  html_text2()

Name <- elements |>
  html_elements(".col_name") |>
  html_text2()

NSA <- elements |>
  html_elements(".col_nsa") |>
  html_text2()

Result <- elements |>
  html_elements(".col_result") |>
  html_text2()

Diff <- elements |>
  html_elements(".col_diff") |>
  html_text2()
```

```{r}
x <- data.frame(Bib, Name, NSA, Rank, Result, Diff)
x <- x[x$Bib!="Bib",]
```

```{r}
rows=dim(x)[1]
n=rows/4

x$Bib=as.numeric(x$Bib)
x$Rank=as.numeric(x$Rank)
x$Diff=as.numeric(x$Diff)

x$Result<-x$Result |> ms() |> period_to_seconds()
x$Result<-round(x$Result/60,3)

group1 <- x[1: (n-3),]
group2 <- x[(n+1):(2*n-3),]
group3 <- x[(2*n+1):(3*n-3),]
group4 <- x[(3*n+1):(4*n-3),]

group1$Dist1 = Dist[1]
group2$Dist2 = Dist[2]
group3$Dist3 = Dist[3]
group4$Dist4 = Dist[4]

names(group1)[4:6]=c("Rank1", "Time1", "Diff1")
names(group2)[4:6]=c("Rank2", "Time2", "Diff2")
names(group3)[4:6]=c("Rank3", "Time3", "Diff3")
names(group4)[4:6]=c("Rank4", "Time4", "Diff4")

```

```{r}
y<-group1 |> left_join(group2) |> left_join(group3) |> left_join(group4)
y <- arrange(y, Rank4)
y$event = 2257
```

```{r}
y <- y |> as.tibble()
y2 <- y |> pivot_longer(c("Dist1", "Dist2", "Dist3", "Dist4"), names_to = "Interval", values_to = "Distance") 
y2$Interval <- str_replace_all(y$Interval, "Dist", "")
tro10k_f <- y2
tro10k_f |> pivot_longer(c("Rank1", "Rank2", "Rank3", "Rank4"), names_to = "Rank", values_to = "Rank") 
```

```{r}
write.csv(y, "awsmit22/ski data/W10kTro_2257.csv", row.names = FALSE)
```

