---
title: "2018-2023 Badminton World Tour Points Head To Head"
author:
  - name: Abigail Smith
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: June 28, 2024
description: Analyzing wins and points head to head in singles and doubles in the Badminton World Tour from 2018-2023. 
categories:
  -  Histograms
  -  Summary Statistics
  -  Side-By-Side Boxplots
  -  T.Test for Difference in Means
  -  Linear Regression Analysis
  -  Confidence Intervals
---

### Welcome video

{{< video  title="2018-2023 Badminton World Tour Points Head To Head" >}}

### Introduction

This activity examines the `wins` and `points for` players at the [Badminton World Tour from 2018-2023](https://en.wikipedia.org/wiki/BWF_World_Tour){target="_blank"}. 

[Badminton](https://en.wikipedia.org/wiki/badminton){target="_blank"} is
a racket sport played by pairs (`Doubles`) or individuals (`Singles`).
Badminton takes place on a court with a net in the middle separating the
opponents. Players use rackets to hit a feathered ball known as the
birdie across the net. Matches are won through the best of three games,
each match is won by the first team to get 21 points. Points are won
when the birdie hits the ground in the opposing side's court.

While often considered a recreational sport, it is also played at the
professional and
[Olympic](https://olympics.com/en/news/badminton-guide-how-to-play-rules-olympic-history){target="_blank"} level. The [BWF Badminton World Tour](https://en.wikipedia.org/wiki/BWF_World_Tour){target="_blank"} is
a tournament series with opens hosted in different countries around the
world. The tour has been running since 2018 and even took place in 2020
despite the covid-19 pandemic. Statistics have been compiled from each
World Tour, a notable statistic being the `Points H2H` which looks at
the points for (`pts_for`) a player and the points against (`pts_agst`) them.

Through statistical analysis, patterns can be identified in this [badminton dataset](badminton.csv){target="_blank"}(badminton.csv). Investigating the distribution of the `Wins` variable will highlight any patterns and what factors might impact winning in badminton at the World Tour Level. 

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity could be used as a quiz, an in class or take home assignment. 
:::



::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, students will be able to:

1.  Assess a variable's distribution
2.  Assess the difference in means for two groups
3.  Fit a simple linear regression model
4.  Evaluate the overall fit of a simple linear regression model
5.  Find the confidence interval of a slope
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Students will use a basic understanding of histograms to evaluate a variable's distribution. Students will also use side-by-side boxplots to assess the distribution of grouped data. Students will further assess the difference in groups, using a t.test for a difference in means. Additionally, students will use hypothesis tests to assess the overall fit of a simple linear model. They can also find the confidence interval of a slope. 
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
This worksheet will require the use of basic statistical software such as Base R or an equivalent level. 
:::

### Data

The data set has 185 rows with 9 variables. Each row is a player who participated in the World Tour. The data set has 5 years worth of data from 2018-2023, the players' statistics are cumulative over the 5 years.

Download data: 

: [badminton.csv](badminton.csv){target="_blank"}

<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description |
|----------------------|-------------------------------------------------|
| `Player` | The name of the player competing. |
| `Category` | The category of competition the player competed in, either `Singles` or `Doubles`. |
| `Matches` | The total number of matches the player played in between 2018-2023 in the World Tour. |
| `Wins` | The total number of wins the player had between 2018-2023 in the World Tour. |
| `Losses` | The total number of losses the player had between 2018-2023 in the World Tour. |
| `pts_for` | The total number of points scored by the player between 2018-2023 in the World Tour. |
| `pts_agst` | The total number of points allowed by the player between 2018-2023 in the World Tour. |
| `win_pct` | The cumulative win percentage (`Wins`/`Matches`) for the player between 2018-2023 in the World Tour. |
| `shot_pct` | The cumulative shot percentage (`pts_for`/(`pts_for` + `pts_agst`)) for the player between 2018-2023 in the World Tour. |


**Data Source**

[Original Dataset](https://www.badmintonstatistics.net/Reports?reportname=MostPointsH2H&category=%&year=-1&level=worldtour&country=%){target="_blank"}

**More information on the rules and set up**

[Olympic Badminton Rules](https://olympics.com/en/news/badminton-guide-how-to-play-rules-olympic-history){target="_blank"}

[Badminton Wikipedia](https://en.wikipedia.org/wiki/Badminton){target="_blank"}

[BWF Tour Website](https://bwfworldtour.bwfbadminton.com/){target="_blank"}

[BWF Tour Wikipedia](https://en.wikipedia.org/wiki/BWF_World_Tour){target="_blank"}

</details>

### Materials

We provide editable MS Word handouts along with their solutions.

[Worksheet](badminton_worksheet.docx)

[Worksheet Answers](badminton_worksheet_KEY.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
After finishing this activity, students should discern whether or not there are any clear patterns in the data. These patterns can relate to differences in mean `Wins` based on the `Category` of matches. The patterns can also relate to the predictability of the number of career `Wins` a player will have in the World Tour. 
:::
