---
title: "freediving_explore"
format: html
---

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(readr)
library(ggplot2)

diving <- read_csv("continentalDiving.csv")

diving <- diving |> mutate(Gender = as.factor(Gender), Discipline = as.factor(Discipline), Continent = as.factor(Continent), Date = dmy(Date))

static <- diving |> filter(Discipline == "STA")

static <- static |> mutate(Result = ms(Result), Announced = ms(Announced))

static <- static |> mutate(Result = as.duration(Result), Announced = as.duration(Announced))

static <- static |> mutate(prop_over = (Result - Announced)/Result)

static_over <- static |> select(Name, Discipline, Gender, Continent, prop_over)
```

```{r}
vertical <- diving |> filter(Discipline %in% c("VMT", "CWT", "CWTB", "CNF", "FIM"))

vertical <- vertical |> mutate(Result = parse_number(Result), Announced = parse_number(Announced))

vertical <- vertical |> mutate(prop_over = (Result - Announced)/Result)

vertical_over <- vertical |> select(Name, Discipline, Gender, Continent, prop_over)
```

```{r}
horizontal <- diving |> filter (Discipline %in% c("DYN", "DYNB", "DNF"))

horizontal <- horizontal |> mutate(Result = parse_number(Result), Announced = parse_number(Announced))

horizontal <- horizontal |> mutate(prop_over = (Result - Announced)/Result)

horizontal_over <- horizontal |> select(Name, Discipline, Gender, Continent, prop_over)
```

```{r}
distance <- full_join(vertical, horizontal)

distance <- distance |> group_by(Discipline) |> mutate(perc_best = Result/max(Result))

static <- static |> mutate(perc_best = as.double(Result/max(Result)))

static_small <- static |> select(Name, Discipline, Gender, Continent, perc_best)
distance_small <- distance |> select(Name, Discipline, Gender, Continent, perc_best)

diving_perform <- full_join(static_small, distance_small)
```

```{r}
ggplot(diving_perform, aes(x = Discipline, y = perc_best)) +
  geom_boxplot(aes(group = Discipline)) +
  facet_wrap(~Gender)
```


