---
title: "exploration"
author: "Brendan Karadenes"
format: html
---

```{r}
library(tidyverse)
library(here)
horseracing <- read.csv(here("bkaradenes/Horseracing_Module/exploration/triple-crown.csv"))
```



# Impact of Poor Track Conditions on low odds horse winning

```{r}
ggplot(data = horseracing, mapping = aes(x = Odds, y = final_place)) +
  geom_point()
```

```{r}
poor_track <- horseracing %>%
  filter(final_place < 4,
         track_condition == "Fast")
```

```{r}
ggplot(data = poor_track, mapping = aes(x = Odds, y = final_place)) +
  geom_point()
```

```{r}
horse_graph <- horseracing %>%
  filter(final_place == 1,
         track_condition == "Sloppy")
```

```{r}
sloppy_track <- horseracing %>%
  filter(track_condition == "Sloppy")
```

```{r}
ggplot(data = horseracing, mapping = aes(x = track_condition, y = Odds)) +
  geom_boxplot() + 
  theme_minimal()
```

```{r}
first <- horseracing %>%
  filter(final_place == 1)
```

```{r}
ggplot(data = first, mapping = aes(x = track_condition, y = Odds)) +
  geom_boxplot()
```

```{r}
ggplot(data = horceracing, mapping = aes(x = track_condition, y = final_place)) +
  geom_boxplot() +
  theme_minimal()
```

```{r}

horseracing <- horceracing %>%
  mutate(top_3 = ifelse(final_place <= 3, 1, 0))


model <- glm(top_3 ~ Odds + high_temp + low_temp + precipitation_24hrs, data = horseracing, family = binomial)


summary(model)

```

```{r}
favorites <- horseracing %>%
  filter(Odds<=10)
```

```{r}
underdogs <- horseracing %>%
  filter(Odds>=20)
```

```{r}
moda = glm(top_3 ~ Odds + track_condition, data = favorites)
summary(moda)
```

```{r}
modb = glm(top_3 ~ Odds + track_condition, data = underdogs)
summary(modb)
```

