---
title: "badminton_data_exploration"
format: html
---

# Libraries

```{r}
library(tidyverse)
library(modelr)
library(broom)
```

# Data

```{r}
badminton_df <- read_csv("~/Desktop/git/stat_289_score/awsmit22/badminton_module/exploration/badminton.csv")

badminton_df <- badminton_df |> select(!...1)
badminton_df
```

# Graphical Explorations

```{r}
ggplot(data = badminton_df, aes(x = Category, y = `Points For`)) + geom_boxplot() + facet_wrap(~Gender)
```

```{r}
mens_singles <- badminton_df |> filter(Category == "Singles" & Gender == "Men") 

mens_singles_sum <- mens_singles |> group_by(Year) |> summarise(`Points For` = mean(`Points For`))
ggplot(data = mens_singles_sum, aes(x = Year, y = `Points For`)) + geom_line() 
```

```{r}
badminton_sum <- badminton_df |> group_by(Year, Gender, Category) |> summarise(mean_pts_for = mean(`Points For`)) |> filter(Year != 2020)

ggplot(data = badminton_sum, aes(x = Year, y = mean_pts_for, colour = Gender)) + geom_line() + facet_wrap(~Category)
```

```{r}
ggplot(data = badminton_df, aes(x = `Points For`, y = `Points Against`, colour = Gender)) + geom_point(alpha = 0.5) + facet_wrap(~Category) + geom_smooth(method = "lm")
```

```{r}
ggplot(data = badminton_df, aes(x = Wins, y = `Points Against`)) + geom_point()
```

```{r}
ggplot(data = badminton_df, aes(x = `Points For`)) + geom_histogram(bins = 15, colour = "black", fill = "lightblue") + facet_wrap(~Year) + theme_minimal()
```

```{r}
ggplot(data = badminton_df, aes(x = `Points For`, y = Difference))+ geom_point() + geom_smooth(method = "lm")
```

```{r}
ggplot(data = badminton_df, aes(x = `Points For`, y = `Points Against`))+ geom_point() + geom_smooth(method = "lm")
```

```{r}
ggplot(data = badminton_df, aes(x = Category, y = `Points For`)) + geom_boxplot()
```

# Grouping

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Player1, Player2) |> summarise()
```

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Player1, Player2, Opponent1, Opponent2) |> summarise()
```

```{r}
badminton_df |> filter(Category == "Singles") |> group_by(Player1, Opponent1) |> summarise(n_matches = sum(Matches))
```

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Player1, Player2, Opponent2, Opponent1) |> summarise(n_matches = sum(Matches))
```

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Player1, Player2) |> summarise(n_matches = sum(Matches))
```

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Opponent1, Opponent2) |> summarise(n_matches = sum(Matches))
```

```{r}
badminton_df |> group_by(Category) |> summarise(n = n())
```

```{r}
badminton_df |> group_by(Gender) |> summarise(n = n())
```

```{r}
badminton_df |> group_by(Year) |> summarise(n = n())
```

```{r}
badminton_df |> group_by(Player1, Opponent1) |> summarise(n = n())
```

```{r}
badminton_df |> group_by(Player1) |> summarise(mean_rank = mean(Rank))
```

```{r}
badminton_df |> group_by(Player1) |> summarise(n_wins = sum(Wins))
```

```{r}
badminton_df |> filter(Category == "Doubles") |> group_by(Player1, Player2) |> summarise(n_matches = n())

badminton_df |> filter(Category == "Doubles")
```

```{r}
badminton_df |> filter(Player1 == "Se Young AN" | Opponent1 == "Se Young AN") |> group_by(Player1, Player2) |> summarise()
```

# Trying something weird with reorganizing the data

```{r}
names <- badminton_df |> pivot_longer(c("Player1", "Opponent1", "Player2", "Opponent2"), names_to = "Position", values_to = "Name") |> filter(!is.na(Name))
```

```{r}
badminton_df |> filter(Matches > 1) |> arrange(desc(Matches)) |> tail()
```

# Modelling attempts

```{r}
singles <- badminton_df |> filter(Category == "Singles")
mod <- lm(`Points For`~ Gender + Category + Matches + `Points Against` + Rank + Player1 + Opponent1 + Wins + Losses + Difference, data = singles)

mod |> tidy()
```


*t.test for difference in means*

```{r}
t.test(`Points For` ~ Category, data = badminton_df)
```

```{r}
mod_1 <- lm(`Points For` ~ Year, data = badminton_df)
mod_1 |> tidy()
```

```{r}
mod_2 <- lm(`Points For` ~ `Points Against`, data = badminton_df)
mod_2 |> tidy()
```

```{r}
mod_3 <- lm(`Points For` ~ Category, data = badminton_df)
mod_3 |> tidy()
```

```{r}
mod_4 <- lm(`Points For` ~ Gender, data = badminton_df)
mod_4 |> tidy()
```

```{r}
mod_5 <- lm(`Points For` ~ Rank, data = badminton_df)
mod_5 |> tidy()
```

```{r}
mod_6 <- lm(`Points For` ~ Matches, data = badminton_df)
mod_6 |> tidy()
```


