---
title: "Olympic Rowing Medals Between 1896 and 2022"
author:
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Abigail Smith
    affiliation:
      - ref: slu
date: June 6, 2024
description: The total number of medals and the weighted points for nations competing in rowing events in the Summer Olympic Games between 1896 and 2022. 
categories:
  - distribution and skewness
  - outlier detection
  - summary statistics
  - confounding variable
---

### Welcome video

{{< video  title="Olympic Rowing Medals Between 1896 and 2022" >}}

### Introduction

This activity looks at the total number of medals and points for nations in [Olympic rowing between 1896 and 2022](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results?resource=download){target="_blank"}. 

Rowing was added to the Olympics in 1896 and has been in every Summer Olympics since. Rowing races in the Olympic context are typically regatta style, meaning that there are multiple boats racing head to head against each other in multiple lanes. Since 1912, the standard distance for Olympic regattas has been 2000m, but until then there had been a range in distances. The boat that is first to cross the finish line is awarded a gold medal, the second a silver medal, and the third a bronze. Over the course of its time as an Olympic sport there have been 25 different event entries. These events range with the number of rowers in the boat (1, 2, 4, 6, 8, 17), the rigging (inrigged, outrigged), sculling, sweeping, and whether or not they are coxed. An inrigged shell means the riggers (where the oar is attached to the boat) are on the inside of the boat, outrigged shells mean the riggers are on the outside. Sculling is where the rowers have an oar on each side and sweeping is when each rower only has one oar on one side. The coxswain steers the boat and guides the rowers, some events have coxed boats whereas some others do not. The total_medals and total_points have been divided by the number of athletes in each event so that the medals are counted towards the whole team not just the athletes. 

In this activity students will assess the distribution of the medals, obtain summary statistics of the points, identify outliers, and consider a confounding variable. Investigating the data's distribution along with any outliers will provide input on patterns in Olympic rowing medals dispersion.

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity could be used as an example or a short take home assessment.
:::



::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, students will be able to:

1.  Assess and interpret data distribution using histograms
2.  Obtain summary statistics with Base R
3.  Identify outliers with IQR
4.  Evaluate confounding variables through the use of barplots
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Students will use an understanding of histograms and sumamry statistics to assess data distribution. Students will also use the IQR formula to identify outliers as well as be able to have a basic understanding of confounding variables. 

:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
Only question 2 will require the use of Base R, all of the other questions should only require a calculator if need be. 
:::

### Data

In the data set there are 101 nations competing in 25 events, each row represents a combination of an event and the country competing in that event. In total, there are 733 rows with 5 variables. The data is cumulative of the 120 years in the original data set. 

Download data: 

: [medals.csv](medals.csv){target="_blank"}

<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description                                                                    |
|-------------------|-----------------------------------------------------|
| `Event` | The event the nation competed in. |
| `NOC` | National Olympic Committee or the nation competing. |
| `Number of Athletes`| The number of athletes in the boat for that event. |
| `total_medals` | The total number of medals for that country in that event. |
| `total_points` | The total number of points for that country in that event. The points are scaled with a gold medal counting for 3 points, a silver for 2, and a bronze for 1. |



**Data Source**

[Kaggle](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results?resource=download){target="_blank"}

</details>

### Materials

We provide editable MS Word handouts along with their solutions.

[Worksheet](medals_worksheet.docx)

[Worksheet Answers](medals_worksheet_answers.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
This Olympic rowing medals worksheet builds students' understanding of data distribution through histograms, summary statistics, and outliers. It also strengthens students' ability to critically evalutate confounding variables and devising relationships amongst variables through looking at barplots. Additionally, it provides an interesting opportunity for studenst to look at patterns in medals for Olympic rowing. 
:::
