---
title: "Data"
format: html
---

Scrape the data 
```{r}
library(rvest)
library(tidyr)
library(dplyr)
```

# Individual scoring leaders
```{r}
url <- "https://www.espn.com/nhl/stats/player/_/view/skating/table/offensive/sort/goals/dir/desc"
h <- read_html(url)
tab <- h %>% html_nodes("table")
```

```{r}
test <- tab %>% html_table()

head( test[[1]] )
head( test[[2]] )
```
```{r}
names <- test[[1]]
data <- test[[2]]
```

Merge the data
```{r}
nhl_scoring <- bind_cols(names, data)
```



# Team scoring
```{r}
url2 <- "https://www.espn.com/nhl/stats/team"
h2 <- read_html(url2)
tab2 <- h2 %>% html_nodes("table")
```

```{r}
test2 <- tab2 %>% html_table()

head( test2[[1]] )
head( test2[[2]] )
```

```{r}
team <- test2[[1]]
data2 <- test2[[2]]
```

Merge the data
```{r}
teams <- data.frame(Team = c("EDM", "BOS", "BUF", "NJ", "SEA", "FLA", "DAL", "TB", "TOR", "LA", "COL", "NYR", "VAN", "VGK", "CAR", "PIT", "STL", "OTT", "CGY", "WSH", "WPG", "NYI", "MIN", "DET", "SJ", "MTL", "ARI", "NSH", "PHI", "CBJ", "ANA", "CHI"))
teams_data <- bind_cols(teams, data2)
```
