---
title: 'D3 2022 Statistics'
author: Hope Donoghue
date: September 21, 2023
description: Division III women's soccer teams statistics from 2022 season
categories:
  - Correlation
  - Chi-square test for association 
---

## Motivation

Have you ever wondered if you know how many goals the home team scored in a soccer game then can you predict how many goals the opponent scored? Is there a relationship between this? This module will explore this idea with NCAA Division III women's soccer data from the 2022 season including the postseason championship. 


## Data

The data set consists of 3753 games in the 2022 Division III women's soccer season. Each row represents one game in the season.


| Variable | Description |
|----|-------------|
| Away |	Name away team |
| Away Score |	The number of goals the away team scored in game |
| Home |	Name of home team |
| Home Score | The number of goals the home team scored in game |
| Date | Date of game |


## Questions

1. What is the correlation value of Home Score vs. Away Score from the data set? Interpret the correlation value in context.



## References

Data web scraped from the D3soccer.com website. https://www.d3soccer.com/seasons/women/2022/schedule 
  


