---
title: Beijing 2022 Winter Olympics Data
author: Eric Seltzer
date: February 28, 2024
description: These datasets contain both athlete information and medal winner information from the Beijing 2022 Olympic Winter Games.
categories:
  - Data Cleaning
  - Summarization
  - Merging
editor:
  markdown: 
    canonical: true
---

## Motivation

The data comes from a kaggle page that contains a total of 10 different datasets. If we are interested in figuring out which country won the most gold medals, or if certain attributes have an impact on their chances to medal these data sets can show us that. This can be done through cleaning the data, wrangling with dyplr functions, and using join statements.

## Data

There are two datasets here, atheletes and medals.

The first athletes contains information on individual athletes. Each row in this dataset represents a different athlete that competed at the Beijing 2022 Olympic Winter Games. This dataset has 2897 rows and 14 columns.

The second medals contains information on medal winners. Each row in this dataset represents a medal won in the Beijing 2022 Olympic Winter Games. This can mean Gold, Bronze, or Silver medals. This dataset has 694 rows and 12 columns.

| Variable          | Description                 |
|-------------------|-----------------------------|
| name              | Athlete Name                |
| short_name        | Athlete Name(short)         |
| gender            | Athlete Gender              |
| birth_date        | Athlete Date of Birthday    |
| birth_place       | Athlete Place of Birthday   |
| birth_country     | Athlete Country of Birthday |
| country           | Athlete Country             |
| country_code      | Athlete Country Code        |
| discipline        | Discipline.                 |
| discipline_code   | Discipline Code             |
| residence_place   | Athlete Residence Place     |
| residence_country | Athlete Residence Country   |
| height_m/ft       | Athlete Height (m/ft)       |
| url               | Athlete Profile Link        |

| Variable           | Description                       |
|--------------------|-----------------------------------|
| medal_type         | Medal Type (Gold, Bronze, Silver) |
| medal_code         | Medal Number (1, 2, 3)            |
| medal_date         | Date Medal Won                    |
| athlete_short_name | Athlete Name (Short)              |
| athlete_name       | Athlete Name                      |
| athlete_sex        | Athlete Gender                    |
| athlete_link       | Athlete Profile Link              |
| event              | Event Competed In                 |
| country            | Country                           |
| country_code       | Country Code                      |
| discipline         | Discipline                        |
| discipline_code    | Discipline Code                   |

The data tables are available for individual download as csv files

:   [athletes.csv](../data/athletes.csv)

:   [medals.csv](../data/medals.csv)

## Questions

If possible, list some analyses or research questions that could be answered with this dataset, or the types of questions you'd ask students. This is mainly meant to give other instructors ideas for how they could use the data.

## References

Give references to the original source here, such as by pasting the package citation:

Petro (2022). *Beijing 2022 Winter Olympi Games*. R package version 1.3.0, <https://www.kaggle.com/datasets/piterfm/beijing-2022-olympics?resource=download&select=medals.csv>.

If the dataset has a particular license, mention the license here. For example, "Data available under the Creative Commons Attribution license."
