---
title: "Chi-Square_Module"
format: docx
editor: visual
---

```{r}
library(tidyverse)
cdSportMoviesCount <- read.csv("agbign20/data/cdSportMoviesCount.csv")
cdSportMoviesCount <- cdSportMoviesCount[,-1]
```

## Chi-Square STAT-113 Module

1. In your own words, what is a Chi-Square Test of Independence? What questions is the test trying to answer?




2.  Is there a connection between certain types of sports and whether a sport film is more likely to be a comedy or drama movie? Use the data located in cdSportsMoviesCount.csv to address this research question.

```{=html}
<!-- -->
```

(a) State the appropriate hypotheses and check the conditions, report the test statistic, degrees of freedom and p-value, reach a decision and give a conclusion within the context of the problem.






(b) Report the test statistic and degrees of freedom



 

(c) What is the p-value? And what evidence does it show?






(d) Provide a brief summary of the analysis using the top contributors to the chi-square statistic to provide justification.





(e) Based on this example, what can you say about the relationship between the test statistic and the p-value?



