---
title: "Untitled"
author: "Chapman and Ramler"
date: "2023-09-20"
output: html_document
---


```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(rvest)
```


Start by importing the data from IMDb

```{r}
basics = read_tsv("https://datasets.imdbws.com/title.basics.tsv.gz")
ratings = read_tsv("https://datasets.imdbws.com/title.ratings.tsv.gz")
akas = read_tsv("https://datasets.imdbws.com/title.akas.tsv.gz")
```
```{r}
names(akas)[1]="tconst"
```



```{r}
top_n = 10000

allmovies1980 = basics %>%
  filter(titleType == "movie") %>%
  filter(!isAdult) %>%
 # filter(str_detect(genres,"Sport")) %>%
  filter(!str_detect(genres,"Documentary")) %>%
  filter(startYear >=1980) %>%
  left_join(akas, by="tconst") %>%
  filter(language=="en") %>%
  select(tconst,titleType,primaryTitle,startYear,runtimeMinutes,genres,language) %>%
  unique() %>%
  left_join(ratings,by="tconst") %>%
   mutate(
      Rating_Rank = min_rank(desc(averageRating)),
      nVotes_Rank = min_rank(desc(numVotes))
    ) %>%
  filter(nVotes_Rank <= top_n) 
```


```{r}
sportsmovies = read_csv("data/sportsmovies.csv")
allmovies = read_csv("data/allmovies1980.csv")
basketball = read_csv("data/BasketballMovies.csv")
baseball = read_csv("data/BaseballMovies.csv")
football = read_csv("data/FootballMovies.csv")
golf = read_csv("data/GolfMovies.csv")
hockey = read_csv("data/HockeyMovies.csv")
soccer = read_csv("data/SoccerMovies.csv")
figure = read_csv("data/FigureSkatingMovies.csv")
```

```{r}
sportsmovies  = allmovies %>%
  mutate(
    Basketball = ifelse(allmovies$primaryTitle %in% basketball$Title,"Basketball",NA),
    Baseball = ifelse(allmovies$primaryTitle %in% baseball$Title,"Baseball",NA),
    Football = ifelse(allmovies$primaryTitle %in% football$Title,"Football",NA),
    Golf = ifelse(allmovies$primaryTitle %in% golf$Title,"Golf",NA),
    Hockey = ifelse(allmovies$primaryTitle %in% hockey$Title,"Hockey",NA),
    Soccer = ifelse(allmovies$primaryTitle %in% soccer$Title,"Soccer",NA),
    FigureSkating = ifelse(allmovies$primaryTitle %in% figure$Title,"Figure Skating",NA)
  )
```


```{r}
sportsmoviesLong = sportsmovies %>%
  pivot_longer(cols=Basketball:Football,names_to=NULL,values_to="Sport") %>%
  drop_na(Sport)
```

```{r}
sportsmoviesLong=sportsmoviesLong %>%
  mutate(ComedyIND = ifelse(str_detect(genres,"Comedy"),"Comedy",NA),
         DramaIND = ifelse(str_detect(genres,"Drama"),"Drama",NA)) %>%
  pivot_longer(cols=ComedyIND:DramaIND,names_to=NULL,values_to="Type") %>%
  drop_na("Type")
```