---
title: "leg_data"
format: html
editor: visual
---

Scraping data from Ski to Sea
```{r}
library(rvest)
```

2009 Leg Data
```{r}
## provide the URL and name it something (in this case, url).
url <- "https://skitosea.pacificmultisports.com/events/101/results/leg/1"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h %>% html_nodes("table")

#
test <- tab %>% html_table()

xcski_2009 <- test[[1]]
```

XCSKI
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 1
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/leg_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

DOWNHILL
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 2
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/downhill_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

RUN
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 3
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/run_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

ROAD BIKE
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 4
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/roadbike_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

CANOE
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 5
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/canoe_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

XCBIKE
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 6
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/xcbike_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

KAYAK
```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 7
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/kayak_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```