---
title: "SLU SCORE Materials"
format:
   gfm:
     html-math-method: 
       method: webtex
       url: https://latex.codecogs.com/png.image?%5Cbg_black&space;
---

This repository contains the in progress materials for the St. Lawrence University students working on building content for the [SCORE Network](https://scorenetwork.org/){target="_blank"}.

It is maintained by Ivan Ramler, Associate Professor of Statistics and Data Science at St. Lawrence University.

## For SLU Content Creators

We are currently using the following workflow to create materials.

1.  Idea formation

    -   Choose either a sport or phenomenon of interest to investigate

2.  Data acquisition

    -   Find an existing data set (e.g., on Kaggle) or webpages that can be scraped

    -   Clean the data to structure it in a way such that it can address your phenomenon of interest

3.  Data exploration

    -   Play with the data with several statistical methods (graphics, models, etc.) to get a better feel for your data and what is feasible with it

4.  Data Repository

    -   Prepare a submission for the data repository. After you move to the next step, a faculty mentor will review the file(s) and submit it to the [SCORE Network Data Repo](https://data.scorenetwork.org/){target="_blank"} for you.

5.  Worksheets

    -   Create a series of related questions to serve as the main materials for your module. You should model these off of either previously completed modules based on similar statistical topics or from an example given to you by a faculty mentor. o Create details solutions for these. (Tip: Do the solutions as you are writing the questions.)

6.  Module Quarto File

    -   Create the accompanying index.qmd file that contains all the background information related to your module. Based these off of preexisting examples

7.  Ready for Student Review

    -   Find a fellow student that is at similar stage and ask them to review your entire module. This includes working through the worksheet(s). Be sure to reciprocate by reviewing for someone else too. o Incorporate meaningful feedback into your module.

8.  Ready for Faculty Review

    -   A faculty mentor will review your draft module and provide feedback as needed.

9.  Submitted to [SLU SCORE Preprint server](https://iramler.github.io/slu_score_preprints/){target="_blank"}

    -   After the faculty mentor has approved the module, they will add it to the SLU SCORE Preprint server.

10. Submitted to the [SCORE Network](https://scorenetwork.org/submissions.html){target="_blank"}

***SLU Content Creators should update their current status on the shared Google Sheet [here](https://docs.google.com/spreadsheets/d/1j5RsbEb5WMKmQo50e6cLg1d8jb23Wdlbc5o5jl1OwUg/edit?usp=sharing){target="_blank"}.***

### Directory Structure

Please organize your directories is a similar fashion to the [example_student](example_student/){target="_blank"}.

i.e., each module will have its own sub-directory containing the same three sub-directories:

1)  `exploration` - used for your scratch work with acquiring and analyzing the data

2)  `data_repo_submission` - contains the materials needed for the submission to the Data Repository

3)  `module` - contains the materials needed for the submission to the Preprint Server

Be sure to check ouut the examples in each to file .qmd files that you can use as a template for your own.

### Additional Examples

-   Numerous example data repository submissions can be found [here](data_repo_submissions/){target="_blank"}

-   Several example modules can be found [here](example_module/){target="_blank"}
