---
title: "salary_exploration"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
```

```{r}
stats <- read_csv(here::here("esselt21/nba_salary_module/exploration/stats.csv"))

salaries <- read_csv(here::here("esselt21/nba_salary_module/exploration/salaries.csv"))
```

# data cleaning and combining
```{r}
stats <-
  stats |>
  mutate(Player = as_factor(Player),
         Season = as_factor(Season))

salaries <-
  salaries |>
  mutate(Player = as_factor(Player),
         Season = as_factor(Season))
```

```{r}
salaries <-
  salaries |>
  mutate(salary = parse_number(salary),
         inflationAdjSalary = parse_number(inflationAdjSalary))
```

```{r}
stats <-
  stats |>
  group_by(Player, Season) |>
  arrange(desc(G)) |>
  slice(1)
```

```{r}
final <-
  left_join(stats,
            salaries,
            by = c("Player", "Season"))

final <-
  final |>
  distinct()
```

```{r}
final |>
  ggplot(aes(x = MP)) +
  geom_histogram(fill = "lightblue",
                 color = "black")
```

```{r}
final <-
  final |>
  filter(MP > 1500)
```

```{r}
# adding PER
final <-
  final |>
  mutate(
    PER = (
      (FG * 85.910) +
        (STL * 53.897) +
        (`3P` * 51.757) +
        (FT * 46.845) +
        (BLK * 39.190) +
        (ORB * 39.190) +
        (AST * 34.677) +
        (DRB * 14.707) -
        (PF * 17.174) -
        ((FTA - FT) * 20.091) -
        ((FGA - FG) * 39.190) -
        (TOV * 53.897)
    ) * (1 / MP)
  )
```

```{r}
final |>
  ggplot(aes(x = PER)) +
  geom_histogram(fill = 'lightblue',
                 color = 'black')
```

```{r}
final <-
  final |>
  na.omit()
```

```{r}
final <-
  final |>
  mutate(logInflationAdjustedSalary = log(inflationAdjSalary / 1000))
```

```{r}
final <-
  final |>
  mutate(ESPR = PER / (logInflationAdjustedSalary * 2))
```

```{r}
final |>
  ggplot(aes(x = logInflationAdjustedSalary)) +
  geom_histogram(fill = 'lightblue',
                 color = 'black')
```

```{r}
mean(final$PER_Salary_ratio)
```

```{r}
final |>
  ggplot(aes(x = logInflationAdjustedSalary,
             y = PER,
             label = Player)) +
  geom_point() +
  geom_abline(slope = 1,
              intercept = 0)
```

```{r}
final |>
  ggplot(aes(x = logInflationAdjustedSalary * 2,
             y = PER,
             label = Player)) +
  geom_point() +
  geom_abline(slope = 1,
              intercept = 0)
```

```{r}
final <-
  final |>
  relocate(logInflationAdjustedSalary, .after = inflationAdjSalary)
```

```{r}
write_csv(final, here::here("esselt21/nba_salary_module/exploration/nba_salary.csv"))
```

```{r}
# most recent season
season <-
  final |>
  filter(Season == 2021)
```