---
title: "wnba"
output: html_document
date: "2023-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Import CSV
wins <- read_csv("data/wins.csv")
```

```{r}
# Load Packages
library(tidyverse)
library(ggplot2)
library(lubridate)
```

## Does mid season record predict season record? 

### Linear Regression Model
```{r}
model <- lm(win_percent ~ half_percent, data = wins) 
summary(model)
```

### Plot it
```{r}
library(ggplot2)
wins %>% ggplot(aes(half_percent, win_percent)) + 
  geom_point(color = "blue") + 
  theme_bw() + 
  labs(
    title = "Win Percentage vs. Half Percentage",
    x = "Half Percentage",
    y = "Win Percentage"
  ) 
```

## Does mid season record predict rank? 

### Linear Regression Model

```{r}
model2 <- lm(rank ~ half_percent, data = wins)
summary(model2)
```

### Plot it

```{r}
# Plot rank based on half season win percent
wins %>% ggplot(aes(half_percent, rank)) + 
  geom_point(color = "blue") + 
  theme_bw() + 
  labs(
    title = "Rank vs. Half Percentage",
    x = "Half Percentage",
    y = "Rank"
  ) +
  scale_y_reverse() 
```

```{r}
# Separate plot for each season -> do they all look linear? 
wins %>% ggplot(aes(half_percent, rank)) + 
  geom_point(color = "blue") + 
  theme_bw() + 
  labs(
    title = "Rank vs. Half Percentage",
    x = "Half Percentage",
    y = "Rank"
  ) +
  scale_y_reverse() + 
  facet_wrap(~ season)
```

# Does rank predict whether a team makes playoffs? 

## Logistic Regression Model

```{r}
model3 <- glm(playoffs ~ rank, data = wins, family = binomial)
summary(model3)
```

## How could we plot it? 

```{r}
wins %>% ggplot(aes(rank, playoffs)) +
  geom_boxplot() +
  labs(
    title = "Logistic Regression: Making Playoffs",
    x = "Rank",
    y = "Playoffs Or Not"
  ) +
  theme_bw() 
```

# Predict record from defensive / offensive summary scores? 

