---
title: "opl_simple"
---

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stats)
library(tidyverse)
```

```{r}
opl_female <- read_csv("powerlifting/Regression Module/opl_female.csv")
```

```{r}
ggplotRegression <- function (fit) {

require(ggplot2)
require(ggthemes)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(caption = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " S =",signif(fit$coef[[2]], 5)),
       title = "Fitted Line Plot",
       subtitle = "BenchKg = 8.866 + 0.474 SquatKg") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5))
}
```

```{r}
ggplotRegression(lm(BenchKg ~ SquatKg, data = opl_female))
```

```{r}
distinct(opl_female)
```
















