---
title: "Exploring Data Manipulation for Analysis"
author:
  - name: Faith Rhinehart
    affiliation:
      - ref: slu
date: "June 23, 2025"
description: "Using R Functions for Data Manipulation"
editor: 
  canonical: true
categories:
  - Data Manipulating 
  - Creating Scatterplots and Labeling Points
---

### Background to Soccer Video

If you are unfamiliar with Soccer, please watch this video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/nT5qyrxoqsA?si=j5plkuc3Lx_-Ive6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Introduction to Module

Soccer, also known as football in many parts of the world, is a globally popular sport. Two teams of eleven players (4 defenders, 4 midfielders, 2 forwards, and 1 goalkeeper) compete to score goals by maneuvering a ball into the opposing team’s net using any part of the body except their hands and arms (goalkeepers are the exception). The game emphasizes a blend of physical endurance, technical skill, and strategic teamwork. Games are 90 minutes long, divided into two 45-minute halves, with extra time and penalty shootouts used if necessary to determine a winner. Players are evaluated not only on goals and assists but also on their passing accuracy, defensive contributions, and overall impact on the game. Referees use yellow and red cards to manage player behavior and maintain fairness on the field. A yellow card serves as a warning for actions such as reckless tackles, delaying the game, or showing dissent toward the referee. If a player receives two yellow cards in one match, it results in a red card, meaning the player is ejected from the game. A red card can also be given directly for more serious offenses like violent conduct, serious foul play, or using offensive language. When a player is shown a red card, their team must continue the match with one fewer player.

The two dataseta in this module features data from male players and female players on the U.S National Team in 2024. Variables include numerical characteristics of the player such as goals, assists, Minutes playes, games played etc. Year. All of the variables are relevant for this module.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
Learning Objectives:

1. Students will learn data manipulation for analysis

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
For this activity, students will need to use R Studio. 

Students are expected to understand the basic data manipulation strategies used in R. Students are also expected to now how to code basic ggplots, and how to use dplyr functions in R Studio.

This activity would be suitable for an in-class activity or as an out-of-class assignment taking approximately one class period.
:::



### Data

The mensSoccer2024 and womensSoccer2024 data contains player's stats on the U.S. National team in 2024.

Download Men's Data: [mensSoccer2024.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Soccer/mensSoccer2024.csv)

Download Women's Data: [womensSoccer2024.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Soccer/womensSoccer2024.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

Men's data:

| Variable       | Description                                                    |
|----------------|----------------------------------------------------------------|                                      
| ..1            | Observation Number                                             |          
| Player         | Name of Player                                                 |
| Pos            | Player's Position                                              |
| GP             | Games Played                                                   |
| GS             | Games Where Player Started                                     |
| MIN            | Game Minutes Played                                            |
| G              | Goals Scored                                                   |
| A              | Assists                                                        |
| G+A            | Goals plus Assists                                             |
| YC             | Number of Yellow Cards Received                                |
| RC             | Number of Red Cards Received                                   |
| MOTM           | Number of Times Player was Recognized as "Man of the Match"    |
| Career Caps    | Number of International Games Played Representing National Team|
| Career Goals   | Career Goals                                                   |
| Career Assist  | Career Assists                                                 |
| Career G+A     | Career Goals plus Career Assists                               |
| OWN GOAL       | Number of own goals scored                                     |
| TOTALS         | Totals for each variable                                       |
| OPPONENT TOTALS| summary the opponent teams’ stats across games                 |

Women's data:

| Variable      | Description                                                    |
|---------------|----------------------------------------------------------------|  
| ..1           | Observation Number                                             |
| Name          | Name of Player                                                 |
| Pos.          | Player's Position                                              |
| GP            | Games Played                                                   |
| GS            | Games Where Player Started                                     |
| MIN           | Game Minutes Played                                            |
| G             | Goals Scored                                                   |
| A             | Assists                                                        |
| Y             | Number of Yellow Cards Received                                |
| R             | Number of Red Cards Received                                   |
| Career Caps   | Number of International Games Played Representing National Team|
| Goals         | Career Goals                                                   |
| Own Goal      | Number of own goals scored                                     |
| TOTAL         | Totals for each variable                                       |
| Opponents     | summary the opponent teams’ stats across games                 |  

</details>


### Materials

[Class handout](soccer_Worksheet.qmd)

[Class handout - with solutions](soccer_Solutions.qmd)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should gain an understanding of how the process of data manipulation works and the different strategies used to achieve a certain dataset. 
:::
