---
title: "soccer_Worksheet"
Authors: Faith Rhinehart
execute: 
  echo: true
  warning: false
  error: true
format: 
  html:
    embed-resources: true
---

Soccer, also known as football in many parts of the world, is a globally popular sport. Two teams of eleven players (4 defenders, 4 midfielders, 2 forwards, and 1 goalkeeper) compete to score goals by maneuvering a ball into the opposing team’s net using any part of the body except their hands and arms (goalkeepers are the exception). The game emphasizes a blend of physical endurance, technical skill, and strategic teamwork. Games are 90 minutes long, divided into two 45-minute halves, with extra time and penalty shootouts used if necessary to determine a winner. Players are evaluated not only on goals and assists but also on their passing accuracy, defensive contributions, and overall impact on the game. Referees use yellow and red cards to manage player behavior and maintain fairness on the field. A yellow card serves as a warning for actions such as reckless tackles, delaying the game, or showing dissent toward the referee. If a player receives two yellow cards in one match, it results in a red card, meaning the player is ejected from the game. A red card can also be given directly for more serious offenses like violent conduct, serious foul play, or using offensive language. When a player is shown a red card, their team must continue the match with one fewer player.

The U.S. Men's National Soccer Team (USMNT) was officially established in 1913 while the U.S. Women's National Team (USWNT) was established in 1985. Players are selected for the U.S. national soccer teams through a combination of scouting, performance, and coaching decisions. For major tournaments like the World Cup or Olympics, coaches must select a limited number of players—usually around 23—who offer the best balance of skill, experience, and team dynamics. Veteran players must also go through the same process but do have a higher advantage then a new player.

Loading necessary packages:
```{r}
library(readr)
library(dplyr)
library(ggplot2)
```

Reading in the Women's data set:


Reading in the Men's data set


Notice in both data sets the variable names are being treated as values instead of the column names. 

1) Fix the `womenSoccer` and the `menSoccer` data set so that the first row is the variable names.



2) Combine the men and women's data set into one data set. 



a - What looks wrong in the new data set?

 

b - Why do you think the data set doesn't look right?



3) Change the variable names of the women's data set to match the men's and get rid of any variables in the men's that don't appear in the women's data set. 



Before we recombine the data sets, it would be helpful to know if the player is male or female and to exclude data not assigned to a player. 

4) Add a new variable to both individual data sets that says "Male" or "Female' for gender of player. 



5) Slice the Men's data set to exclude `OWN GOAL`, `TOTALS`, and `OPPONENT TOTALS` and slice the Women's data set to exclude `Own Goal`, `TOTAL`, and `Opponent`.



6) Combine the the updated data sets.



7) Change the variables to a numeric class except for `Sex` and `Pos` (change those to factor)



8) Create a scatterplot that uses `MIN` to predict `Career Goals` colored by `Sex`. Add a smoother for both genders and appropriate labels to the graph.



9) Manipulate the dataset to get the highest scoring player for each gender.



10) Recreate the graph made in question 8 but add the player's name from question 9 to their respective point on the graph.


