---
title: Powerlifting Statistics
author: Sarah Weaver
date: June 21, 2023
description: Data on powerlifting competitors spanning many years.
categories:
  - simple regression
  - multiple regression
  - correlation
  - scatterplots
editor: 
  markdown: 
    wrap: 72
---

## Motivation

Powerlifting consists of three types of lifts (squats,bench press and
deadlift) where the competitors get three attempts at maximal weight on
those three lifts. These lifts can either be done 'classic' or 'raw'
which refers to if competitors complete lifts equipped or un-equipped.
Things like supportive shirts, briefs, suits, and sometimes knee wraps
are seen as equipment. Competitions are held all around the world and
competitors are divided by weight classes and age.

## Data

The original dataset was found at https://www.openpowerlifting.org/ with
over 3 million rows with the filter of 'raw' tournaments. The website
allows you to specify certain criteria for rows.

This data set has 295,877 rows with 7 columns. Each row represents a
power lifting competitor and their respective personal information.

| Variable     | Description                                              |
|--------------|----------------------------------------------------------|
| Name         | The competitor's name                                    |
| Sex          | The competitor's sex                                     |
| Age          | The competitor's age                                     |
| BodyweightKg | The competitor's body weight in kilograms                |
| BenchKg      | The total weight a competitor can bench in kilograms     |
| SquatKg      | The total weight a competitor can squat in kilograms     |
| DeadliftKg   | The total weight a competitor can dead lift in kilograms |

: [powerliftingregression.csv](../data/powerliftingregression.csv)

## Subsets

This subset consists of 25-year-old females and the variables listed above.

:   [opl_female.csv](../data/opl_female.csv)

```{r}
# eval: false
opl_female <- opl_class |> filter(Sex == "F") |> filter(Age == 25.0)
```

This code is an example of one of the ways to create a smaller subset of
data which could be more manageable for simple problems. Change the
filters to create different subsets that fit your statistical needs!

## Questions

Is there any correlation between lifting events within a certain age or
weight category?

Can a relationship be modeled between events weights and body weight?

Is there an event where females perform better than males?

## References

Powerlifting rankings. OpenPowerlifting. (n.d.).
<https://www.openpowerlifting.org/>
