---
title: "Wingspan & Performance in the NBA"
author:
  - name: Cooper Olney
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: "June __, 2025"
description: "___"
editor: 
  canonical: true
categories:
  -  ___
  -  ___
---

## Module
Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.


### Introduction
The National Basketball Association (NBA) is a professional basketball league featuring the best players from around the world. In the modern NBA, player evaluation has gone far beyond just points. Physical attributes like height, [wingspan](https://www.nba.com/knicks/videos/how-to-measure-your-wingspan){target="_blank"} and reach are increasingly used by teams to gain a competitive edge. These measurements not only influence how players are scouted and drafted, but also how they're expected to perform on the court. One particularly interesting metric is wingspan advantage which is the difference between a player's wingspan and their height (wingspan - height). A larger wingspan relative to height is often considered beneficial for defense, rebounding, and shot-blocking, but does this actually show up in the data?

In this worksheet, you'll explore how physical traits like wingspan advantage relate to on-court performance. You'll work with real NBA data to practice essential skills such as cleaning, tidying and joining datasets, as well as visualizing relationships. By the end, you'll use your cleaned and combined datasets to look for meaningful patterns between a player's wingspan advantage and their statistical output.




::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1. Clean and transform raw and messy data into a structured and analysis ready format.

2. Combine multiple datasets, including resolving issues like inconsistent naming.

3. Use web scraping tools to gather additional data from an online source.

4. Explore relationships between variables and communicate findings using visualizations.

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
**Technology Requirement:**

This activity requires the use of RStudio with familiarity in Quarto documents and several `tidyverse` packages including `dplyr`, `tidyr`, `readr` and `stringr`. Students will also work with the `janitor`, `rvest` and `fuzzyjoin` packages to perform webs scraping, clean raw datasets and attempt to resolve joining issues due to data inconsistencies. 

:::

### Data
The **nba_player_profiles_2025.csv** data set contains 499 rows and 4 columns. Each row represents a NBA player from the 2024-25 season. **Note** this dataset is partially cleaned from the data found at craftednba.com.

Download Data: [nba_player_profiles_2025.csv](/data_repo_submission/nba_player_profiles_2025.csv){target="_blank"}

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable          | Description
|-------------------|------------------------------------------------
| name    | Full Name of NBA player, with team abbreviation and primary position
| height    | Player's height in feet & inches format
| wingspan    | Player's wingspan in feet & inches format 
| wingspan_advantage    | Difference between wingspan and height in inches (wingspan - height)  

</details>

#### Data Source

[https://craftednba.com/player-traits/length](https://craftednba.com/player-traits/length){target="_blank"}


### Materials

[Class handout](___)

[Class handout - with solutions](___)


::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Through this module, you explored how physical attributes, specifically wingspan and wingspan advantage might relate to on-court performance in the NBA. By cleaning the combining data from multiple sources, you've created a comprehensive dataset that allowed for deeper exploration of relationships between physical characteristics and basketball statistics. 

With your final combined dataset, you were able to generate visualizations to investigate potential connections, such as whether players with longer wingspan advantages tend to have a larger defensive impact. These kinds of relationships can provide use insights for analysts, scouts and even fans trying to understand the value of certain physical traits. 

This activity underscores the value of data wrangling, merging and visualization and sets the stage for more advanced analysis in the future. Whether that's building predictive models, exploring important relationships, or applying machine learning techniques to sports data.



:::






