---
title: "Data Repo"
author: "Gavin Cassidy"
format: html
---


## Motivation





## Data

The DGPT data set contains 97 rows and 24 columns where each row is a disc golfer's statistics from the first 11 events of 2024 Disc Golf Pro Tour season. Each row includes a players average scoring, throwing, and putting statistics, as well as cumulative and average placement and earning statistics. The columns are as follows:




| Variable          | Description                                                   |
|-------------------|-----------------------------------------------------|
| player        | player name                                                   |
| birdie_avg    | the average number of birdies from an 18 hole round           |
| bogey_avg     | the average number of bogeys from an 18 hole round            |
| PKD           | the percentage of shots a player has 'parked' (within 10 ft of the basket)           |
| C1R           | the percent of shots throw within 'Circle 1'(0-33ft) in regulation  |
| C2R           | the percent of shots throw within 'Circle 2'(33-66ft) in regulation |
| FWY           | the percent fairways hit with drives                                |
| SCR           | the percent of successful 'scrambles' (when a player makes par or better from a drive off the fairway)    |
| OB/18         | the average total out of bounds shots for 18 holes            |
| C1X           | the percent of putts made from C1 excluding tap in putts(0-10ft)  |
| C2P           | the percent of putts made from C2 (33-66ft)                   |
| tot_SG:TG     | the total 'Strokes Gained' on the rest of the field from the tee to the green from the whole DGPT season |
| tot_SG:P      | the total 'Strokes Gained' on the rest of the field putting for the DGPT season     |
| C1R           | the percent of shots throw to 'Circle 1' in regulation        |
| events        | total events played for the 2024 DGPT season                       |
| rounds        | total rounds played for the 2024 DGPT season                       |
| wins          | wins from the 2024 DGPT season                                     |
| podiums       | total podium placements from the 2024 DGPT season                  |
| top_10s       | total top 10 placements from the 2024 DGPT season                  |
| top_20s       | total top 20 placements from the 2024 DGPT season                  |
| avg_place     | average placement from the 2024 DGPT season                       |

















