---
title: "fifa_exploration"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
library(stringr)
```

```{r}
fifa <- read_csv("esselt21/fifa_module/exporation/fifa.csv")
```

```{r}
fifaAtt <-
  fifa |>
  mutate(ST = if_else(str_detect(player_positions, "ST"), 1, 0),
         CF = if_else(str_detect(player_positions, "CF"), 1, 0),
         RW = if_else(str_detect(player_positions, "RW"), 1, 0),
         LW = if_else(str_detect(player_positions, "LW"), 1, 0),
         RM = if_else(str_detect(player_positions, "RM"), 1, 0),
         LM = if_else(str_detect(player_positions, "LM"), 1, 0),
         CAM = if_else(str_detect(player_positions, "CAM"), 1, 0),
         CM = if_else(str_detect(player_positions, "CM "), 1, 0),
         CDM = if_else(str_detect(player_positions, "CDM"), 1, 0),
         LWB = if_else(str_detect(player_positions, "LWB"), 1, 0),
         RWB = if_else(str_detect(player_positions, "RWB"), 1, 0),
         LB = if_else(str_detect(player_positions, "LB"), 1, 0),
         RB = if_else(str_detect(player_positions, "RB"), 1, 0),
         CB = if_else(str_detect(player_positions, "CB"), 1, 0),
         GK = if_else(str_detect(player_positions, "GK"), 1, 0)
         )
```


```{r}
fifaTry <-
  fifa |>
  separate(player_positions,
           into = c("Position1", "Position2"),
           sep = ",")

fifaTry <-
  fifaTry |>
    separate(Position2,
           into = c("Position2", "Position3"),
           sep = ",")

fifaTry |>
  pull(Position1)
```

