---
title: "fencing_exploration"
format: html
---

# Libraries

```{r}
library(tidyverse)
library(readr)
library(broom)
```

# Data

```{r}
fencing_df <- read_csv("~/Desktop/git/score_new/awsmit22/fencing_module/exploration/fencing.csv")
fencing_df
```

# Grouping Exploration

```{r}
# Schools
fencing_df |> group_by(School) |> summarise(n=n())
```

```{r}
# Weapons
fencing_df |> group_by(Weapon) |> summarise(n=n())
```

```{r}
# Gender
fencing_df |> group_by(Gender) |> summarise(n=n())
```

```{r}
# Schools
fencing_df |> group_by(School) |> summarise(avg_ind = mean(Ind))
```

```{r}
# Ivies
fencing_df |> group_by(Ivy) |> summarise(n=n())
```

```{r}
# Ivies
fencing_df |> group_by(Ivy) |> summarise(avg_ind = mean(Ind))
```

```{r}
# Ivies
fencing_df |> group_by(Ivy) |> summarise(avg_pct = mean(Pct))
```

```{r}
# Schools
fencing_df |> group_by(School) |> summarise(avg_pct = mean(Pct))
```

# Graphical Explorations

```{r}
ggplot(data = fencing_df, aes(x = Gender, y = Ind)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = Weapon, y = Ind)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = Ivy, y = Ind)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = Gender, y = Pct)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = Weapon, y = Pct)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = Ivy, y = Pct)) + geom_boxplot()
```

```{r}
ggplot(data = fencing_df, aes(x = TS, y = TR)) + geom_point()
```

```{r}
ggplot(data = fencing_df, aes(x = Victories)) + geom_histogram(bins = 10, colour = "black", fill = "lightblue") + facet_grid( Gender ~ Weapon) + theme_minimal() + theme(axis.text = element_text(size = 12), strip.text = element_text(size = 12)) + labs(title = "Histograms of Victories for Each Weapon and Both Genders")
```

```{r}
barplot <- fencing_df |> group_by(School) |> summarise(Victories = sum(Victories)) |> mutate(School = fct_reorder(School, Victories))
ggplot(data = barplot, aes(x = School, y = Victories)) + geom_col() + coord_flip()
```

```{r}
ggplot(data = fencing_df, aes(x = Ivy, y = Victories)) + geom_col()
```

```{r}
ggplot(data = fencing_df, aes(x = Ivy, y = Pct)) + geom_col()
```

# Modelling

```{r}
# Full mod
full_mod <- lm(Place ~ Victories + Bouts + Pct + TS + TR + Ind + Gender + Weapon + Ivy, data = fencing_df)
full_mod |> tidy()
```

```{r}
# Indicator to predict place
ind_mod <- lm(Place ~ Ind, data = fencing_df)
ind_mod |> tidy()
```

```{r}
# Indicator to predict pct
pct_mod <- lm(Pct ~ Ind, data = fencing_df)
pct_mod |> tidy()
```

```{r}
# Bigger mod with categorical predictors
bi_mod <- lm(Pct ~ Gender + Weapon + Ivy, data = fencing_df)
bi_mod |> tidy()
```



