---
title: "2024 NCAA Fencing National Championship Results"
author:
  - name: Abigail Smith
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: July 3, 2024
description: Analyzing various statistics from the results of the 2024 NCAA Fencing National Championships for both genders and all weapons. 
categories:
  -  Normal Distribution
  -  Boxplots
  -  Summary Statistics
  -  Outlier Detection
  -  Least Squares Line
  -  Residuals
  -  R-Squared
---

### Welcome video

{{< video  title="2024 NCAA Fencing National Championship Results" >}}

### Introduction

This activity examines the `Victories` and `Indicator` variables for fencers at the [2024 NCAA Fencing National Championship](https://en.wikipedia.org/wiki/NCAA_Fencing_Championships){target="_blank"}. 

[Fencing](https://en.wikipedia.org/wiki/Fencing){target="_blank"} is a semi-contact sport that is based on sword fighting and dates back to the 1600s. There are three weapon types in fencing, epee, foil, and sabre. Fencing consists of bouts in which two fencers face-off against each other on a strip (14 x 1.5 meters). During bouts fencers attempt to hit each other with their weapon within the valid target area. Target areas vary for each weapon type. For epee, the entire body is a target area, for foil only the torso is a valid target area, and for sabre the target area is from the hips to the head. Bouts last 9 minutes total and are broken into three 3-minute phrases with a minute break in between. A bout is won by the first fencer to reach 15 touches, if the bout ends before either fencer has 15 touches, the fencer with the most touches is
declared winner.

At the [collegiate level](https://en.wikipedia.org/wiki/Collegiate_fencing){target="_blank"}
the fencing season comes to a close with the [NCAA Fencing Championships](https://en.wikipedia.org/wiki/NCAA_Fencing_Championships){target="_blank"} which is hosted at a different school every year. The championship is non-divisional and consists of the top fencers from schools in each NCAA region (Northeast, Mid-Atlantic/South, Midwest, and West). Fencers qualify for nationals based on their performance at regionals. Schools are allowed up to 12 fencers total in the tournament, but are only allowed a maximum of two fencers in each weapon and gender. The final championship consists of a 24 fencer round-robin in which each fencer in the discipline faces each other in 5-touch bouts. Fencers are ranked based on descending indicator scores which is the difference in touches sent and touches received. The top 4 fencers from each discipline face each other off in a round of 15-touch semifinals and championship bouts. The fencer to win the championship places number 1 in the discipline. Each school is awarded a point for each victory from each of their fencers. Schools' points are added and ranked, and the school with the most points at the end of the tournament wins.

This [fencing dataset](fencing.csv){target="_blank"}(fencing.csv) contains the final results for each individual fencer in the 2024 NCAA Fencing Championships hosted at Ohio State University. It has data for both men and women in all three weapon types. The indicator variable in particular highlights the performance of fencers in the tournament and is often used in fencing in general to rank fencers. Since it is a calculation of a fencer's touches sent minus the touches they received, it is a good measure of offensive strength. Investigating this variable in conjuncture with the number of victories per fencer in the tournament can assess the performance of fencers in the data set.

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity could be used as a quiz, an in class or take home assignment. 
:::



::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, students will be able to:

1.  Assess a variable's distribution
2.  Create a boxplot and identify outliers using summary statistics
3.  Interpret a least squares line
4.  Evaluate the R-Squared value of a model
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Students will use a basic understanding of histograms to evaluate a variable's distribution and to determine if that distribution is normal. Students will also use summary statistics to find outliers and draw boxplots. Students will assess the relationship between variables through looking at scatterplots and least squares lines. Students can evaluate the strength of this relationship through interpreting R-Squared. 
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
This worksheet will not require the use of any technology.
:::

### Data

The data set has 144 rows with 13 variables. Each row is a fencer who participated in the 2024 NCAA Fencing Championships. The statistics in each row are the fencers' totals from the tournament.

Download data: 

: [fencing.csv](fencing.csv){target="_blank"}

<details>
<summary><b>Variable Descriptions</b></summary>

| Variable   | Description                                                                                                             |
|-----------------------|------------------------------------------------|
| `Place` | The place the fencer finished the tournament in. |
| `Tied` | If the fencer was tied for their place with someone else, `TRUE` or `FALSE`. |
| `Name` | The fencer's name in `first name last name` order. |
| `School` | The school the fencer is representing. |
| `Victories`   | The total victories the fencer had in the tournament. |
| `Bouts`  | The number of bouts the fencer was in in the tournament. |
| `Pct` | The percentage of wins (`Victories`/`Bouts`) the fencer had in the tournament. |
| `TS`  | The total touches sent by the fencer in the tournament, meaning touches they scored against opponents. |
| `TR` | The total touches received by the fencer in the tournament, meaning touches scored against the fencer. |
| `Ind` | The indicator score, calculated by `TS`-`TR`. |
| `Gender` | The fencer's gender, `Women` or `Men`. |
| `Ivy` | If the fencer's school is in the Ivy League, `Ivy` or `Non-Ivy`. |


**Data Source**

[Website the Data was Scraped From](https://ncaa.escrimeresults.com/ncaa2024.html){target="_blank"}=

**More information on the rules and set up**

[Olympic Fencing Rules](https://www.nbcolympics.com/news/fencing-101-rules-and-scoring){target="_blank"}

[NCAA Fencing Website](https://www.ncaa.com/sports/fencing){target="_blank"}

[NCAA Fencing Championships Wikipedia](https://en.wikipedia.org/wiki/NCAA_Fencing_Championships){target="_blank"}

[NCAA Fencing Wikipedia](https://en.wikipedia.org/wiki/Collegiate_fencing){target="_blank"}

[Fencing Wikipedia](https://en.wikipedia.org/wiki/Fencing){target="_blank"}

</details>

### Materials

We provide editable MS Word handouts along with their solutions.

[Worksheet](fencing_worksheet.docx)

[Worksheet Answers](fencing_worksheet_KEY.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
After finishing this activity, students should be able to identify if a variable is normally distributed or not. Using the 5-number summary, students will identify outliers and create boxplots. Students will also interpret the slope and r-squared value of a least-squares line and calculate residuals. 
:::
