---
title: "Predicting Total Points and Free Skate Score"
author:
  - name: Faith Rhinehart
    affiliation:
      - ref: slu
date: "June 17, 2025"
description: "Model Building on the US Olympic Figure Skaters"
editor: 
  canonical: true
format: 
  html:
    embed-resources: true
categories:
  - Model Building
  - Log Transformations
---

### Background to Figure Skating Video

If you are unfamiliar with Figure Skating Scoring, please watch this video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/i6pw07k3GkM?si=ud_nUmub-iDQ_cAm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Introduction to Module

Figure skating is a sport where people perform routines on ice to music, combining athletic skill with artistic expression. Skaters compete in different categories like men's singles, women's singles, pairs (a man and a woman skating together), and ice dance (which focuses more on rhythm and movement). Each skater or team performs two routines: the short program and the free skate. The short program is a shorter routine with a list of required moves that every skater must include. Judges look at how well each move is done and how smoothly everything fits with the music. The free skate is longer and gives skaters more freedom to show their personal style and creativity. They still need to include certain types of moves, but they can choose how to put them together. Judges give scores for both routines based on how difficult the moves are, how well they’re done, and how artistic the performance is. The scores from both routines are added together, and the skater or team with the highest total wins.

The MensFigureSkating dataset features data from male skaters in the winter Olympics since 2006. Variables include characteristics such as Name, Nation, Year. Other variables included the 3 types of scoring: Free Skate, Short Program, and Total Points. The relevant variables for this specific module are Total Points and Year.   

For the sake of this module, the data set was tidied so that it excluded any skater who did not advance to the Free Skate round.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
Learning Objectives:

1. Students will gain a further understanding log transformations and model building

2. Students will practice their skills of interpreting a model 

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
For this activity, students will need to use a statistical software such as R. 

Students are expected to understand the concept of model building, model assumptions, and model transformations. Knowing how to code these things will be helpful in completing this assignment.

This activity would be suitable for an in-class activity or as an out-of-class assignment taking approximately one class period.
:::



### Data

The MensFigureSkating data contains scores from skaters in the Winter Olympics since 2006. 

Download data: [MensFigureSkating.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Olympic Figure Skating/logTransformation/Module/MensFigureSkating.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable | Description                   |                           
|----------|-------------------------------|
|Rank      | Rank of the Skater            |
|Name      | Name of the skater            |
|Nation    | Country Skater's representing |
|TP        | Total points scored (SP + FS) |
|SP        | Short Program score           |
|FS        | Free Skate Score              |
|Year      | Year of Olympics              |   

</details>


### Materials

R qmd file:

[Class handout](Figure_Skating_Worksheet.qmd)

[Class handout - with solutions](Figure_Skating_Solutions.qmd)

Word Document:

[Class handout](Figure_Skating_Worksheet.docx)

[Class handout - with solutions](Figure_Skating_Solutions.docx)

pdf Document:

[Class handout](Figure_Skating_Worksheet.pdf)

[Class handout - with solutions](Figure_Skating_Solutions.pdf)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should gain an understanding of model building, interpreting coefficients, and the process of log transformations.
:::
