---
 title: "Tour de France Doping Eras"
author:
  - name: Gavin Cassidy
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: 
    email: 
    affiliation:
      - ref: slu
date: July 15, 2024
description: Compare different statistics from the Tour de France across the different eras of doping in the Tour
categories:
  - Side-by-Side Boxplots
  - ANOVA for Difference in Means
---

## Module

### Introduction

The Tour de France is a 21 stage cycling race that takes place around the hills and mountains of France every summer. Cyclists cover around 4000 kilometers over the duration of the race and can climb over 50,000 meters through the mountains. Riders come to the tour with one of a few goals, win a stage, win the Sprint or King of the Mountains jersey, win the General Classification, or support their team mates in achieving their goal. For most riders, winning a stage at the Tour is a career accomplishment, while some riders win several in a tour. Mark Cavendish holds the record for stage wins with 35 over the course of his career, all of them coming from sprints. A prestigious as winning a stage is, the General Classification(GC) is the ultimate prize of the Tour. The General Classification is the overall classification where placing is determined by overall time. The leader in the GC wears the Yellow Jersey or Maillot Jaune, and teams compete fiercely for their leader to wear yellow. 

The real battle in the General Classification happens mainly between the top riders on 2 types of stages, individual time trials and mountains stages. These types of stages generally have larger time gains or losses than flat stages as working with teammates is less beneficial or not allowed. Individual time trials are short stages where riders are alone and try to ride to get their best possible time. Time gaps are easier to open on time trials as there are no team mates to assist riders and no references to rivals. The most time gains come on the steep mountain stages, generally taking place in the Alps or Pyrenees. The mountain stages are where the GC contenders separate themselves, as minutes can be gained or lost on the steep climbs. The tour is often decided by which rider can drop their opponents up the steep climbs and hold them off for the duration of the tour. Modern day tours are often decided by less than 5 minutes, while early tours were won by hours. The closest finish ever was a 8 second victory where American Greg LeMond edged out Frenchman Laurent Fignon on the final stage, winning a time trial by 58 seconds to close a 50 second gap.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
The learning objectives associated with this module are:

-   Defining the null and alternative hypothesis for a multi-way ANOVA

-   Reading boxplots to determine is means display variance or not

-   Reading a pairwise t test and understand the output
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
-   The handout provides a plots and output for an ANOVA test and pairwise t test
:::


### Data

This data was found on [kaggle](https://www.kaggle.com/datasets/pablomonleon/tour-de-france-historic-stages-data)

The tdf_stages data set contains information from each stage of the Tour de France from 1903 to 2017. There are 8 columns and 2236 rows, with each row being a unique stage in the Tour. The columns are listed below.

[tdf_stages.csv](tdf_stages.csv)

| Variable       | Description                                                       |
|------------------------|------------------------------------------------|
| Stage          | the number of the stage in the particular edition                 |
| Date           | the date the stage took place (yyyy-mm-dd)                        |
| Distance       | the distance of the stage in kilometers                           |
| Origin         | the town where the stage began                                    |
| Destination    | the town where the stage ended                                    |
| Type           | the type of riding that the stage entailed(flat, mountain, hilly) |
| Winner         | the name of the stage winner                                      |
| Winner_Country | the country where the stage winner is a citizen                   |

The tdf_winners data set contains information about the winner of each edition of the Tour de France from 1903 to 2019. There are 21 columns and 106 rows that contain information about each winner. Each row is 1 edition of the Tour. The columns are listed below

[tdf_winners.csv](tdf_winners.csv)

| Variable       | Description                                                          |
|------------------------|------------------------------------------------|
| edition        | how many Tour de France's had taken place                            |
| start_date     | the date the tour began (yyyy-mm-dd)                                 |
| winner_name    | the name of the winner                                               |
| winner_team    | the name of the team of the winner                                   |
| distance       | the total distance of the specific edition of the tour               |
| time_overall   | the overall time of the race winner in hours                         |
| avg_speed      | the average speed of the winner in kilometers per hour               |
| time_margin    | the margin of victory of the winner in hours                         |
| seconds_margin | the margin of victory of the winner in seconds                       |
| stage_wins     | the number of stage wins of the winner of the tour                   |
| stages_led     | the number of stages where the winner led the General Classification |
| height         | the height of the winner of the tour in meters                       |
| weight         | the weight of the winner of the tour in kilograms                    |
| age            | the age of the winner of the tour when they won                      |
| born           | the birth date of the winner (yyyy-mm-dd)                            |
| died           | the date of death of the winner(if applicable)                       |
| full_name      | the full name of the winner(if not used for winner name)             |
| nickname       | the nickname of the winner(if applicable)                            |
| birth_town     | the town where the winner was born                                   |
| birth_country  | the country where the winner was born                                |
| nationality    | the nationality of the winner                                        |


### Materials

[tdf_stages.csv](tdf_stages.csv) - Data set containing data on each stage of the Tour de France

[tdf_winners.csv](tdf_winners.csv) - Data set containing the winner of each Tour de France and associated statistics

[tdf_worksheet.docx](tdf_worksheet.docx) - Worksheet containing ANOVA and Pairwise t Test questions

[tdf_worksheet_ans.docx](tdf_worksheet_ans.docx) - Answer Sheet

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should find that there is differences between the eras of the Tour
:::
