---
title: "Dakar Rally analysis"
author: "Matt Maslow"
format: html
---





```{r}
library(tidyverse)
```



```{r}
dakarRally_bikes_data <- read_csv("Dakar Rally/data/dakarRally_bikes_data.csv")
```


# Question 1

```{r}
dakarRally_bikes_data %>%
  filter( Stage == 6) %>%
  select(Rank, Hours, Variation_Hours, Penalty_Hours, Penalty_Minutes) %>%
  lm(Rank ~ ., data = .) %>%
  summary()

dakarRally_bikes_data %>%
  filter( Stage == 6) %>%
  select(Rank, Hours, Variation_Hours, Penalty_Hours, Penalty_Minutes) %>%
  lm(Rank ~ ., data = .) %>%
  anova()
```

## a.

```{r}
# R2 = 1 - SSE / SST
SSE = 33737
SST = (35395+50998+22590+8590+33737)

(R2 = 1 - (SSE / SST))
```

## b.

on answer key



# Question 2

```{r}
dakarRally_bikes_data <- 
  dakarRally_bikes_data %>% 
  mutate(topFive = ifelse(Rank <= 5, 1, 0))
```

```{r}
modFull <- glm(topFive ~ Hours + Variation_Hours + Penalty_Hours + Penalty_Minutes + Stage,
               data = dakarRally_bikes_data, family = binomial)
summary(modFull)
```


```{r}
modRed <- glm(topFive ~  Hours + Variation_Hours +  Penalty_Hours + Stage,
              data = dakarRally_bikes_data, family = binomial)
summary(modRed)
```
```{r}
anova(modRed, modFull, test = "Chisq")
```



# Quesrtion 3 

```{r}
dakarRally_bikes_data %>%
  group_by(Country, Driver) %>%
  summarise(count = n(),
            average_Rank = mean(Rank),
            Mean_Hours_Driven = ((mean(Hours)*60 + mean(Minutes) + (mean(Seconds)/60)) / 60),
            Mean_Hours_Penalty = (mean(Penalty_Hours)*60 + mean(Penalty_Minutes) + (mean(Penalty_Seconds)/60)) / 60,
            Mean_Hours_Variation = (mean(Variation_Hours)*60 + mean(Variation_Minutes) + (mean(Variation_Seconds)/60)) / 60) %>%
  filter((count > 1)) %>%
  arrange(average_Rank) %>%
  head()
```



# viz
```{r}
dakarRally_bikes_data %>%
  group_by(Country, Driver) %>%
  summarise(count = n(),
            average_Rank = mean(Rank),
            Mean_Hours_Driven = ((mean(Hours)*60 + mean(Minutes) + (mean(Seconds)/60)) / 60),
            Mean_Hours_Penalty = (mean(Penalty_Hours)*60 + mean(Penalty_Minutes) + (mean(Penalty_Seconds)/60)) / 60,
            Mean_Hours_Variation = (mean(Variation_Hours)*60 + mean(Variation_Minutes) + (mean(Variation_Seconds)/60)) / 60) %>%
  filter((count == 13)) %>%
  arrange(desc(Mean_Hours_Driven))
```

```{r}
dakarRally_bikes_data %>%
  group_by(Team) %>%
  summarise(count = n(),
            average_Rank = mean(Rank),
            Mean_Hours_Driven = ((mean(Hours)*60 + mean(Minutes) + (mean(Seconds)/60)) / 60),
            Mean_Hours_Penalty = (mean(Penalty_Hours)*60 + mean(Penalty_Minutes) + (mean(Penalty_Seconds)/60)) / 60,
            Mean_Hours_Variation = (mean(Variation_Hours)*60 + mean(Variation_Minutes) + (mean(Variation_Seconds)/60)) / 60) %>%
  filter((count %% 13 == 0) & (count > 0)) %>%
  arrange(average_Rank) %>% 
  head() %>%
  ggplot(aes(x = reorder(Team, average_Rank), y = average_Rank)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Top Teams by Average Rank",
       x = "Team",
       y = "Average Rank") +
  # add their means hours driven as text
  geom_text(aes(label = round(Mean_Hours_Driven+Mean_Hours_Penalty, 2)), hjust = -0.1) +
  theme_minimal() +
  theme(axis.title = element_text(size = 14),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10)) +
  scale_color_viridis_d()
```

```{r}
dakarRally_bikes_data %>%
  group_by(Driver) %>%
  summarise(avg_rank = Rank,
            stage = Stage,
            stage_count = n(),
            Hours_Driven = (((Hours)*60 + (Minutes) + ((Seconds)/60)) / 60),
            Hours_Penalty = ((Penalty_Hours)*60 + (Penalty_Minutes) + ((Penalty_Seconds)/60)) / 60) %>%
  filter(stage_count == 13 & stage == 12 & !between(avg_rank, 87, 103)) %>% # drivers skew result as they could have be disqualified
  arrange(Hours_Driven + Hours_Penalty) %>%
  head(5)
```
Final 5 drivers in the Dakar Rally

RICKY BRABEC, ROSS BRANCH, ADRIEN VAN BEVEREN, KEVIN BENAVIDES, TOBY PRICE

```{r}
dakarRally_bikes_data %>%
  group_by(Driver) %>%
  summarise(avg_rank = Rank,
            stage = Stage,
            stage_count = n(),
            Hours_Driven = (((Hours)*60 + (Minutes) + ((Seconds)/60)) / 60),
            Hours_Penalty = ((Penalty_Hours)*60 + (Penalty_Minutes) + ((Penalty_Seconds)/60)) / 60) %>%
  filter(Driver %in% c("RICKY BRABEC", "ROSS BRANCH", "ADRIEN VAN BEVEREN", "KEVIN BENAVIDES", "TOBY PRICE")) %>%
  ggplot(aes(x = reorder(Driver, Hours_Driven + Hours_Penalty), y = avg_rank, fill = Driver)) +
  geom_boxplot() +
  geom_point() +
  labs(title = "Hours Driven by the Final 5 Drivers",
       x = "Driver",
       y = "Hours Driven") +
  theme_minimal() +
  coord_flip() +
  theme(plot.title = element_text(size = 14),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10)) +
  theme(legend.position = "none")
```




