---
title: Handball Individual Player Statistics for the 2022-2023 Season
author: Abigail Smith
date: June 7, 2024
description: A variety of statistics for individual players in the Handball-Bundesliga for the 2022-23 season.
categories:
  - confidence intervals
  - prediction intervals
  - multiple linear regression
  - anova for overall fit
  - t.test for correlation
  
editor: 
  markdown: 
    wrap: 72
---
## Motivation

Handball is a popular sport in many European countries such as Germany where it is said to have originated. The Bundesliga, for example, is a German professional handball league. Handball is typically played indoors on a rectangular court (20m x 40m). There are two goals (3m x 2m) on opposite sides of the court, the goal for each team is to score a goal by getting the ball in the other team's goal. The challenge to this is that there is a semicircle with a radius of 6m surrounding the goal which players other than the goal keeper are not allowed in, making it challenging to score. Players run back and forth down the court passing the ball to each other and trying to score. There are seven positions total in handball: the goalkeeper who defends the team's goal, left and rights backs are positioned on the left and right side of their half of the court to provide further defense, the center can move up and down the court and is usually the one trying to score, left and right wings cna also move up and down the court, serving as offense when the team pushes for attack and defense when the opposing team tries to score, lastly, the pivot is considered strictly an offensive player as they are usually position in the opposing side of the court, they often work closely with the center. 

Handball is considered a contact sport which means aggressive strategies are often used in games. This data set could provide insight on if players or teams that are more aggressive are more successful than those who are more passive. Aggressiveness can be measured in the penalty statistics as players who tend to get more penalties are usually more considered more aggressive players overall. Their success can be measured both in offensive statistics as well as the handball performance index.  

## Data

The dataset has 372 players from 18 different clubs, with 8 variables, 6 of which are statistics. Each row in the data set is a player in the Handball-Bundesliga during the 2022-23 season. The statistics are cumulative for the entirety of the season.

| Variable | Description |
|-------------------|-----------------------------------------------------|
| `CLUB` | The club the player is on. There are 18 in the Bundesliga.|
| `POSITION`| The position of the player. There are 7 positions in handball: goalkeeper, fullbacks (left and right), center backcourt, wingers (left and right), and pivot.  |
| `P` | The number of games the player was in that season. |
| `total_offense` | The total offensive plays made by the player in the season. Calculated by adding the 6 offensive focused statistics from the original dataset.|
| `total_penalties` | The total penalties the player had in the season. Calculated by adding the 5 penalty related statistics from the original dataset.|
| `percentage` | The shot percantage of the player in the season. |
| `BL` | The number of shots blocked by the player in the season. |
| `HPI` | Handball performance index, formulaic calculation equivalent to how well the player performed in the season. |

: [handball_total.csv](handball_total.csv){target="_blank"}


## Questions

1.    Calculate and interpret a 98% confidence interval for the mean HPI of a player with 30 total_penalties. Check your work with R. 

2.    Calculate and interpret a 98% prediction interval for the HPI of a player with 30 total_penalties. Check your work with R.

3.    Perform an ANOVA test to assess the overall fit of `HPI = total_offense + total_penalties`. Provide an interpretation of the results. Check your work with R.

4.    Test the significance of the correlation between the `total_offense` and the `total_penalties` of a player. Provide an interpretation of the results. Check your work with R.

## References

[Kaggle Original Dataset](https://www.kaggle.com/datasets/nemanjagojkovic/handball-bundesliga-stats-202223){target="_blank"}

[Olympic Handball Rules](https://olympics.com/en/news/handball-game-rules-regulations-how-to-play){target="_blank"}

[Handball Positions](https://www.theukrules.co.uk/rules/sport/handball/player-positions/#google_vignette){target="_blank"}