---
title: "CodeAnalysis_BullsData"
author: "Matthew Maslow"
format: html
---



```{r}
library(tidyverse)
library(broom)
```


```{r}
bulls <- read_csv("Bull Riding/Bulls.csv")
```

# 1 Variable selection techniques

```{r}
bulls %>%
  select(-Bull) %>%
  cor() %>%
  round(2)
```

```{r}
bulls <- bulls %>%
  mutate(lessThree_Buckoff = ifelse(Avg_Buckoff_Time < 3.00, 1, 0),
         betterThanAverage = ifelse(Avg_BullScore > mean(Avg_BullScore), 1, 0) )
```


```{r}
bulls %>%
glm(betterThanAverage ~ World_Champ_Avg_Score + Avg_Buckoff_Time + Highest_BullScore + fortyFivePt_Rides, data = .) %>%
  summary()
```

```{r}
mod <- glm(betterThanAverage ~ World_Champ_Avg_Score + Avg_Buckoff_Time + Highest_BullScore + fortyFivePt_Rides, data = bulls)
plot(mod, pch = 16)
```



# 2 Population hypothesis testing

```{r}
anova(mod, test = "Chisq")
```


```{r}
confint(mod)
```



```{r}
mod <- glm(`betterThanAverage` ~ World_Champ_Avg_Score + Avg_Buckoff_Time + Highest_BullScore + fortyFivePt_Rides, data = bulls)
newdata <- data.frame(World_Champ_Avg_Score = 45.5, 
                      Avg_Buckoff_Time = 3.73, 
                      Highest_BullScore = 45.5, 
                      fortyFivePt_Rides = 1)
```
```{r}
predict.glm(mod, interval = "prediction", newdata = newdata)
```

```{r}
 exp(1.001762 )/(1+exp(1.001762))
```




