---
title: "Exploring ANOVA Through the NBA Draft"
author: "Vivian Johnson" 
date: "June 17, 2024" 

categories:
  - One-Way ANOVA
  - Difference in means 
---

## Motivation

#### The NBA Draft

Each year, the National Basketball Association (NBA) holds a [draft](https://www.bbc.co.uk/newsround/65997816){target="_blank"}, where prospective basketball players are able to be chosen to join one of the 30 professional teams across the United States and Canada.

In order to be eligible for the draft, a player must be at least 19 years old and out of high school for at least one year. Prior to 2006, this rule was not in effect, and players could be drafted during/right out of high school.

The draft is comprised of 60 players and takes place over two rounds of 30 selections. Teams pick players in an order based on performance from the previous season, with teams that performed poorly getting earlier picks in order to create a seemingly more level playing field.

#### Playing Basketball

The goal in basketball is to score as many points as possible by throwing the ball through the other team's hoop. The two netted baskets, positioned on opposite ends of a rectangular court, are normally 10 feet high, and have a backboard behind them.

In the middle of [the court](https://en.wikipedia.org/wiki/Basketball_court){target="_blank"} there is a half-court line that divides the two sides. On both sides, surrounding the hoops, there is an arch called the three-point line. Within the three-point line stands the free-throw line, where a player would shoot from should there be a foul called.

During play, each team has five players on the court. The game starts with the referee tossing the ball in the air in between a player from each team, while each player tries to swat the ball to a member of their team (called a jump ball).

**Scoring**

Players can shoot towards the hoop from any point on the court. A different number of points is rewarded based on where the player is standing when they release the ball. The three shots are explained below.

-   Field Goal: Worth 2 points, scored by shooting within the three point line
-   Three Pointer: Worth 3 points, scored by shooting outside the three point line.
-   Free Throw: Worth one point, taken from the free throw line after a foul.

Players move the ball up and down the court by dribbling[^1], passing the ball to teammates, or shooting the ball. At the end of the game, which is played in four twelve-minute quarters, the team with the most points wins.

[^1]: to bounce the ball continuously while running or walking up and down the court

## Data

The `nba_draft` data set includes data from players that were selected in the NBA drafts between the years 1990-2021. Each row represents a different player and statistics from their respective careers in the NBA, some of which are still ongoing.

| Variable          | Description                                                                                                          |
|------------------|------------------------------------------------------|
| draft_pick        | The pick number a player was selected in the NBA draft                                                               |
| team              | The NBA team that drafted the player                                                                                 |
| player_name       | The name of the player selected                                                                                      |
| college           | The college the player attended (NA for those drafted out of high school, G-League team for international prospects) |
| years_played      | Number of years spent in the NBA                                                                                     |
| games_played      | Games played in the NBA                                                                                              |
| total_mins_played | Total minutes played in the NBA                                                                                      |
| total_pts         | Total points scored in the NBA                                                                                       |
| total_rebounds    | Total rebounds grabbed in the NBA                                                                                    |
| total_assists     | Total assists recorded in the NBA                                                                                    |
| fg_percent        | The percent of field goal shots made by the player in the NBA                                                        |
| three_pt_percent  | The percent of three-point shots made by the player in the NBA                                                       |
| ft_percent        | The percent of free throws made by the player in the NBA                                                             |
| win_shares        | Win shares in the NBA                                                                                                |
| win_shares_per_48 | Win shares in the NBA per 48 minutes                                                                                 |
| draft_year        | Year the player was drafted                                                                                          |
| mins_per_game     | Average number of minutes played per game for career in the NBA                                                      |
| pts_per_game      | Average number of points scored per game for career in the NBA                                                       |
| rebounds_per_game | Average number of rebounds per game for career in the NBA                                                            |
| assists_per_game  | Average number of assists per game for career in the NBA                                                             |
| round_picked | Indicates the round the player was selected (either round 1 or round 2) |
| pick_in_round | Indicates the order in which players were selected in that round | 

: [nba_draft.csv](stat_289_score/vgjohn/nba_draft_module_213/Data_Repo_Submission/nba_draft.csv)

## Questions

1. State the null and alternative hypotheses for a one-way ANOVA test in the context of the data. 

2. Comment on the amount of variability within groups compared to amount of variability between groups. 

3. Explain the results of the one-way ANOVA test and some of the applications the results can be used for. 

## References

[20 Years of NBA Draft Data - Kaggle](https://www.kaggle.com/datasets/benwieland/nba-draft-data){target="_blank"}

