---
title: "Investigating Surfaces Impact on Win Percentages in Professional Tennis"
date: June 18, 2024
author:
  - name: Eric Seltzer
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
description: Multiple linear regression modeling process
editor: 
  canonical: true
categories:
  - Multiple linear regression
  - Assumptions
  - Interpretations
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

In the Association of Tennis Professionals (ATP) the rankings are typically based on set parameters. Throughout the year there are tournaments that are worth different numbers of points. There are four tiers of events, Grand Slams, Masters 1000, ATP 500 and ATP 250. You receive the most points in your [ATP rankings](https://en.wikipedia.org/wiki/ATP_rankings) from winning a Grand Slam, and the least from winning an ATP 250 tournament. In Tennis, there are also three different types of surfaces that are played on. The options are Grass, Hard, and Clay. The surfaces are important to keep track of as the speed of tennis changes, e.g., clay generally slows the ball down whereas grass speeds it up. Certain players perform better on certain surfaces. This data set contains information for each player on each surface. Throughout the year, there are two Grand Slams on a Hard court, one on Clay, and one on Grass.

The data set we will be using is from [Wheelo Ratings](https://www.wheeloratings.com/tennis_atp_stats_last52.html). In this rating website, they have calculated an ELO rank for each player. This ranking considers not only what tournament you are playing in, but who you are playing. For instance, if 4th ranked Coco Gauff beats 1st ranked Iga Swiatek, it will be worth more to her ELO ranking than if she beat 14th ranked Emma Navarro in the same tournament.

#### Additional Tennis Information
In Tennis, there is the Association of Tennis Professionals (ATP) for men, and the Women's Tennis Association (WTA) for women. The ATP has 60 tournaments a year while the WTA has over 70. Both the ATP have the WTA have four grand slam tournaments. In the ATP, these Grand Slam tournaments are played in a best of 5 format instead of a best of 3 like every other tournament. In the WTA, every tournament is played in a best of 3 format, including the Grand Slam tournaments.

In this worksheet, we will look at the data including this Elo ranking and look at the process behind creating a multiple linear regression model in order to predict a player's win percentage.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1.  Understand the how to determine which variables are important to test.

2.  Understand how interaction terms and why they should be used.

3.  Be able to assess a model.

4.  Be able to interpret coefficients of a model.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Technology requirement: The activity handout will require nothing more than the handout and a writing utensil to complete.

1.  Knowledge of multiple linear regression.

2.  Knowledge of normal assumptions.

3.  Knowledge of assessing a model.
:::

### Data

There is one data set for this exercise. The data is made up of 5194 rows and 20 columns and is provided by Jeff Sackman on GitHub. Each row represents a match played between two players.

Download non tidy data: [atp_2023_213](data/atp_2023_213.csv)

**Tennis**

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable              | Description                                                                |
|-----------------------|----------------------------------------------------------------------------|
| Season                | The season the data is from                                                |
| Player                | The name of the NBA player                                                 |
| Pos                   | The position of the NBA Player                                             |
| Age                   | The age of the NBA player                                                  |
| Tm                    | The team that the player plays for                                         |
| G                     | The number of games played                                                 |
| GS                    | The number of games started                                                |
| MP                    | The number of minutes played                                               |
| FG                    | The number of field goals made                                             |
| FGA                   | The number of field goals attempted                                        |
| FG%                   | The field goal percentage                                                  |
| 3P                    | The number of 3 pointers made                                              |
| 3PA                   | The number of 3 pointers attempted                                         |
| 3P%                   | The 3 point percentage                                                     |
| 2P                    | The number of 2 pointers made                                              |
| 2PA                   | The number of 2 pointers attempted                                         |
| 2P%                   | The 2 point percentage                                                     |
| eFG%                  | The effective field goal percentage                                        |
| FT                    | The number of free throws made                                             |
| FTA                   | The number of free throws attempted                                        |
| FT%                   | The free throw percentage                                                  |
| ORB                   | The number of offensive rebounds                                           |
| DRB                   | The number of defensive rebounds                                           |
| TRB                   | The total number of rebounds                                               |
| AST                   | The number of assists                                                      |
| STL                   | The number of steals                                                       |
| BLK                   | The number of blocks                                                       |
| TOV                   | The number of turnovers                                                    |
| PF                    | The number of fouls                                                        |
| PTS                   | The number of points                                                       |
| Salary                | The salary for the season                                                  |
| InflationAdjSalary    | The salary for the season adjusted for inflation                           |
| logInflationAdjSalary | The salary for the season adjusted for inflation with a log transformation |
| PER                   | The player efficiency rating                                               |
| ESPR                  | Eric's salary to PER ratio                                                 |

</details>

#### Data Source

[Kaggle](https://www.kaggle.com/datasets/loganlauton/nba-players-and-team-data?select=NBA+Salaries%281990-2023%29.csv){target="_blank"}

### Materials

[Class Handout](nba_handout.docx)

[Class Handout - Solutions](nba_handout_key.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Forthcoming
:::
