---
title: "Men and Women's National Team Stats 2024"
author: "Faith Rhinehart" 
date: "June 23, 2025" 
format: html
categories:
  - Data Manipulating 
  - Creating Scatterplots and Labeling Points
---

## Motivation

Soccer, also known as football in many parts of the world, is a globally popular sport. Two teams of eleven players (4 defenders, 4 midfielders, 2 forwards, and 1 goalkeeper) compete to score goals by maneuvering a ball into the opposing team’s net using any part of the body except their hands and arms (goalkeepers are the exception). The game emphasizes a blend of physical endurance, technical skill, and strategic teamwork. Games are 90 minutes long, divided into two 45-minute halves, with extra time and penalty shootouts used if necessary to determine a winner. Players are evaluated not only on goals and assists but also on their passing accuracy, defensive contributions, and overall impact on the game. Referees use yellow and red cards to manage player behavior and maintain fairness on the field. A yellow card serves as a warning for actions such as reckless tackles, delaying the game, or showing dissent toward the referee. If a player receives two yellow cards in one match, it results in a red card, meaning the player is ejected from the game. A red card can also be given directly for more serious offenses like violent conduct, serious foul play, or using offensive language. When a player is shown a red card, their team must continue the match with one fewer player.

The U.S. Men's National Soccer Team (USMNT) was officially established in 1913 while the U.S. Women's National Team (USWNT) was established in 1985. Players are selected for the U.S. national soccer teams through a combination of scouting, performance, and coaching decisions. For major tournaments like the World Cup or Olympics, coaches must select a limited number of players—usually around 23—who offer the best balance of skill, experience, and team dynamics. Veteran players must also go through the same process but do have a higher advantage then a new player. 

## Data

The dataset provided (male and female soccer players on their respective National teams in 2024) was scraped from the U.S. Soccer official website (see references for links). 

::: {.callout-note collapse="true" title="Tidying Process"}

This process was used to make the datasets:
- **Copied and pasted the data set into Excel**
 * Created a .csv file for each men and women

:::


<details>
<summary><strong>Variable Descriptions</strong></summary>

2024 Men's (19 variables and 52 observations) data:

| Variable       | Description                                                    |
|----------------|----------------------------------------------------------------|                                      
| ..1            | Observation Number                                             |          
| Player         | Name of Player                                                 |
| Pos            | Player's Position                                              |
| GP             | Games Played                                                   |
| GS             | Games Where Player Started                                     |
| MIN            | Game Minutes Played                                            |
| G              | Goals Scored                                                   |
| A              | Assists                                                        |
| G+A            | Goals plus Assists                                             |
| YC             | Number of Yellow Cards Received                                |
| RC             | Number of Red Cards Received                                   |
| MOTM           | Number of Times Player was Recognized as "Man of the Match"    |
| Career Caps    | Number of International Games Played Representing National Team|
| Career Goals   | Career Goals                                                   |
| Career Assist  | Career Assists                                                 |
| Career G+A     | Career Goals plus Career Assists                               |
| OWN GOAL       | Number of own goals scored                                     |
| TOTALS         | Totals for each variable                                       |
| OPPONENT TOTALS| summary the opponent teams’ stats across games                 |

Women's (15 variables and 43 observations) data:

| Variable      | Description                                                    |
|---------------|----------------------------------------------------------------|  
| ..1           | Observation Number                                             |
| Name          | Name of Player                                                 |
| Pos.          | Player's Position                                              |
| GP            | Games Played                                                   |
| GS            | Games Where Player Started                                     |
| MIN           | Game Minutes Played                                            |
| G             | Goals Scored                                                   |
| A             | Assists                                                        |
| Y             | Number of Yellow Cards Received                                |
| R             | Number of Red Cards Received                                   |
| Career Caps   | Number of International Games Played Representing National Team|
| Goals         | Career Goals                                                   |
| Own Goal      | Number of own goals scored                                     |
| TOTAL         | Totals for each variable                                       |
| Opponents     | summary the opponent teams’ stats across games                 |
                       
</details>

Download Men's Data: [mensSoccer2024.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Soccer/mensSoccer2024.csv)

Download Women's Data: [womensSoccer2024.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Soccer/womensSoccer2024.csv)

## Questions Investigated
1. Can the dataset be tidied to become more readable?
2. Can the datasets be manipulated to be able to combine them?
3. Can new variables be added to the datasets?
4. Can we change the class of different variables?
5. Can we graph a scatterplot by using `MIN` to predict `Career Goals`?
6. Can the highest scoring player from both genders be found?
7. Can points be labeled on a scatterplot?

## References

Data was scraped from the U.S. Soccer official website:

[mensSoccer2024](https://www.ussoccer.com/usmnt-stats/2024){   }

[womenSoccer2024](https://www.ussoccer.com/uswnt-stats/2024){   }

Video was linked from YouTube:

<iframe width="560" height="315" src="https://www.youtube.com/embed/nT5qyrxoqsA?si=j5plkuc3Lx_-Ive6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

