---
title: "combined_leg_data"
format: html
editor: visual
---

Scraping data from Ski to Sea

```{r}
library(rvest)
```

2009 Leg Data

```{r}
## provide the URL and name it something (in this case, url).
url <- "https://skitosea.pacificmultisports.com/events/101/results/leg/1"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h %>% html_nodes("table")

#
test <- tab %>% html_table()

xcski_2009 <- test[[1]]
```

XCSKI

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 1
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/leg_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

DOWNHILL

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 2
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/downhill_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

RUN

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 3
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/run_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

ROAD BIKE

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 4
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/roadbike_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

CANOE

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 5
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/canoe_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

XCBIKE

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 6
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/xcbike_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

KAYAK

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
leg <- 7
isEvent <- TRUE

for (event in 101:111) {
  url <- paste0(base_url, event, "/results/leg/", leg)
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/kayak_results/event_", event, "_leg_", leg, "_results.csv"))
    
    # append leg number
    leg <- leg + 7
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```

Combine Canoe Data

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("canoe_results/event_", 101:111, "_leg_", seq(5, 75, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_canoe_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(canoe_time = `Elapsed Time`)
  
  combined_canoe_data <- bind_rows(combined_canoe_data, data)
}

```

Combine Downhill Data

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("downhill_results/event_", 101:111, "_leg_", seq(2, 72, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_downhill_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(downhill_time = `Elapsed Time`)
  
  combined_downhill_data <- bind_rows(combined_downhill_data, data)
}
```

Combine Kayak Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("kayak_results/event_", 101:111, "_leg_", seq(7, 77, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_kayak_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(kayak_time = `Elapsed Time`)
  
  combined_kayak_data <- bind_rows(combined_kayak_data, data)
}
```

Combine Roadbike Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("roadbike_results/event_", 101:111, "_leg_", seq(4, 74, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_roadbike_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(roadbike_time = `Elapsed Time`)
  
  combined_roadbike_data <- bind_rows(combined_roadbike_data, data)
}
```

Combine Run Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("run_results/event_", 101:111, "_leg_", seq(3, 73, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_run_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(run_time = `Elapsed Time`)
  
  combined_run_data <- bind_rows(combined_run_data, data)
}
```

Combine XC Bike Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("xcbike_results/event_", 101:111, "_leg_", seq(6, 76, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_xcbike_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(xcbike_time = `Elapsed Time`)
  
  combined_xcbike_data <- bind_rows(combined_xcbike_data, data)
}
```

Combine XC Ski Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("xcski_results/event_", 101:111, "_leg_", seq(1, 71, by = 7), "_results.csv")

# Read and combine the files using a loop
combined_xcski_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(xcski_time = `Elapsed Time`)
  
  combined_xcski_data <- bind_rows(combined_xcski_data, data)
}
```

Combine Overall Results

```{r}
library(readr)
library(dplyr)

# List of file names
file_names <- paste0("overall_results/event_", 101:111,"_results.csv")

# Read and combine the files using a loop
combined_overall_data <- NULL
nyears = length(file_names)

for (i in 1:nyears) {
  data <- read_csv(file_names[i]) %>% 
  mutate(Year = i + 2008) %>%
  mutate(`Elapsed Time` = as.character(`Elapsed Time`)) %>%
  select(`Elapsed Time`, `Team Name`, `Year`) %>%
  rename(overall_time = `Elapsed Time`)
  
  combined_overall_data <- bind_rows(combined_overall_data, data)
}
```

Combine All Leg Results

```{r}
combined_leg_data <- inner_join(combined_xcski_data, combined_canoe_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_downhill_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_kayak_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_roadbike_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_run_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_xcbike_data, by = c("Team Name", "Year")) %>%
  inner_join(combined_overall_data, by = c("Team Name", "Year"))

combined_leg_data <- combined_leg_data %>%
  select(`Year`, `Team Name`, `overall_time`, everything())
```

```{r}
library(dplyr)
library(lubridate)
library(tidyverse)

combined_leg_data <- combined_leg_data %>%
  mutate(canoe_minutes = hour(hms(canoe_time)) * 60 + minute(hms(canoe_time)) + second(hms(canoe_time))/60) %>%
  mutate(xcski_minutes = hour(hms(xcski_time)) * 60 + minute(hms(xcski_time)) + second(hms(xcski_time))/60) %>%
  mutate(downhill_minutes = hour(hms(downhill_time)) * 60 + minute(hms(downhill_time)) + second(hms(downhill_time))/60) %>%
  mutate(kayak_minutes = hour(hms(kayak_time)) * 60 + minute(hms(kayak_time)) + second(hms(kayak_time))/60) %>%
  mutate(roadbike_minutes = hour(hms(roadbike_time)) * 60 + minute(hms(roadbike_time)) + second(hms(roadbike_time))/60) %>%
  mutate(run_minutes = hour(hms(run_time)) * 60 + minute(hms(run_time)) + second(hms(run_time))/60) %>%
  mutate(xcbike_minutes = hour(hms(xcbike_time)) * 60 + minute(hms(xcbike_time)) + second(hms(xcbike_time))/60) %>%
  mutate(overall_minutes = hour(hms(overall_time)) * 60 + minute(hms(overall_time)) + second(hms(overall_time))/60)

Ski_to_Sea_Data <- na.omit(combined_leg_data)

Ski_to_Sea_Data <- Ski_to_Sea_Data %>% select("Year", "Team Name", "overall_minutes", "canoe_minutes", "xcski_minutes", "downhill_minutes", "kayak_minutes", "roadbike_minutes", "run_minutes", "xcbike_minutes")
```

```{r}
write.csv(Ski_to_Sea_Data, file = "Ski_to_Sea_Data.csv")
```
