---
title: Statistics of Ski to Sea Race from 2009-2019
author: Sam Peacock
date: May 8, 2024
description: Comparing time in minutes for each leg of the Ski to Sea Race to the overall result times from 2009-2019
categories:
  - Correlation 
---

## Motivation

The Ski to Sea race is a multi-sport relay race held annually in Whatcom County, Washington. The race consists of seven legs: cross-country skiing, downhill skiing or snowboarding, running, road biking, canoeing, mountain biking, and kayaking, with each leg representing a different outdoor sport. 

This module focuses on analyzing which leg of the race is most important to a team's success for the Ski to Sea Race. Focusing on the correlation of time in minutes taken to complete each leg, this module examines the relative importance of each leg in contributing to the overall time in the Ski to Sea race.

## Data

Each row of data provides the leg race times in minutes for one team in a given year. The dataset covers 11 Ski to Sea Races from 2009-2019 with 5842 cases in all. Each race consists of seven legs: canoe, cross country ski, downhill ski, kayak, road bike, run, and cross country bike. 

| Variable           | Description                                                        |
|--------------------|--------------------------------------------------------------------|
| `Year`             | The year the race took place (2009-2019)                           |
| `Team Name`        | The team's name                                                    |
| `canoe_minutes`    | The amount of minutes taken to complete the canoe leg              |
| `xcski_minutes`    | The amount of minutes taken to complete the cross country ski leg  |
| `downhill_minutes` | The amount of minutes taken to complete the downhill ski leg       |
| `kayak_minutes`    | The amount of minutes taken to complete the kayak leg              |
| `roadbike_minutes` | The amount of minutes taken to complete the roadbike leg           |
| `run_minutes`      | The amount of minutes taken to complete the run leg                |
| `xcbike_minutes`   | The amount of minutes taken to complete the cross country bike leg |
| `overall_minutes`  | The amount of minutes taken to complete the entire race            |

: [Ski_to_Sea_Data.csv](../data/Ski_to_Sea_Data.csv)

## Questions

1.  Which leg of the Ski to Sea race has the strongest correlation with the overall race time? Does this vary across different years?

2.  Are certain legs more consistent in their impact on the overall race time, or do their effects vary widely between teams and years?

3.  Do successful teams exhibit a consistent strategy in terms of leg performance, such as prioritizing certain legs over others?

4.  Have the relative importance of each leg changed over the years? Are there trends or patterns in how different legs contribute to the overall race time?

## References

The data were obtained from [Ski to Sea Website](https://skitosea.pacificmultisports.com/results)
