---
title: Ski to Sea Data Description
author: Sam Peacock
date: May 3, 2024
description: This module focuses on analyzing which leg of the race is most important to a team's success for the Ski to Sea Race. Focusing on the correlation of time taken to complete each leg and the overall team place, this module examines the relative importance of each leg in contributing to overall place in the Ski to Sea race.

categories:
  - Multiple Regression
  - Correlation
  - that can be used
---

## Motivation

The Ski to Sea race is a multi-sport relay race held annually in Whatcom County, Washington. The race consists of seven legs: cross-country skiing, downhill skiing or snowboarding, running, road biking, canoeing, mountain biking, and kayaking, with each leg representing a different outdoor sport.

In this first section, describe the source of the dataset and what it's about. Give any necessary background about it and the sports research question of interest. See other datasets on the website for examples.

## Data

Describe the data. What does each row represent? How many rows are there? If there is missingness, say how it is coded and why it is present.

| Variable      | Description                                                   |
|---------------|---------------------------------------------------------------|
| Minutes       | A team's Time (minutes) taken to complete a leg of the race   |
| Overall Place | A team's overall place in the race                            |

: [filename.csv](../data/filename.csv)

For the link above, change filename.csv to the name of the data file. Leave the `../data/` part in the link; this is where the data will live in the system.

If there are multiple data files, repeat the table, including the line starting with `:`, for each data file.

## Questions

If possible, list some analyses or research questions that could be answered with this dataset, or the types of questions you'd ask students. This is mainly meant to give other instructors ideas for how they could use the data.

## References

Give references to the original source here, such as by pasting the package citation:

Petti B, Gilani S (2022). *baseballr: Acquiring and Analyzing Baseball Data*. R package version 1.3.0, <https://CRAN.R-project.org/package=baseballr>.

If the dataset has a particular license, mention the license here. For example, "Data available under the Creative Commons Attribution license."
