---
title: "2025 Women's Track Running: Fixing Non-Linear Data with a Log Transformation"
format: 
  html:
      embed-resources: true
---

In outdoor track, runners run on a track and compete to complete the distance in the shortest time. There are many different events (distinguished by length, measured in meters) and runners typically have a specialty between distance or sprint. Distance runners need to think about pacing themselves and strategically overtaking competitors. Sprinters need to get a good start and maintain their highest speed for a short period of time. NCAA Women's Division 1 track runners compete at a very high level, and their times are recorded throughout the season to track the top individual achievements.

```{r}
library(tidyverse)
library(ggplot2)

track <- read.csv("WomensTrack2025.csv")
```

Each row in this data set represents one of the 50 fastest times in a given event for the 2025 NCAA Women's Division 1 East outdoor track season (with only a runner's fastest time included, no runner is included more than once for a single event). Runners' speeds have been calculated (in meters per second) by dividing the event's distance by the runner's time.

There are 351 rows observed over 10 variables.

### 1. Define a model using distance (Event) to predict speed and interpret the R-squared for the model.

### 2. Make a scatterplot representing the model you defined.

#### 2.1. What do you notice? (think of model conditions)

#### 2.2. Given the context from the first paragraph and/or your background knowledge of the sport, give a possible explanation for what you noticed.

The scatterplot above shows that at first, there is very quick decay in speed as distance increases, but then that decay slows and soon levels out. There are a few different ways we could account for this non-linearity in a model. One (the one this worksheet explores) is to use a transformation on the data.

### 3. Based on the model's issue, apply a transformation to the data to make a linear model more appropriate.

### 4. Make a scatterplot showing the transformed relationship.

### 5. Define a model using the transformed data and print a summary.

### 6. Interpret the R-squared for this model and compare it to the R-squared from question 1.

Look back at your scatterplots and notice that despite the increased appropriateness of the transformed model, the data still has some curvature. To deal with this stubborn curvature we will apply another transformation.

### 7. Apply an appropriate transformation to the Speed variable in the data.

### 8. Make a scatterplot showing this relationship.

### 9. Define a model using the transformed data and print a summary.

### 10. Which of the three models you defined do you prefer?

### 11. Is there a downside to the model you prefer?