---
title: "exploration"
author: "Brendan Karadenes"
format: html
---

```{r}
Sys.setenv(CFBD_API_KEY = "+R2YMcbKerOTZ/CwnOquxCPVYE8kZ+Z//G4gRA6zIxYst5iZBvFxtI50dKiP7uCq")
```


```{r}
library(tidyverse)
library(here)
library(readxl)
```

```{r}
receivers <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recievers.xlsx"))
recruits <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit.xlsx"))
```

```{r}
recruits <- recruits %>%
  rename(Player = Name)
```

```{r}
full_data <- inner_join(x = recruits, y = receivers, by = "Player")
```

```{r}
install.packages("remotes")
install.packages("cfbfastR")
remotes::install_github("saiemgilani/cfbscrapR")
```

```{r}
library(cfbscrapR)
cfb_recruiting_position(start_year = 2023, end_year = 2000)
```

```{r}
recruits_17 <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit_17.xlsx"))
recruits_15 <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit_15.xlsx"))
recruits_18 <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit_18.xlsx"))
recruits_19 <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit_19.xlsx"))
```

```{r}
recruits_17 <- recruits_17 %>%
  rename(Player = Name)
```

```{r}
full_data2 <- inner_join(x = recruits_17, y = receivers, by = "Player")
```

```{r}
recruits_17 <- read_excel(here("bkaradenes/CollegeFB_Module/exploration/recruit_17.xlsx"))
```

```{r}
recruits_15 <- recruits_15 %>%
  mutate(`HometownInfo Latitude` = as.numeric(`HometownInfo Latitude`),
         `HometownInfo FipsCode` = as.numeric(`HometownInfo FipsCode`))
recruiting <- full_join(x = recruits_15, y = recruits)
```

```{r}
recruiting <- full_join(x = recruiting, y = recruits_17)
recruiting <- full_join(x = recruiting, y = recruits_18)
recruiting <- full_join(x = recruiting, y = recruits_19)
```

```{r}
recruiting <- recruiting %>%
  rename(Player = Name)
```

```{r}
recruiting_data <- inner_join(x = recruiting, y = receivers, by = "Player")
```




