---
title: "Investigating Surfaces Impact on Win Percentages in Professional Tennis"
date: June 11, 2024
author:
  - name: Eric Seltzer
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
description: Describing distribution shapes and interpreting visualizations.
editor: 
  canonical: true
categories:
  - Five Number Summary
  - Distribution
  - Side-by-side boxplots
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

In the Association of Tennis Professionals (ATP) the rankings are typically based on set parameters. Throughout the year there are tournaments that are worth different numbers of points. There are four tiers of events, Grand Slams, Masters 1000, ATP 500 and ATP 250. You receive the most points in your [ATP rankings](https://en.wikipedia.org/wiki/ATP_rankings) from winning a Grand Slam, and the least from winning an ATP 250 tournament. In Tennis, there are also three different types of surfaces that are played on. The options are Grass, Hard, and Clay. The surfaces are important to keep track of as the speed of tennis changes, e.g., clay generally slows the ball down whereas grass speeds it up. Certain players perform better on certain surfaces. This data set contains information for each player on each surface. Throughout the year, there are two Grand Slams on a Hard court, one on Clay, and one on Grass.

#### Additional Tennis Information
In Tennis, there is the Association of Tennis Professionals (ATP) for men, and the Women's Tennis Association (WTA) for women. The ATP has 60 tournaments a year while the WTA has over 70. Both the ATP have the WTA have four grand slam tournaments. In the ATP, these Grand Slam tournaments are played in a best of 5 format instead of a best of 3 like every other tournament. In the WTA, every tournament is played in a best of 3 format, including the Grand Slam tournaments.

In this worksheet, we will look at the data including this Elo ranking and look at distributions, shapes, and a multiple linear regression model. There will be questions about each of these, some of them being more open ended than others.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1.  Understand the shapes of distribution as well as terms used to describe distribution.

2.  Understand the five number summary and be able to calculate some of its numbers.

3.  Be able to interpret a side-by-side box plots.

4.  Compare differences between two populations through visualizations. 
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Technology requirement: The activity handout will require nothing more than the handout and a writing utensil to complete.

1.  Knowledge of distribution types and terms that come along with it.

2.  Knowledge of the five number summary and how the numbers are calculated.

3.  Knowledge of interpreting box plots and what they represent.
:::

### Data

There is one data set for this exercise. The data is made up of 5194 rows and 20 columns and is provided by Jeff Sackman on GitHub. Each row represents a match played between two players.

Download non tidy data: [atp_2023_113](data/atp_2023_113.csv)

**Tennis**

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable           | Description                                           |
|--------------------|-------------------------------------------------------|
| tourney_name       | The name of the tournament                            |
| GS                 | Whether this tournament was a grand slam or not       |
| surface            | The type of surface that was played on for this match |
| result             | Whether this player was a winner or not               |
| player             | The name of the player                                |
| rank               | The ATP ranking of the player                         |
| hand               | The handedness of the player                          |
| height             | The height of the player (cm)                         |
| country            | The country the player is representing                |
| age                | The age of the player                                 |
| minutes            | How long the match was in minutes                     |
| numAces            | The number of aces                                    |
| numDF              | The number of double faults                           |
| servePoints        | The number of serve points                            |
| first_serve_won    | The number of serve points won                        |
| second_serve_won   | The number of second serve points won                 |
| serve_games_won    | The number of serve games won                         |
| first_serve_in     | The number of first serves in                         |
| break_points_saved | The number of break points saved                      |
| break_points_faced | The number of break points faced                      |

</details>

#### Data Source

[Jeff Sackman](https://github.com/JeffSackmann/tennis_atp){target="_blank"}

### Materials

[Class Handout](tennis_handout113.docx)

[Class Handout - Solutions](tennis_handout113_key.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Forthcoming
:::
