---
title: "erging_exploration"
format: html
---
# Libraries

```{r}
library(tidyverse)
library(readr)
```

# Data

```{r}
erg_df <- read_csv("~/Desktop/git/score_new/awsmit22/erging_module/stat213/exploration/erg.csv")

erg_df <- erg_df |> mutate(Verified = as.factor(Verified), Gender = as.factor(Gender), Year = as.factor(Year), Distance = as.factor(Distance))
```

# Graphical Exploration

```{r}
ggplot(data = erg_df, aes(x = Distance, y = Split)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Verified, y = Split)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Age_Group, y = Split)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Year, y = Split)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Age, y = Time)) + geom_point() + facet_grid(Gender ~Distance)
```

```{r}
ggplot(data = erg_df, aes(x = Age, fill = Distance)) + geom_bar()
```

```{r}
bar <- erg_df |> group_by(Country) |> summarise(n = n()) |> mutate(Country = fct_reorder(Country, n)) |> filter(n >= 8)

ggplot(data = bar, aes(x = Country, y = n)) + geom_col() + coord_flip() + geom_text(aes(label = n), hjust = -0.1) + theme_minimal() + labs(title = "Bar Plot of 20 Countries With The Most Rowers", y = "Number of Rowers") + theme(plot.title = element_text(hjust = 0.5))
```


# Statistical Exploration

```{r}
age <- lm(Speed ~ Age, data = erg_df)
summary(age)
```

```{r}
sex <- lm(Speed ~ Gender, data = erg_df)
summary(sex)
```

```{r}
dist <- lm(Speed ~ Distance, data = erg_df)
summary(dist)
```

```{r}
age_grp <- lm(Speed ~ Age_Group, data = erg_df)
summary(age_grp)
anova(age_grp)
```

```{r}
t.test(Speed ~ Verified, data = erg_df)
```

```{r}
ggplot(data = erg_df, aes(x = Verified, y = Speed)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Age, y = Pos, colour = Distance)) + geom_point(alpha = 0.5) + facet_wrap(~Gender) + theme_minimal()
```

```{r}
ggplot(data = erg_df, aes(x = Age_Group)) + geom_bar() 
```

# Modelling

```{r}
simple <- lm(Pos ~ Age, data = erg_df)
summary(simple)
```

```{r}
ggplot(erg_df, aes(x = Age, y = Pos)) + geom_point() + geom_smooth() + facet_grid(Distance ~ Gender)
```

```{r}
ggplot(data = erg_df, aes(x = Speed)) + geom_histogram() + facet_wrap(~Year)
```

```{r}
no_outliers <- erg_df |> filter(Name != "Toño Martí ayala" & Name != "Lynn Hansford" & Name != "Travis Willcox" & Name != "Natasshia Lee")
```

```{r}
ggplot(data = no_outliers, aes(x = Speed)) + geom_histogram() + facet_wrap(~Year)
```

```{r}
simple2 <- lm(Speed ~ Age, data = erg_df)
summary(simple2)
```

```{r}
ggplot(data = erg_df, aes(x = Distance, y = Age)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Gender, y = Age)) + geom_boxplot()
```

```{r}
ggplot(data = erg_df, aes(x = Age)) + geom_histogram() + facet_wrap(~Year)
```

```{r}
ggplot(data = erg_df, aes(x = Distance, y = Age)) + geom_col()
```

