---
title: "2025 Kentucky Derby Results"
author: "Faith Rhinehart" 
date: "July 15, 2025" 
format: html
categories:
  - Muliple Linear Regression
  - Simple Linear Regression
  - Correlation
---

## Motivation

Horse racing at the Kentucky Derby is a high-stakes thoroughbred competition held annually on the first Saturday in May at Churchill Downs in Louisville, Kentucky. Known as “The Most Exciting Two Minutes in Sports,” the Derby features a 1¼-mile (10 furlong) race on a dirt track, where up to 20 three-year-old horses compete for a chance at Triple Crown glory. The race is a fast-paced dash requiring both speed and stamina. Jockeys must navigate position, pace, and track conditions to secure a winning run to the finish line.

The Kentucky Derby is the first leg of the Triple Crown, followed by the Preakness Stakes and Belmont Stakes. Horses qualify through a points-based Road to the Kentucky Derby series called prep races. Betting plays a major role in the excitement, with odds reflecting the public’s perception of each horse’s chances to win. Odds are determined by the amount of money wagered on each horse and fluctuate until post time. For example, a 5-1 horse would return 5 dollar profit for every 1 dollar bet if it wins. Favorites often have low odds, while long shots results in dramatic payouts. Beyond athleticism, the Derby is a cultural spectacle in Southern tradition.

## Data

The dataset provided (2025 Kentucky Derby final results) was scraped from Wikipedia (see references for link). 

::: {.callout-note collapse="true" title="Tidying Process"}

This process was used to make the dataset
- **Copied and pasted the data set into Excel**
  - Added 0 to indicate 0 winnings awarded
  - Switched the odds columns to just include the first number

:::


<details>
<summary><strong>Variable Descriptions</strong></summary>

2025 Kentucky Derby results (19 cases with 30 variables) data:

| Variable         | Description                |
|------------------|----------------------------|
| Finish           | Place Horse Finished       |
| Program Number   | Number of Horse            |
| Horse            | Horse's Name               |
| Qualifying Points| Points Earned in Prep Races|
| Trainer          | Trainer's Name             |
| Jockey           | Jockey's Name              |
| Morning Line Odds| Projected Odds Before Race |
| Final Odds       | Actual Odds Post Race      |
| Margin Lengths   | Blank Ends                 |
| Winnings         | Distance Between Finishers |

* Note that morning line odds values mean # to 1 odds
                       
</details>

Download Kentucky Derby Data: [horseRacing.csv](frhinehart/Horse Racing/Data Repository/horseRacing.csv)

## Questions Investigated
1. Does the projected Morning Line Odds do a good job predicting actual Final Odds?
2. Can we predict a horse's finish position using Final Odds and Qualifying Points?
3. Do horses with higher qualifying points tend to finish in better positions?
4. Do lower Final Odds (i.e., favorites) predict better race outcomes?

## References

Data was scraped from Wikipedia:

[2025 Kentucky Derby](https://en.wikipedia.org/wiki/2025_Kentucky_Derby){   }

