---
title: "Draft Picks"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(readr)
library(rvest)
library(ggplot2)
```

# Pick 1
```{r}
url <- "https://www.sportingnews.com/us/nhl/news/list-no-1-overall-pick-nhl-draft-history-canadiens/q1hnthszlyswpwgvsfk6vwzk"
h <- read_html(url)
tab <- h %>% html_nodes("table")

test <- tab %>% html_table()
draft_picks <- test[[1]]
draft_picks <- draft_picks[-1, ]
draft_picks <- draft_picks[-c(4)]
draft_picks <- draft_picks %>% rename("Year" = X1, "Player" = X3, "Team" = X2)
```


```{r}
draft_picks <- draft_picks %>%
  mutate(Division = case_when(Team %in% c("Toronto Maple Leafs", "Florida Panthers", "Boston Bruins", "Buffalo Sabres", "Detroit Red Wings", "Montreal Canadiens", "Ottawa Senators", "Tampa Bay Lightning") ~ "Atlantic",
                              Team %in% c("Carolina Hurricanes", "Columbus Blue Jackets", "New Jersey Devils", "Colorado Rockies", "New York Islanders", "New York Rangers", "Philadelphia Flyers", "Pittsburgh Penguins", "Washington Capitals") ~ "Metropolitan",
                              Team %in% c("Chicago Blackhawks", "Colorado Avalanche", "Quebec Nordiques", "Dallas Stars", "Minnesota North Stars", "Minnesota Wild", "Nashville Predators", "St. Louis Blues", "Winnipeg Jets", "Atlanta Thrashers") ~ "Central",
                              Team %in% c("Anaheim Ducks", "Calgary Flames", "Edmonton Oilers", "Los Angeles Kings", "San Jose Sharks", "Seattle Kraken", "Vancouver Canucks", "Vegas Golden Knights") ~ "Pacific"),
         Pick = 1
  ) %>% 
  filter(Year >= 2012)
draft_picks <- draft_picks[-c(22),]
```

```{r}
# https://www.statmuse.com/nhl/ask/nhl-3rd-overall-draft-picks

round_3 <- readxl::read_excel("~/OneDrive - St. Lawrence University/round_3.xlsx")
```

```{r}
# https://www.statmuse.com/nhl/ask/nhl-2nd-overall-draft-picks

round_2 <- readxl::read_excel("~/OneDrive - St. Lawrence University/round_2.xlsx")
```

```{r}
draft_picks <- bind_rows(draft_picks, round_2, round_3)
```

```{r}
Points <- c(31, 63, 39, 48, 69, 52, 44, 21, 21, 35, 10, 57, 10, 23, 37, 30, 64, 56, 42,
            24, 21, 43, 29, 23, 34, 33, 48, 9, 51, 32, 27)
```

```{r}
draft_picks <- bind_cols(draft_picks, Points) %>%
  rename("Points" = "...6")
```



```{r}
draft_picks %>% 
  mutate(Pick = factor(Pick)) %>%
  ggplot(aes(x = Pick, y = Points, color = Division)) +
  geom_point()
```

```{r}
points_division <- draft_picks %>%
  group_by(Division) %>%
  summarise(mean(Points)) %>%
  rename(average_points = "mean(Points)")
```

```{r}
draft_picks %>%
  ggplot(aes(x = Division, y = Points, fill = Division)) +
           geom_boxplot()
```

```{r}
summary(aov(Points~Division, data = draft_picks))
```












