---
title: "Shootout"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(readr)
library(rvest)
```

```{r}
nhl_schedule <- read_csv("~/OneDrive - St. Lawrence University/nhl_schedule.csv")
```

```{r}
shootout <- nhl_schedule %>%
  rename(V_goals = "G...3",
         H_goals = "G...5",
         extra_time = "...6",
         attendance = "Att.") %>%
  filter(extra_time == "SO") %>%
  select(c(1:7))
```

```{r}
shots_la <- read_csv("~/OneDrive - St. Lawrence University/shots_la.csv")
```

```{r}
url <- "https://www.espn.com/nhl/game?gameId=401458641"
h <- read_html(url)
tab <- h %>% html_nodes("table")
```

```{r}
test <- tab %>% html_table()

p1 <- test[[3]]
p2 <- test[[4]]
p3 <- test[[5]]
SO <- test[[7]]
```

```{r}
p1 <- p1[-c(2)]
p2 <- p3[-c(2)]
p2 <- p2[-c(2)]
SO <- SO[-c(2)]
```

```{r}
shootout <- shootout %>%
  mutate(home_win = if_else(H_goals > V_goals, TRUE, FALSE))
```

```{r}
shootout %>%
  summarise(mean(home_win))
```

```{r}
shootout %>% 
  group_by(Home) %>%
  summarise(mean(home_win))
```

```{r}
shootout %>%
  group_by(Visitor) %>%
  summarise(mean(home_win))
# visitor loss
```














