---
title: "womenFigureSkatingCleanup"
Authors: Faith Rhinehart
execute: 
  echo: true
  warning: false
format: 
  html:
    embed-resources: true
---

## Women's Olympic Data with years

```{r}
#2006 women data 
url3 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2006_Winter_Olympics_%E2%80%93_Ladies%27_singles"
tab3 <- read_html(url3) |>
  html_nodes("table") |> html_table()
womenSkate2006 <- tab3[[6]] 
anyDuplicated(names(womenSkate2006))
colnames(womenSkate2006) <- make.names(colnames(womenSkate2006), unique = TRUE)
womenSkate2006 <- womenSkate2006 |> mutate(Year = "2006")
#2010 women data 
url4 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2010_Winter_Olympics_%E2%80%93_Ladies%27_singles"
tab4 <- read_html(url4) |>
  html_nodes("table") |> html_table()
womenSkate2010 <- tab4[[7]] 
anyDuplicated(names(womenSkate2010))
colnames(womenSkate2010) <- make.names(colnames(womenSkate2010), unique = TRUE)
womenSkate2010 <- womenSkate2010 |> mutate(Year = "2010")
#2014 women data 
url5 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2014_Winter_Olympics_%E2%80%93_Ladies%27_singles"
tab5 <- read_html(url5) |>
  html_nodes("table") |> html_table()
womenSkate2014 <- tab5[[8]] 
anyDuplicated(names(womenSkate2014))
colnames(womenSkate2014) <- make.names(colnames(womenSkate2014), unique = TRUE)
womenSkate2014 <- womenSkate2014 |> mutate(Year = "2014")
#2018 women data 
url6 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2018_Winter_Olympics_%E2%80%93_Ladies%27_singles"
tab6 <- read_html(url6) |>
  html_nodes("table") |> html_table()
womenSkate2018 <- tab6[[8]] 
anyDuplicated(names(womenSkate2018))
colnames(womenSkate2018) <- make.names(colnames(womenSkate2018), unique = TRUE)
womenSkate2018 <- womenSkate2018 |> mutate(Year = "2018") |>
  rename(FS = "FS.1", FS.1 = "FS") |>
  rename(SP = "SP.1", SP.1 = "SP")
#2022 women data 
url7 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Women%27s_singles"
tab7 <- read_html(url7) |>
  html_nodes("table") |> html_table()
womenSkate2022 <- tab7[[8]] 
anyDuplicated(names(womenSkate2022))
colnames(womenSkate2022) <- make.names(colnames(womenSkate2022), unique = TRUE)
womenSkate2022 <- womenSkate2022 |> mutate(Year = "2022")

womenSkate2006$SP.1 <- as.character(womenSkate2006$SP.1)
womenSkate2010$SP.1 <- as.character(womenSkate2010$SP.1)
womenSkate2014$SP.1 <- as.character(womenSkate2014$SP.1)
womenSkate2018$SP.1 <- as.character(womenSkate2018$SP.1)
womenSkate2022$SP.1 <- as.character(womenSkate2022$SP.1)

allwomen_data <- bind_rows(womenSkate2006, womenSkate2010, womenSkate2014, womenSkate2018, womenSkate2022) |>
  mutate(`Total Points` = coalesce(TP, Total, `Total.points`, `Total.Points`)) |>
  select(-TP, -Total, -`Total.points`, -`Total.Points`) |>
  select(2:3, 5, 7, 8, 15) |>
  slice(1:24, 31:54, 65:85, 93:116, 124:147)
View(allwomen_data)
```

## Men's Olympic Data With Years

```{r}
Skating <- read_csv(here::here("frhinehart/Olympic Figure Skating/Module/MensFigureSkating.csv")) |>
  select(2:7)
```


## Women's and Men's Olympic Data 2022

```{r}
url1 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Women%27s_singles"
tab1 <- read_html(url1) |>
  html_nodes("table") |> html_table()

womenSkate <- tab1[[8]]

womenSkateTidy <- womenSkate[, c(2:4, 6, 8)] |> slice(1:24, 30) |> mutate(Sex = "Female") |> mutate(SP = as.numeric(SP)) |> mutate(FS = as.numeric(FS)) |> mutate(Total = as.numeric(Total))

url2 <- "https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Men%27s_singles"
tab2 <- read_html(url2) |>
  html_nodes("table") |> html_table()

menSkate <- tab2[[9]]

menSkateTidy <- menSkate[, c(2:4, 6, 8)] |> slice(1:24) |> mutate(Sex = "Male") |> mutate(SP = as.numeric(SP)) |> mutate(FS = as.numeric(FS)) |> mutate(Total = as.numeric(Total))

combined_data <- bind_rows(womenSkateTidy, menSkateTidy)
```

