---
title: "FigureSkating"
author: "Faith Rhinehart" 
date: "June 12th, 2025" 
format: html
categories:
  - ANOVA
  - Post Hoc Tukey Test
  - Confidence Interval
---

## Motivation

Figure skating is a sport where individuals, pairs, or groups preform with music on ice skates. Performing various tricks such as jumps, spins, and footwork showcases a combination of athleticism and artistry. Figure skating was the first winter sport to be in included in the Olympic Games in 1908. 

In the Olympics, athletes first performs a **Short Program** that lasts 2 minutes and 40 seconds. The **Short Program** is designed to highlight the skaters' technical skills and artistry since they must perform specific required elements. After the **Short Program**, skaters perform the **Free Skate** which last 1 to 4.5 minutes. The **Free Skate** allows for more creativity as Skaters' can choose from a variety of elements to create their performance. The combination of the **Short Program** score and **Free Skate** score gets added up into a total score which determines the winner. 

## Data

The dataset provided (male skaters' winter Olympic scores since 2006 with demographic information) was scraped from Wikipedia: 

[skate2006](https://en.wikipedia.org/wiki/Figure_skating_at_the_2006_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2010](https://en.wikipedia.org/wiki/Figure_skating_at_the_2010_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2014](https://en.wikipedia.org/wiki/Figure_skating_at_the_2014_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2018](https://en.wikipedia.org/wiki/Figure_skating_at_the_2018_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2022](https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

::: {.callout-note collapse="true" title="Tidying Process"}

This process was used to tidy dataset.

- **Sliced the full data set** to exclude:                                 
  - Skaters' who did not advance to free skate      

:::


<details>
<summary><strong>Variable Descriptions</strong></summary>

Olympics since 2006 data:

| Variable        | Description                                    |
|-----------------|------------------------------------------------|
| Rank            | How the skater was ranked among other skaters  |
| Name            | Skater's Name                                  |
| Nation          | Nation representing Skater                     |
| FS              | Free Skate Score                               |
| SP              | Short Program score                            |
| TP              | Combined score of free skate and short program |
| Year            | Olympic Year                                   |
                       
</details>


:[Figure Skating Data](frhinehart/Olympic Figure Skating/Module/MensFigureSkating.csv)

## Questions Investigated
1. Is there a significant difference in mean scores throughout the different years of the winter Olympics
2. Which specific years have a significant difference in mean scores

## References

[skate2006](https://en.wikipedia.org/wiki/Figure_skating_at_the_2006_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2010](https://en.wikipedia.org/wiki/Figure_skating_at_the_2010_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2014](https://en.wikipedia.org/wiki/Figure_skating_at_the_2014_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2018](https://en.wikipedia.org/wiki/Figure_skating_at_the_2018_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}

[skate2022](https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Men's_singles){target="_blank'}


<iframe width="560" height="315" src="https://www.youtube.com/embed/i6pw07k3GkM?si=ud_nUmub-iDQ_cAm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
