---
title: World Cup Women's 10k Classic Nordic Ski Race
author: Abigail Smith
date: February 29, 2024
description: The times and ranks of skiers taken at four different distance points (1.3, 4.3, 7.5, and 10k) in a 10k classic race in Trondheim, Norway.
categories:
  - simple linear regression analysis
  - multiple r-squared
  - checking conditions for simple linear regression
  
editor: 
  markdown: 
    wrap: 72
---
## Motivation

The International Ski and Snowboard Federation (FIS), organizes and records a series of events such as the World Cup which exists for all disciplines of FIS such as Nordic Skiing. World Cup races occur every weekend between January and March, with events hosted in different countries. These events consist of multiple different races, held in different disciplines and distances. Nordic skiing is split up into two different techniques, classic and skate, all race weekends have a mixture of skate and classic technique races. The race in this dataset is a women’s' 10k classic race set in Trondheim, Norway. In long distance pieces like 10ks there is often a lot of discussion about pacing. Racers' times are recorded at different distance intervals throughout the course. It is interesting to look at how well racers' times at different distances predict their rank at the end of the race. I think especially the first time is most interesting to see with regard to the final rank, to see if the same racers who have top times in the first distance have good ranks at the end of the race. 

The following questions are based on a dataset from a Nordic Ski race in Trondheim, Norway on the 17th December 2023. The race is one of many World Cup events held by the International Ski Federation throughout the months of December through March. This race in particular was a 10-kilometer women’s race in the classic technique, with 61 women enrolled. The course for this race consisted of two 5-kilometer loops. In the original data set, there are 4 different distance intervals taken at 1.3, 4.3, 7.5, and 10k respectively. 


## Data

Each row of the dataset represents a skier in the womens' 10k classic
ski race in Trondheim. There are 61 racers in the dataset and 20 variables.

| Variable | Description                                                                                                                |
|-------------------|-----------------------------------------------------|
| Bib      | The bib number of the skier, which also represents the order they started in.                                              |
| Name     | The name of the skier.                                                                                                     |
| NSA      | The nation a skier is representing.                                                                                        |
| Rank1    | The rank or placement of skiers at the first distance interval.                                                            |
| Time1    | The skier's time at the first distance interval, measured in minutes.                                                      |
| Diff1    | The difference of time between each skier and the first place racer, at the first distance interval, measured in seconds.  |
| Dist1    | The distance of the first interval, measured in kilometers.                                                                |
| Rank2    | The rank or placement of skiers at the first distance interval.                                                            |
| Time2    | The skier's time at the first distance interval, measured in minutes.                                                      |
| Diff2    | The difference of time between each skier and the first place racer, at the second distance interval, measured in seconds. |
| Dist2    | The distance of the second interval, measured in kilometers.                                                               |
| Rank3    | The rank or placement of skiers at the third distance interval.                                                            |
| Time3    | The skier's time at the third distance interval, measured in minutes.                                                      |
| Diff3    | The difference of time between each skier and the first place racer, at the third distance interval, measured in seconds.  |
| Dist3    | The distance of the third interval, measured in kilometers.                                                                |
| Rank4    | The rank or placement of skiers at the fourth distance interval.                                                           |
| Time4    | The skier's time at the fourth distance interval, measured in minutes.                                                     |
| Diff4    | The difference of time between each skier and the first place racer, at the fourth distance interval, measured in seconds. |
| Dist4    | The distance of the fourth interval, measured in kilometers.                                                               |
| Event    | The FIS code assigned to the event.                                                                                        |

: [W10kTro_2257.csv](W10kTro_2257.csv)


## Questions

1.    Fit the following models and create scatter plots with regression lines for each of them. Record their R2 values and comment on the linearity. 

2.    Interpret the slope coefficient for the best of these models to predict Rank4. Remember to contextualize. 

4.    If a skier is ranked #14 after the first split, what rank would you predict for her finish?

5.    Interpret the slope coefficient for the best of these models to predict Time4. Remember to contextualize.

6.    If a skier had a time of 5.00 minutes after the first split, what time would you predict for her finish?

 
## References

[FIS Results](https://live.fis-ski.com/cc-2257/results-pda.htm){target="_blank"}

