---
title: "TwoWayANOVA"
format: html
---

```{r}
library(ggplot2)
library(tidyverse)
library(here)
library(dplyr)
menSkating <- read_csv(here::here("frhinehart/Olympic Figure Skating/Module/MensFigureSkating.csv")) |> select(2:7) 

menSkating$Sex <- "Male"

combined_women_data <- bind_rows(womenSkate2006, womenSkate2010, womenSkate2014, womenSkate2018, womenSkate2022) 

combined_women_data$`Total Points` <- paste(combined_women_data$Total.points, combined_women_data$Total.Points, combined_women_data$TP, combined_women_data$Total) 

combined_women_data$`Total Points` <- gsub("NA", "", combined_women_data$`Total Points`)

WomenTidied <- combined_women_data |> select(2:3, 6, 8, 9, 19) |> slice(1:24, 31:54, 62:85, 93:116, 124:152) |> slice(1:120) |> mutate(Year = as.double(Year))

WomenTidied$Sex <- "Female"

combinedSkate <- bind_rows(menSkating, WomenTidied)

combinedSkate$`Free Skate` <- paste(combinedSkate$FS, combinedSkate$FS.1) 
combinedSkate$`Free Skate` <- gsub("NA", "", combinedSkate$`Free Skate`)

combinedSkate$`Short Program` <- paste(combinedSkate$SP, combinedSkate$SP.1)
combinedSkate$`Short Program` <- gsub("NA", "", combinedSkate$`Short Program`)

combinedSkate$Total <- paste(combinedSkate$TP, combinedSkate$`Total Points`)
combinedSkate$Total <- gsub("NA", "", combinedSkate$Total)

real <- combinedSkate |> select(1, 2, 6, 7, 11:13)
View(real)
```


```{r}
real$Total <- as.numeric(as.character(real$Total))
anova_result <- aov(Total ~ Year * Sex, data = real)
summary(anova_result)
```

Significant difference for all three
