---
title: "Exploring Logistic Regression Through Cricket"
author:
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Vivian Johnson
    affiliation:
      - ref: slu
date: "June 12, 2024"
description: "Using data from the Asia Cup Tournament to create a multiple logistic regression model."
editor: 
  canonical: true
categories:
  - Logistic Regression 
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

Cricket is a game watched and played by billions of people across the world. Second in global popularity only to football (soccer), it is extremely popular in South Asia, Australia, Africa, and Europe.

#### The Rules of Cricket

Cricket is played on a rectangular pitch inside an oval boundary. In the pitch, on either side, there is a vertical **wicket**, made up of three vertical wooden "stumps" with two wooden bails (small blocks of wood) resting atop the stumps. There are two teams, each with 11 players (a batting team and a bowling team).

**The bowling team:** The bowler bounces a small leather ball at the batter. The goal of the bowler is to get the batter out and ultimately knock the bails off of the stumps.

**The batting team:** The goal of the batting team is to score as many runs as possible and not let the bowler hit the bail off of the stumps. There are two batters at a time for the batting team. After the batter hits the ball, the two batters will attempt to switch sides. Each batter will go until they get out, when at that time, they will switch with another teammate.

**Scoring Runs:** Each time the two batters switch sides without getting out counts as a run scored. For example, if you hit the ball and are able to run to the other wicket and back without getting out, that would score two runs for your team. If the batter hits the ball on a bounce to the oval boundary, it counts as four runs scored. If the batter hits the ball over the oval boundary on a fly, it counts as six runs.

**Outs:** Below are a few common ways in which a batter can get out

-   If the batter hits the ball and it is caught in the air (caught out)
-   If a player on the bowling team throws the ball and it hits the bails off the stumps before the batter can cross the line while trying to score a run (run out)
-   If the bowler throws the ball past the batter and it knocks a bail off the wicket
-   If the batter gets hit in the legs by a ball that would have hit the wicket (Note: if the batter gets hit and the ball wasn't ruled as one that would have hit the wicket, the batter is not out)

The duration of cricket matches can range from hours to days, depending on what format is being played, and scores are often high as each individual batter usually scores many runs on multiple pitches before getting out.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will:

1.  Enhance ability to interpret coefficients in a multiple logistic regression model, including interaction coefficients and binary predictors. 

2.  Become proficient in being able to convert between log odds of an event and the probability.

3.  Be able to identify which predictors are useful to the model.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Knowledge of logistic regression and different components is necessary. R output is provided, and students should be familiar with writing simple R code and have the ability to read output clearly. Students should have knowledge of log odds and probability with regards to logistic regression, and have an understanding of how to interpret binary and numeric predictors. 
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
No explicit technology is required, although a calculator is recommended.
:::

### Data

The `asia_cup` data set includes data from each cricket match played in all Asia Cup Tournaments from 1984 (the first one) to 2022. The Asia Cup is a tournament that now takes place every two years, alternating host cities in different countries throughout Asia. Each row represents on game played. 

Download data: [asia_cup.csv](asia_cup.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable      | Description                                                              |
|-----------------------|-------------------------------------------------|
| Team          | One team of the match                                                    |
| Opponent      | The team played                                                          |
| Host          | Venue played at                                                          |
| Year          | Tournament year played                                                   |
| Toss          | Coin toss to determine who starts batting or bowling (0 = lost, 1 = won) |
| Selection     | Team's selection after winning / losing the toss (0 = Batting, 1 = Bowling)                     |
| Run Scored    | Total runs scored by that team                                           |
| Fours         | Total scored fours for that team                                         |
| Sixes         | Total scored sixes for that team                                         |
| Extras        | Amount of extra runs scored by that team                                 |
| Highest Score | Highest individual number of runs scored                                 |
| Result        | 0 = lost match, 1 = won match                                            |
| Given Extras  | Number of extra runs given up                                            |

</details>

#### Data Source

The data is sourced from this data set on [Kaggle](https://www.kaggle.com/datasets/hasibalmuzdadid/asia-cup-cricket-1984-to-2022/data)

### Materials

[Class handout](cricket_worksheet.docx)

[Class handout - with solutions](cricket_worksheet_SOLUTIONS.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
In conclusion, working with the Asia Cup tournament data provides a great opportunity to practice logistic regression. The mix of binary and numeric predictors allows for interesting models that make sense in the context and provide a lot of explanatory power regarding who wins the match or not. 
:::
