---
title: "Investigating Surfaces Impact on Win Percentages in Professional Tennis"
date: March 8, 2024
author:
  - name: Eric Seltzer
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
description: Exploring data through visualizations to create questions.
editor: 
  canonical: true
categories:
  - Data Visualization
  - Data Exploration
  - Modeling
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

The NFL, one of America's most popular sports league has some of the most available data. As the sport has evolved, many questions have been raised about the safety of the players and how to protect them. As it is a full contact sport, there are lots of injuries, particularly a large amount of head injuries. In this worksheet, we will be looking into investigating differences in concussions in the NFL. Some of the things we will look at are teams, positions, and seeing how the treatment of players differs.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1.  Understand a process for investigating data and deciding if there are questions to be looked into.

2.  Be comfortable using ggplot and creating sound data visualizations.

3.  Be able to decide if there is any questions worth pursuing further.

4.  Create an ANOVA model.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Technology requirement: The activity handout provides examples of how to clean and summarize data. For this, the use of R Studio is required and we will be using a quarto document. However, the activity could be modified to ask students to produce that information from the raw dataset and/or extend the activity to investigate other variables available in the data.

1.  Knowledge of tidyverse and creating variables

2.  Knowledge of ggplot

3.  Knowledge of interpreting visualizations and creating models
:::

### Data

This data is made up of 392 rows and 10 columns. Each row represents a player that experienced a concussion during the set time frame.

Download non tidy data: [concussion.csv](data/concussion.csv)

**American Football**

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable                       | Description                                                       |
|------------------------|------------------------------------------------|
| Player                         | The player's name                                                 |
| Team                           | The team that the player plays for                                |
| Date                           | The date in which the concussion happened                         |
| Position                       | The position that the player plays                                |
| Games Missed                   | The number of games the player missed with the injury             |
| Reported Injury Type           | What the injury was reported as                                   |
| Play Time After Injury         | How many downs the player played after getting injured            |
| Average Playtime Before Injury | How much the player was playing on average before getting injured |
| Offense                        | Whether the player was an offensive player or not                 |
| Skilled                        | Whether the player was a skilled position or not                  |

</details>

#### Data Source

[Kaggle](https://www.kaggle.com/datasets/rishidamarla/concussions-in-the-nfl-20122014/data){target="_blank"}

### Materials

[Class Handout](Class-Handout.qmd)

[Class Handout - Solutions](Class-Handout-Solutions.qmd)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Forthcoming
:::
