---
title: "exploration"
author: "Brendan Karadenes"
format: html
editor: visual
---

```{r}
# Get the Data
library(readr)
library(tidyverse)
vb_matches <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-19/vb_matches.csv', guess_max = 76000)
```

```{r}
# cleaning
vb_matches <- vb_matches %>%
  select(-date) %>%
  mutate(w_p1_birthyear = year(w_p1_birthdate),
         w_p2_birthyear = year(w_p2_birthdate),
         l_p1_birthyear = year(l_p1_birthdate),
         l_p2_birthyear = year(l_p2_birthdate)) %>%
  select(-w_p1_birthdate,
         -w_p2_birthdate,
         -l_p1_birthdate,
         -l_p2_birthdate) %>%
  separate(col = score, into = c("first_round", "second_round", "thrid_round"), sep = ", ", fill = "right")
```

```{r}
vb_matches <- vb_matches %>%
  mutate(w_rank = parse_number(w_rank),
         l_rank = parse_number(l_rank))
```

```{r}
vb_matches <- vb_matches %>%
  mutate(duration = as.numeric(period_to_seconds(hms(duration)))/60)
```

```{r}
write.csv(vb_matches,"vb_matches.csv", row.names = FALSE)
```

# Difference in Means

```{r}
avp_vb <- avp_vb %>%
  mutate(avg_tot_hitpct = (w_p1_tot_hitpct + w_p2_tot_hitpct + l_p1_tot_hitpct + l_p2_tot_hitpct)/4)
```

```{r}
fivb_vb <- fivb_vb %>%
  mutate(avg_tot_hitpct = (w_p1_tot_hitpct + w_p2_tot_hitpct + l_p1_tot_hitpct + l_p2_tot_hitpct)/4)
```

```{r}
avp_vb %>%
  filter(avg_tot_hitpct != "NA") %>%
  summarise(mean(avg_tot_hitpct),
            sd(avg_tot_hitpct),
            n())
```

```{r}
fivb_vb %>%
  filter(avg_tot_hitpct != "NA") %>%
  summarise(mean(avg_tot_hitpct),
            sd(avg_tot_hitpct),
            n())
```

```{r}
vb_matches_women <- vb_matches %>%
  filter(gender == "W") %>%
  mutate(avg_age = (w_p1_age + w_p2_age)/2)


ggplot(data = vb_matches_women, mapping = aes(x = avg_age, y = w_rank)) +
  geom_hex() +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(x = "Average Age", y = "Winning Team Rank", title = "Winning Team Age vs. Rank") +
  theme(plot.title = element_text(hjust = 0.5))
```




