---
title: "Multicollinearity in the Negro Leagues"
author: 
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Brendan Karadenes
    affiliation: 
      - ref: slu
    date: June 21, 2024
    description: Describing multicollinearity between different statistics in the Negro Leagues
    categories:
      - Linear Regression
      - Correlation
      - Multicollinearity
---

## Introduction

For this activity, you will be exploring batting statistics for players that competed in the [Negro Leagues](https://www.seamheads.com/NegroLgs/index.php){target="_blank"}.

In particular, you will examine linear regression output to determine correlation and multicollinearity between different batting statistics. Also, you will use VIFs and p-values to compare and contrast multicollinearity and significance between different variables.

Investigating these trends is useful for several reasons. Exploring these trends can help us understand which players that take certain approaches to the plate end up scoring the most runs for their team. Also, analyzing different types of batting statistics give insights about the subtleties that separate the average and great players. It can help identify which groups of statistics hitters are most likely to excel in and which will help them be the most successful. Analyses like these can help inform front offices on what type of hitters to have in their lineups.

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity would be suitable for an in-class example.
:::

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, you will be able to:

1.  Create linear models and obtain summary output in R
2.  Analyze correlation using p-values and VIFs
3.  Construct visualizations of variable correlations
4.  Make conclusions about the usefulness of specific variables
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
For this activity, students will primarily use linear regression models to analyze correlations. Students will also likely require basic knowledge of t-tests.
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
The provided worksheets will require access to R and RStudio.

Since the data is provided, instructors are encouraged to modify the worksheets to expand analysis on the data.
:::

### Data

The data set contains 502 rows and 34 columns. Each row represents a player who competed in the negro leagues during the period from 1886 to 1948.

Download data:

Available on the [SCORE Data Repository](https://data.scorenetwork.org/): [ngl_batting.csv](https://github.com/SCOREnetworkorg/sports-data-repository/raw/main/data/ngl_batting.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable     | Description                                               |
|--------------|-----------------------------------------------------------|
| rank         | career hit rank                                           |
| Player       | first and last name of player                             |
| G            | number of games played                                    |
| AB           | number of at-bats                                         |
| R            | number of runs scored                                     |
| H            | number of hits                                            |
| Doubles      | number of doubles                                         |
| Triples      | number of triples                                         |
| HR           | number of homeruns                                        |
| RBI          | number of runs batted in                                  |
| SB           | number of stolen bases                                    |
| CS           | number of times caught stealing                           |
| BB           | number of walks                                           |
| SO           | number of strikeouts                                      |
| IBB          | number of intentional walks                               |
| HBP          | number of times hit by a pitch                            |
| SH           | number of sacrifice hits                                  |
| SF           | number of sacrifice flys                                  |
| DP           | number of times hit into a double play                    |
| BA           | career batting average                                    |
| OBP          | career on-base percentage                                 |
| SLG          | career slugging percentage                                |
| OPS          | career on-base plus slugging percentage                   |
| OPS_plus     | career on-base plus slugging normalized across the league |
| wOBA         | career weighted on-base average                           |
| BB_rate      | career walk percentage                                    |
| K_rate       | career strikeout percentage                               |
| BB_K_ratio   | career walk to strikeout ratio                            |
| homerun_rate | career homerun percentage                                 |
| ISO          | career extra-base hits averaged per at bat                |
| begin_year   | year the player began their career                        |
| end_year     | final year the player played                              |
| Pos          | primary position of the player                            |
| PA           | number of career plate appearances                        |

**Data Source**

[SeamHeads](https://www.seamheads.com/NegroLgs/index.php){target="_blank"}

</details>

### Materials

We provide an editable Quarto File and its solutions.

[Class handout](batting_worksheet.qmd)
[Class Handout - with solutions](batting_worksheet_key.qmd)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
In conclusion, the Negro Leagues Batting worksheet provides valuable learning opportunities for students in several important areas. It allows them to understand reasons why correlations exist and how models can change significantly just by adding one or two variables. The calculation of VIF and p-values allows the students to compare and contrast different models and show how small differences between batter outcomes can have a large impact on the outcome of the game. Overall, this worksheet allows students to conduct an in-depth analysis on hitter data from the Negro Leagues and draw meaningful conclusions about the performances of the players who helped make baseball America's pastime. 
:::



