---
title: "Determining Outlier Influence With Figure Skating "
author:
  - name: Faith Rhinehart
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Jessica Chapman
    email: jchapman@stlawu.edu
    affiliation:
      - ref: slu
date: "June 9th, 2025"
description: "Exploring Different Outlier Detection Stratigies"
editor: 
  canonical: true
categories:
  - Standarized Residuals
  - Leverage
  - Cook's Distance
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.


### Background to Powerlifting Video

If you are unfamiliar with Figure Skating, please watch this video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/SSQzeYYs6s0?si=3so0I5NXUR7tee56" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Introduction to Module

Figure skating is a sport where individuals, pairs, or groups preform with music on ice skates. Performing various tricks such as jumps, spins, and footwork showcases a combination of athleticism and artistry. Figure skating was the first winter sport to be in included in the Olympic Games in 1908. 

In the Olympics, athletes first performs a Short Program that lasts 2 minutes and 40 seconds. The Short Program is designed to highlight the skaters' technical skills and artistry since they must perform specific required elements. After the hort Program, skaters perform the Free Skate which last 1 to 4.5 minutes. The Free Skate allows for more creativity as Skaters' can choose from a variety of elements to create their performance. The combination of the Short Program score and Free Skate score gets added up into a total score which determines the winner. 

The menSkating dataset features data from individual sakters during the winter olympics since 2006. Variables include Name, Nation, Year, Free Skate Score (FS), Short Program Score (SP), and Total Points (TP). The relevant variables for this specific module are FS and SP. 

For the sake of this module, the data set was tidied so that it excluded skaters who did not make it to the free skate round, were disqualified, or drop out of competition.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
Learning Objectives:

1. Students will learn how to detect outliers

2. Students will learn how about Standardized Residuals

3. Students will learn how about Leverage

4. Students will learn how about Cook's Distance

5. Students will learn how to determine an outlier's influence

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
For this activity, students will need to use R Studio. 

Students are expected to understand the concept of what an outlier is. There's also an expectation that they are able to make basic graphs in R using ggplot and write models in R.

This activity would be suitable for an in-class activity or as an out-of-class assignment taking approximately one class period.
:::



### Data

The menSkating data contains records of competitors from the 2006-2022 winter Olympics. 

Download data: ____ (link)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable        | Description                                    |
|-----------------|------------------------------------------------|
| Name            | Skater's Name                                  |
| Nation          | Nation representing Skater                     |
| FS/FS.1         | Free Skate Score                               |
| SP/SP.1         | Short Program score                            |
| TP/Total Points | Combined score of free skate and short program |
| Year            | Olympic Year                                   |
| Sex             | Gender of Skater                               |

</details>


### Materials

[Class handout]

[Class handout - with solutions]

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should gain an understanding of outlier detection and determining an outlier's influence. Students should be able to calculate Standardized Residual, Leverage, and Cook's Distance.
:::
