
```{r}
library(readr)
library(ggplot2)
library(dplyr)
```

Link to data from Reddit Thread: https://www.reddit.com/r/Fitness/comments/35q4i3/how_much_do_you_dumbbell_flat_bench_compared_to/

```{r}
weights_ratio <- read_csv("~/Desktop/weights_ratio.csv", col_names = TRUE)
View(weights_ratio)
```
```{r}
weights_ratio <- weights_ratio %>%
  mutate(
    Ratio = Ratio * 2
  )
```

```{r}
write_csv(weights_ratio,
          file = "~/GitHub/stat_289_score/vgjohn/weights_ratio.csv")
```

Data Exploration 

actual mean: 
```{r}
mean(weights_ratio$Ratio)
```

```{r}
plot1 <- ggplot(data = weights_ratio,
                mapping = aes(x = Ratio)) +
  geom_histogram(binwidth = 0.01, fill = "blue") +
  scale_x_continuous(limits = c(0,1), breaks = seq(0,1, by = 0.1))

plot1
```

making a 95% confidence interval for the mean ratio: between  0.6822360 0.7690974
```{r}
t.test(weights_ratio$Ratio)
```
99% confidence interval  0.6660064 0.7853269
```{r}
t.test(weights_ratio$Ratio, conf.level = 0.99)
```
```{r}
IQR(weights_ratio$Ratio)
```

```{r}
sum <- fivenum(x = weights_ratio$Ratio)
sum
```
```{r}
stdev <- sd(weights_ratio$Ratio)
stdev

mean <- mean(weights_ratio$Ratio)
mean
```

```{r}
summary_df <-
  data.frame(
    Statistic = c("Min", "Q1", "Median", "Q3", "Max", "Mean", "St. Dev"),
    Value = c(sum, mean, stdev)
  )

summary_df <- summary_df %>%
  mutate(
    Value = round(Value, 3)
  )
print(summary_df)
```
sum_transposed <- t(summary_df)
colnames(sum_transposed) <- summary_df$Statistic
sum_transposed <- as.data.frame(sum_transposed)
sum_transposed <- sum_transposed[-1,]
sum_transposed <- sum_transposed %>%

seems to follow a normal distribution
```{r}
nDist <- rnorm(weights_ratio$Ratio, mean = 0.7257, sd = 0.08733505)
hist(nDist, breaks = 10)
```

```{r}
library(ggplot2)
library(readr)
weights_ratio <- read.csv("~/GitHub/stat_289_score/vgjohn/weights_ratio/module/weights_ratio.csv")
ggplot(data = weights_ratio,
       mapping = aes(y = Ratio)) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, by = 0.1))+
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )
```
