---
title: "Data Description"
editor: visual
---

## Motivation

\
Over the years, lacrosse has experienced remarkable growth, with increased popularity and participation propelling the sport to new heights. This surge has led to a rise in skilled athletes competing in high-level leagues, notably NCAA Division I Men's Lacrosse. Within this heightened competition, faceoffs are known to be a vital aspect of the game. Due to their important impact, players train to specifically specialize in them, as winning a faceoff often grants their teams crucial opportunities for offensive possession which can profoundly impact the course of the game.

## Data

The data set contains 72 rows and 22 columns. Each row represents a lacrosse team at the NCAA Division 1 level from the 2022-2023 season.

\| Variable \| Description \| \|\-\-\--\|\-\-\-\-\-\-\-\-\-\-\-\-\-\--\|

\| Team \| college of the team \|

\| avg_assists \| average assists to goals per game \|

\| avg_caused_turnovers \| average turnovers forced by the team per game \|

\| clearing_pctg \| percentage of successful attempts to earn an offensive opportunity after gaining the ball in the teams own half \|

\| total_faceoffs \| total faceoffs taken by a team for the season \|

\| faceoff_wins \| total faceoff wins by a team for the season \|

\| faceoff_win_pct \| proportion of total faceoff wins out of total faceoffs \|

\| avg_goals \| average goals per game \|

\| avg_goals_allowed \| average goals allowed by the team per game \|

\| avg_ground_balls \| average loose balls picked up by the team per game \|

\| man_down_defense_pctg \| proportion of times a team stops the opponent from scoring while man down due to a penalty \|

\| man_up_offense_pctg \| proportion of times the offense scores out of total opportunities while man up \|

\| avg_scoring_margin \| average margin of goals per game \|

\| opp_clear_pctg \| opponents clearing percentage averaged by game \|

\| avg_points \| average team points per game \|

\| avg_saves \| average saves per game \|

\| shot_pctg \| proportion of shots that go in out of total shots \|

\| avg_turnovers \| average turnovers that are directly the fault of a player per game \|

\| W \| total wins by the team \|

\| L \| total losses by the team \|

\| win_loss_pctg \| proportion of games won out of total games \|

## Questions

Which teams have better faceoff win proportions than the average?

Which teams have worse faceoff win proportions than the average?

What sort of impact does faceoff percentage have on the success of the team?

## References

NCAA Website: Men's Lacrosse Division I

<http://stats.ncaa.org/rankings/change_sport_year_div>
