---
title: Women's Alpine Skiing World Cup GS Statistics
author: Emilia Agostinelli
date: February 29, 2024
description: Statistics from a two-run women's World Cup Giant Slalom race at Mont-Tremblant
categories:
  - Paired data
  - Difference in means
---

## Motivation

In World Cup Giant Slalom (GS), there are 30 racers and two runs. If a racer is disqualified (DSQ) or did not finish (DNF) their first run, they do not take a second run. The order for the first run is determined by taking the best seven competitors, based on their World Cup points, and randomly assigning them a bib 1-7. The next eight best competitors are randomly assigned a bib 8-15. The next best 15 racers are assigned bibs 16-30 in order of their points, from highest to lowest. For the second run, competitors race in reverse order of their times achieved on the first run, so slowest to fastest run time. Since this data includes information on 2 runs by the same competitor (unless they DSQ or DNF), it allows for exploration of paired data. It can also explore difference in means between the 2 runs to investigate if racers are on average faster/slower on a specific run.

## Data

Each of the 30 rows in this data set represents a racer. There are a few missing values in the Total, Pr, Run_2_Time, and Run_2_Rank columns due to racers not finishing their first run.

| Variable   | Description                                      |
|------------|--------------------------------------------------|
| Rank       | Final rankings of the race                       |
| Number     | Start order for the second run                   |
| Bib        | Start order for the first run                    |
| Name       | Name of the racer                                |
| Nat        | The country the racer represents                 |
| Total      | Combined time of both runs in seconds            |
| Pr         | The difference between run 1 rank and final rank |
| Run_1_Time | Time for run 1 in seconds                        |
| Run_1_Rank | Rankings of run 1                                |
| Run_2_Time | Time for run 2 in seconds                        |
| Run_2_Rank | Rankings of run 2                                |

: [Tremblant.csv](Tremblant.csv)

## Questions

A possible question that could be answered with this data set is, is there a significant difference in times between run 1 and run 2? Do racers get faster or slower after their first run? Or is there no difference? If there is a difference, what could account for that?

Some other questions could be formulated around correlation. For example, is run order for run 2 associated with final results?

## References

The data comes from the following link: https://live.fis-ski.com/lv-al5009.htm#/follow
