
```{r}
library(tidyverse)
```

```{r}
male <-
  read_csv(here::here("esselt21/hotdog_module/hotdog_male.csv"))

female <-
  read_csv(here::here("esselt21/hotdog_module/hotdog_female.csv"))

total <-
  read_csv(here::here("esselt21/hotdog_module/hotdog_total.csv"))
```

```{r}
model <- lm(HDB ~ BMI + Gender + dunkingEra, data = total)

summary(model)
```

```{r}
male |>
  ggplot(aes(x = as_factor(Year),
             y = HDB,
             fill = dunkingEra)) +
  geom_col(alpha = 0.5) +
  theme_minimal() +
  coord_flip() +
  labs(fill = "Buns Dunked?",
       x = "Year of Contest",
       y = "Hot Dogs and Buns Eaten",
       title = "Winning Number of Hot Dogs Eaten")
```


```{r}
avg_ratio <-
  male |>
  group_by(Winner) |>
  summarise(avg_ratio = mean(bmi_dog_ratio))

female_ratio <-
  female |>
  group_by(Winner) |>
  summarise(avg_ratio = mean(bmi_dog_ratio))

avg_ratio <-
  bind_rows(avg_ratio,
            femalef)

avg_ratio |>
  ggplot(aes(x = reorder(Winner, avg_ratio),
             y = avg_ratio,
             fill = Winner)) +
  geom_col(alpha = 0.6) +
  theme_minimal() +
  coord_flip() +
  theme(legend.position = "none")
```


```{r}
library(png)
library(grid)
img <- readPNG(system.file("img", "hotdog.png", package="png"))
g <- rasterGrob(img, interpolate=TRUE)

```

```{r}

```

```{r}
library(ggplot2)
library(cowplot)
library(magick)

theme_set(theme_cowplot())

my_plot <- 
  total |>
  ggplot(aes(x = Height)) +
  geom_dotplot(fill = "white",
               color = "black") +
  theme_minimal() 

# Example with PNG (for fun, the OP's avatar - I love the raccoon)
ggdraw() +
  draw_image("https://thumbs.dreamstime.com/b/hot-dog-mustard-hand-drawing-delicious-classic-american-drawn-vector-illustration-isolated-white-background-146434962.jpg") +
  draw_plot(my_plot)
```


