---
title: "Olympic Figure Skating Scoring 2006-2022"
author: "Faith Rhinehart" 
date: "June 12, 2025" 
format: html
categories:
  - ANOVA
  - Post Hoc Tukey Test
  - Confidence Interval
  - Log Transformations
  - Model Building
  - Two-Way Anova Interaction
  - Pair-Wise Comparisons 
---

## Motivation

Figure skating is a sport where individuals, pairs, or groups preform with music on ice skates. Performing various tricks such as jumps, spins, and footwork showcases a combination of athleticism and artistry. Figure skating was the first winter sport to be in included in the Olympic Games in 1908. 

In the Olympics, athletes first performs a Short Program that lasts 2 minutes and 40 seconds. The Short Program is designed to highlight the skaters' technical skills and artistry since they must perform specific required elements. After the Short Program, skaters perform the Free Skate which last 1 to 4.5 minutes. The Free Skate allows for more creativity as Skaters' can choose from a variety of elements to create their performance. The programs are scored by combining two main parts: the Technical Score, which evaluates the difficulty and execution of jumps, spins, and footwork, and the Program Components Score, which judges artistry, choreography, and interpretation. Points can be deducted for mistakes like falls. The combination of the Short Program score and Free Skate score gets added up into a total score which determines the winner. 

## Data

The dataset provided (male and female skaters' winter Olympic scores since 2006 with demographic information) was scraped from Wikipedia (see references for links). 

::: {.callout-note collapse="true" title="Tidying Process"}

This process was used to make the dataset
- **Copied and pasted the data set into Excel**
  - Added a year variable to indicate the year of Olympics
  - Added a sex variable to indicate the gender of skater

- **Sliced the full data set** to exclude:                                 
  - Skaters' who did not advance to free skate      

:::


<details>
<summary><strong>Variable Descriptions</strong></summary>

Olympics since 2006 Men's (7 variables and 120 cases) and Women's (6 variables and 120 cases) data:

| Variable        | Description                                    |
|-----------------|------------------------------------------------|
| Rank            | Place of Skater in Competition (Men's only)    |
| Name            | Skater's Name                                  |
| Nation          | Nation Skater is representing                  |
| FS              | Free Skate Score                               |
| SP              | Short Program Score                            |
| TP              | Combined score of free skate and short program |
| Year            | Olympic Year                                   |
                       
</details>

Download Men's Data:  [MensFigureSkating.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Olympic Figure Skating/MensFigureSkating.csv)

Download Women's Data:  [womensFigureSkating.csv](C:/Users/0211f/GitHub/slu_score_module_development/frhinehart/Olympic Figure Skating/womensFigureSkating.csv)

## Questions Investigated
1. Is there a significant difference in mean scores throughout the different years of the Winter Olympics?
2. Which specific years have a significant difference in mean scores?
3. Can we use year to predict total points?
4. Can we use short program score to predict free skate score?
5. Is there a main effect of year and sex on total points and is there an interaction effect?

## References

Data was scraped from Wikipedia:

[Menskate2006](https://en.wikipedia.org/wiki/Figure_skating_at_the_2006_Winter_Olympics_%E2%80%93_Men's_singles){   }
[Menskate2010](https://en.wikipedia.org/wiki/Figure_skating_at_the_2010_Winter_Olympics_%E2%80%93_Men's_singles){   }
[Menskate2014](https://en.wikipedia.org/wiki/Figure_skating_at_the_2014_Winter_Olympics_%E2%80%93_Men's_singles){   }
[Menskate2018](https://en.wikipedia.org/wiki/Figure_skating_at_the_2018_Winter_Olympics_%E2%80%93_Men's_singles){   }
[Menskate2022](https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Men's_singles){   }

[Womenskate2006](https://en.wikipedia.org/wiki/Figure_skating_at_the_2006_Winter_Olympics_%E2%80%93_Ladies%27_singles){   }
[Womenskate2010](https://en.wikipedia.org/wiki/Figure_skating_at_the_2010_Winter_Olympics_%E2%80%93_Ladies%27_singles){   }
[Womenskate2014](https://en.wikipedia.org/wiki/Figure_skating_at_the_2014_Winter_Olympics_%E2%80%93_Ladies%27_singles){   }
[Womenskate2018](https://en.wikipedia.org/wiki/Figure_skating_at_the_2018_Winter_Olympics_%E2%80%93_Ladies%27_singles){   }
[Womenskate2022](https://en.wikipedia.org/wiki/Figure_skating_at_the_2022_Winter_Olympics_%E2%80%93_Women%27s_singles){   }

Video was linked from YouTube:

<iframe width="560" height="315" src="https://www.youtube.com/embed/i6pw07k3GkM?si=ud_nUmub-iDQ_cAm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
