---
title: "euros_exploration"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
```

```{r}
eurosClean <- read_csv(here::here("esselt21/euros_module/exploration/eurosClean.csv"))
```

# Cleaning data
```{r}
# getting rid of duplicates
eurosClean <-
  euros |>
  select(-c(`Away Accurate passes...28`, `Away Accurate passes...68`, `Away Total shots.`, `Away Expected goals (xG)`, `Away Shots on target.`, `Away Expected goals (xG)`, `Away Shots on target.`, `Away Shots on target.`))
```

```{r}
# separations
eurosClean <-
  eurosClean |>
  separate(`Away Accurate passes...12`,
           into = c("Away Accurate passes", "Away Accurate passes %"),
           sep = 3) |>
  separate(`Away Accurate long balls`,
           into = c("Away Accurate long balls", "Away Accurate long balls %"),
           sep = 2) |>
  separate(`Away Accurate crosses`,
           into = c("Away Accurate crosses", "Away Accurate crosses %"),
           sep = 2) |>
  separate(`Away Tackles won`,
           into = c("Away Tackles won", "Away Tackles won %"),
           sep = 2) |>
  separate(`Away Ground duels won`,
           into = c("Away Ground duels won", "Away Ground duels won %"),
           sep = 2) |>
  separate(`Away Aerial duels won`,
           into = c("Away Aerial duels won", "Away Aerial duels won %"),
           sep = 2) |>
  separate(`Away Successful dribbles`,
           into = c("Away Successful dribbles", "Away Successful dribbles %"),
           sep = 2)
```

```{r}
# Parsing Numbers
eurosClean <-
  eurosClean |>
  mutate(`Away Accurate passes` = parse_number(`Away Accurate passes`),
         `Away Accurate passes %` = parse_number(`Away Accurate passes %`),
         `Away Accurate long balls` = parse_number(`Away Accurate long balls`),
         `Away Accurate long balls %` = parse_number(`Away Accurate long balls %`),
         `Away Accurate crosses` = parse_number(`Away Accurate crosses`),
         `Away Accurate crosses %` = parse_number(`Away Accurate crosses %`),
         `Away Tackles won` = parse_number(`Away Tackles won`),
         `Away Tackles won %` = parse_number(`Away Tackles won %`),
         `Away Ground duels won` = parse_number(`Away Ground duels won`),
         `Away Ground duels won %` = parse_number(`Away Ground duels won %`),
         `Away Aerial duels won` = parse_number(`Away Aerial duels won`),
         `Away Aerial duels won %` = parse_number(`Away Aerial duels won %`),
         `Away Successful dribbles` = parse_number(`Away Successful dribbles`),
         `Away Successful dribbles %` = parse_number(`Away Successful dribbles %`))
```

```{r}
# separations
eurosClean <-
  eurosClean |>
  separate(`Away Accurate passes...52`,
           into = c("Away Accurate passes", "Away Accurate passes %"),
           sep = 3) |>
  separate(`Away Accurate long balls`,
           into = c("Away Accurate long balls", "Away Accurate long balls %"),
           sep = 2) |>
  separate(`Away Accurate crosses`,
           into = c("Away Accurate crosses", "Away Accurate crosses %"),
           sep = 2) |>
  separate(`Away Tackles won`,
           into = c("Away Tackles won", "Away Tackles won %"),
           sep = 2) |>
  separate(`Away Ground duels won`,
           into = c("Away Ground duels won", "Away Ground duels won %"),
           sep = 2) |>
  separate(`Away Aerial duels won`,
           into = c("Away Aerial duels won", "Away Aerial duels won %"),
           sep = 2) |>
  separate(`Away Successful dribbles`,
           into = c("Away Successful dribbles", "Away Successful dribbles %"),
           sep = 2)
```

```{r}
# Parsing Numbers
eurosClean <-
  eurosClean |>
  mutate(`Away Accurate passes` = parse_number(`Away Accurate passes`),
         `Away Accurate passes %` = parse_number(`Away Accurate passes %`),
         `Away Accurate long balls` = parse_number(`Away Accurate long balls`),
         `Away Accurate long balls %` = parse_number(`Away Accurate long balls %`),
         `Away Accurate crosses` = parse_number(`Away Accurate crosses`),
         `Away Accurate crosses %` = parse_number(`Away Accurate crosses %`),
         `Away Tackles won` = parse_number(`Away Tackles won`),
         `Away Tackles won %` = parse_number(`Away Tackles won %`),
         `Away Ground duels won` = parse_number(`Away Ground duels won`),
         `Away Ground duels won %` = parse_number(`Away Ground duels won %`),
         `Away Aerial duels won` = parse_number(`Away Aerial duels won`),
         `Away Aerial duels won %` = parse_number(`Away Aerial duels won %`),
         `Away Successful dribbles` = parse_number(`Away Successful dribbles`),
         `Away Successful dribbles %` = parse_number(`Away Successful dribbles %`))
```

```{r}
# renaming all variables
eurosClean <-
  eurosClean |>
  rename("h_xG" = `Home Expected goals(xG)`,
         "h_TS" = `Home Total shots`,
         "h_SOT" = `Home Shots on target`,
         "h_BC" = `Home Big chances`,
         "h_BCM" = `Home Big chances missed`,
         "h_AP" = `Home Accurate passes`,
         "h_AP%" = `Home Accurate passes %`,
         "h_FC" = `Home Fouls committed`,
         "h_C" = `Home Corners`,
         "h_SOFFT" = `Home Shots off target`,
         "h_BS" = `Home Blocked shots`,
         "h_HW" = `Home Hit woodwork`,
         "h_SIB" = `Home Shots inside box`,
         "h_SOB" = `Home Shots outside box`,
         "h_xGOP" = `Home xG open play`,
         "h_xGSP" = `Home xG set play`,
         "h_npxG" = `Home Non-penalty xG`,
         "h_xGOT" = `Home xG on target (xGOT)`,
         "h_P" = `Home Passes`,
         "h_OHP" = `Home Own half`,
         "h_OPHP" = `Home Opposition half`,
         "h_ALB" = `Home Accurate long balls`,
         "h_ALB%" = `Home Accurate long balls %`,
         "h_AC" = `Home Accurate crosses`,
         "h_AC%" = `Home Accurate crosses %`,
         "h_Throws" = `Home Throws`,
         "h_TouchOB" = `Home Touches in opposition box`,
         "h_OFF" = `Home Offsides`,
         "h_YC" = `Home Yellow cards`,
         "h_RC" = `Home Red cards`,
         "h_TW" = `Home Tackles won`,
         "h_TW%" = `Home Tackles won %`,
         "h_INT" = `Home Interceptions`,
         "h_B" = `Home Blocks`,
         "h_CL" = `Home Clearances`,
         "h_KS" = `Home Keeper saves`,
         "h_DW" = `Home Duels won`,
         "h_GDW" = `Home Ground duels won`,
         "h_GDW%" = `Home Ground duels won %`,
         "h_ADW" = `Home Aerial duels won`,
         "h_ADW%" = `Home Aerial duels won %`,
         "h_SD" = `Home Successful dribbles`,
         "h_SD%" = `Home Successful dribbles %`)
```

```{r}
# renaming variables part 2
eurosClean <-
  eurosClean |>
  rename("a_xG" = `Away Expected goals(xG)`,
         "a_TS" = `Away Total shots`,
         "a_SOT" = `Away Shots on target`,
         "a_BC" = `Away Big chances`,
         "a_BCM" = `Away Big chances missed`,
         "a_AP" = `Away Accurate passes`,
         "a_AP%" = `Away Accurate passes %`,
         "a_FC" = `Away Fouls committed`,
         "a_C" = `Away Corners`,
         "a_SOFFT" = `Away Shots off target`,
         "a_BS" = `Away Blocked shots`,
         "a_HW" = `Away Hit woodwork`,
         "a_SIB" = `Away Shots inside box`,
         "a_SOB" = `Away Shots outside box`,
         "a_xGOP" = `Away xG open play`,
         "a_xGSP" = `Away xG set play`,
         "a_npxG" = `Away Non-penalty xG`,
         "a_xGOT" = `Away xG on target (xGOT)`,
         "a_P" = `Away Passes`,
         "a_OHP" = `Away Own half`,
         "a_OPHP" = `Away Opposition half`,
         "a_ALB" = `Away Accurate long balls`,
         "a_ALB%" = `Away Accurate long balls %`,
         "a_AC" = `Away Accurate crosses`,
         "a_AC%" = `Away Accurate crosses %`,
         "a_Throws" = `Away Throws`,
         "a_TouchOB" = `Away Touches in opposition box`,
         "a_OFF" = `Away Offsides`,
         "a_YC" = `Away Yellow cards`,
         "a_RC" = `Away Red cards`,
         "a_TW" = `Away Tackles won`,
         "a_TW%" = `Away Tackles won %`,
         "a_INT" = `Away Interceptions`,
         "a_B" = `Away Blocks`,
         "a_CL" = `Away Clearances`,
         "a_KS" = `Away Keeper saves`,
         "a_DW" = `Away Duels won`,
         "a_GDW" = `Away Ground duels won`,
         "a_GDW%" = `Away Ground duels won %`,
         "a_ADW" = `Away Aerial duels won`,
         "a_ADW%" = `Away Aerial duels won %`,
         "a_SD" = `Away Successful dribbles`,
         "a_SD%" = `Away Successful dribbles %`)
```

```{r}
# renaming part 3
eurosClean <-
  eurosClean |>
  rename("h_country" = home_team,
         "a_country" = away_team,
         "h_goals" = home_goals,
         "a_goals" = away_goals)
```

```{r}
write_csv(eurosClean, here::here("esselt21/euros_module/exploration/eurosClean.csv"))
```

```{r}
# exploration, who had the most goals
home <-
  eurosClean |>
  group_by(home_team) |>
  summarise(homeGoals = sum(home_goals)) |>
  arrange(desc(homeGoals))

away <-
  eurosClean |>
  group_by(away_team) |>
  summarise(awayGoals = sum(away_goals)) |>
  arrange(desc(awayGoals))

goals <-
  left_join(home,
            away,
            by = c("home_team" = "away_team"))

goals <-
  goals |>
  mutate(goals = homeGoals + awayGoals) |>
  rename("Country" = home_team) |>
  select(Country, goals)
```

```{r}
# who had the most expected goals
home <-
  eurosClean |>
  group_by(home_team) |>
  summarise(homexG = sum(`Home Expected goals(xG)`))

away <-
  eurosClean |>
  group_by(away_team) |>
  summarise(awayxG = sum(`Away Expected goals(xG)`))

xG <-
  left_join(home,
            away,
            by = c("home_team" = "away_team"))

xG <-
  xG |>
  mutate(xG = homexG + awayxG) |>
  rename("Country" = home_team) |>
  select(Country, xG)
```

```{r}
# joining xG and goals
goals_xG <-
  left_join(goals,
            xG,
            by = c("Country"))
```

```{r}
# adding a winner variable
eurosClean <-
  eurosClean |>
  mutate(HomeWin = if_else(home_goals > away_goals, "W", if_else(home_goals < away_goals, "L", "D")))

eurosClean <-
  eurosClean |>
  mutate()
  relocate(HomeWin, .after = away_goals)
  
eurosClean <-
  eurosClean |>
  mutate(totalGoals = home_goals + away_goals,
         totalxG = `Home Expected goals(xG)` + `Away Expected goals(xG)`)
```

```{r}
ggplot(data = eurosClean,
       aes(x = totalGoals)) +
  geom_dotplot(fill = "ivory",
               color = "black") +
  theme_minimal()

ggplot(data = eurosClean,
       aes(x = totalxG)) +
  geom_histogram(fill = "ivory",
                 color = "black",
                 binwidth = .5) +
  geom_dotplot(aes(x = totalGoals),
               fill = "cyan",
               alpha = 0.5) +
  theme_minimal()
```

```{r}
# who missed the most big chances
home <-
  eurosClean |>
  group_by(home_team) |>
  summarise(homeMissed = sum(`Home Big chances missed`))

away <-
  eurosClean |>
  group_by(away_team) |>
  summarise(awayMissed = sum(`Away Big chances missed`))

missedChances <-
  left_join(home,
            away,
            by = c("home_team" = "away_team"))

missedChances <-
  missedChances |>
  mutate(missedChances = homeMissed + awayMissed) |>
  rename("Country" = home_team) |>
  select(Country, missedChances)
```

```{r}
# who had the most average attendance
home <-
  eurosClean |>
  group_by(home_team) |>
  summarise(homeAttendance = mean(attendance))

away <-
  eurosClean |>
  group_by(away_team) |>
  summarise(awayAttendance = mean(attendance))

attendance <-
  left_join(home,
            away,
            by = c("home_team" = "away_team"))

attendance <-
  attendance |>
  mutate(averageAttendance = (homeAttendance + awayAttendance) / 2) |>
  rename("Country" = home_team) |>
  select(Country, averageAttendance)
```

