---
title: Mapping NFL Stadium Locations
author: Eric Seltzer
date: July 22, 2024
description: Data of the coordinates of NFL Stadiums, as well as the attendance numbers for each NFL Stadium.
categories:
  - Mapping
  - Visualization
editor:
  markdown: 
    canonical: true
---

## Motivation

The first data set is provided by Logan Donaldson on Kaggle. It contains the latitude and longitude data of every stadium in the MLB, NFL, NBA, NHL, and MLS. The second data set is provided by Sujay Kapadnis, it contains the total attendance for NFL teams, the home attendance, away attendance, and weekly attendance.

## Data

### Stadiums

This data is made up of 32 rows and 7 columns. Each row represents a different NFL team and the stadium that they play at.

| Variable          | Description                                |
|-------------------|--------------------------------------------|
| Team              | The name of the team                       |
| League            | What league the team plays in              |
| Division          | What division the team plays in            |
| Lat               | The latitude of the stadium                |
| Long              | The longitude of the stadium               |
| total             | The total team attendance for the season   |
| averageAttendance | The average team attendance for the season |

: [stadiums.csv](../data/stadiums.csv)

### Attendance

This data set has 10,846 rows and 8 variables. It contains data on each team from 2000-2019 and shows their attendance numbers both as totals and weekly.

| Variable          | Description                               |
|-------------------|-------------------------------------------|
| team_name         | The name of the team                      |
| year              | What year the season is from              |
| total             | The total attendance for that season      |
| home              | The total home attendance for that season |
| away              | The total away attendance for that season |
| week              | The week of the season                    |
| weekly_attendance | The attendance for the given week         |

: [attendance.csv](../data/attendance.csv)

## Questions

Insert later

## References

Logan Donaldson, *Sports Stadium Locations*. <https://www.kaggle.com/datasets/logandonaldson/sports-stadium-locations>.

Sujay Kapadnis, *NFL Stadium Attendance*. <https://www.kaggle.com/datasets/sujaykapadnis/nfl-stadium-attendance-dataset>.
