---
title: "Short Track Speed Skating"
author:
  - name: Gavin Cassidy
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: 
    email: 
    affiliation:
      - ref: slu
date: June 13, 2024
description: Speed Skating
categories:
---

## Modules

### Introduction

Speed Skating is a competition where athletes see who can complete a distance in the shortest amount of time. The two styles of speed skating are short track and long track. Long track speed skating gives athletes separate lanes on a 400m track and compare times from each different heat to decide a winner. Short track speed skating is contested on a 111m track with 4-6 skaters competing at the same time. This data set looks at a collection of 500m races which consist of 4 1/2 action packed laps with athletes bumping and nudging each other around every turn. Short track speed skating tends to be very contact heavy and crowded, leading to some chaotic races and dangerous crashes.

Short Track Speed Skating hold several high profile events each season, with the World Cup consisting of a series of events with a point series, the European Championships, the World Championships, and every 4 years the Olympic Games. 

### Data

The Short Track Speed Skating data set contains 5125 rows and 28 columns, where each row is 1 race performance from an athlete at either the European Championship, World Cup, World Championship, or Olympics. Each row includes lap times and placements, as well as location, round, qualification status, and other data. This data set contains each race from the 2012/13 season up to the end of 2016 in the 2016/17 season. The list of variables is in the table below:

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable       | Description                                                                     |
|-------------------------|-----------------------------------------------|
| Season         | the season the race occurred during, ex. 2015/2016                              |
| Series         | the type of event, ex. World Championships                                      |
| City           | the city where the event is located                                             |
| Country        | the abbreviation of the country where event is located                          |
| Year           | the year of the event                                                           |
| Month          | the month of the event                                                          |
| Day            | the day of the event                                                            |
| Distance       | the distance (500m for all)                                                     |
| Round          | the round that the race occurred during                                         |
| Group          | the group of the racer for the particular round                                 |
| Num_Skater     | the number of the skater for the event                                          |
| Name           | the name of the skater                                                          |
| Nationality    | the nationality of the skater                                                   |
| Rank_In_Group  | the rank of the skater in their race                                            |
| Start_Position | the position on the track where the skater started, 1 is on the inside          |
| Time           | the time of the skater                                                          |
| Qualification  | the qualification status of the racer for their race, included penalties        |
| rank_lap1      | the rank of the racer after lap 1 (lap 1 is the first half lap)                 |
| time_lap1      | the time of the racer after lap 1 (lap 1 is the first half lap)                 |
| rank_lap2      | the rank of the racer after lap 2 (laps after 1 are tracked on the finish line) |
| time_lap2      | the rank of the racer after lap 2                                               |
| rank_lap3      | the rank of the racer after lap 3                                               |
| time_lap3      | the time of the racer after lap 3                                               |
| rank_lap4      | the rank of the racer after lap 4                                               |
| time_lap4      | the time of the racer after lap 4                                               |
| rank_lap5      | the rank of the racer after lap 5                                               |
| time_lap5      | the time of the racer after lap 5                                               |
| Time_Event     | the date of event expressed as year followed by a decimal month and day         |

Data File: [short_track.csv](../data/short_track.csv)

### Materials
