---
title: "new_data_exploration"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
```

```{r}
atp <- read_csv(here::here("esselt21/tennis_module/exploration/atp_2023.csv"))
```

```{r}
# creating win percentages
GSwinPercentage <-
  atp |>
  group_by(player, best_of) |>
  summarise(winPct = mean(result == "Winner"),
            matches = n()) |>
  mutate(best_of = as_factor(best_of),
         best_of = fct_recode(best_of, "Non-Grand Slam" = "3", "Grand Slam" = "5"))

winPercentage <-
  atp |>
  group_by(player, surface) |>
  summarise(winPct = mean(result == "Winner"),
            matches = n()) |>
  filter(matches >= 5) |>
  mutate(surface = as_factor(surface),
         surface = fct_relevel(surface, c("Clay", "Grass", "Hard")))
```

```{r}
# histogram of win percentage by surface
winPercentage |>
  ggplot(aes(x = winPct,
             y = after_stat(density))) +
  geom_histogram(fill = 'lightblue',
                 color = 'black',
                 bins = 15) +
  facet_grid(~surface) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = 'white'),
        panel.background = element_rect(fill = 'white'),
        strip.background = element_rect(colour = 'black',
                                        fill = 'gray90'),
        strip.text = element_text(size = 15,
                                  face = 'bold'),
        plot.caption = element_text(size = 20,
                                    face = 'bold'),
        plot.title = element_text(size = 20)) +
  labs(x = 'Win Percentage',
       y = 'Density',
       title = 'Histogram of Win Percentages by Surface',
       caption = "ATP")
```

```{r}
# five number summary and standard deviation
cWPercentage <-
  winPercentage |>
  filter(surface == 'Clay') |>
  pull(winPct)

gWPercentage <-
  winPercentage |>
  filter(surface == 'Grass') |>
  pull(winPct)

hWPercentage <-
  winPercentage |>
  filter(surface == 'Hard') |>
  pull(winPct)

claySummary <- summary(cWPercentage)
hardSummary <- summary(hWPercentage)
grassSummary <- summary(gWPercentage)

claySummary
grassSummary
hardSummary
```

```{r}
# box plot of win percentage by surface
winPercentage |>
  ggplot(aes(x = surface,
             y = winPct,
             fill = surface)) +
  stat_boxplot(geom = 'errorbar') +
  geom_boxplot() +
  theme_minimal() +
  theme(panel.background = element_rect(fill = 'white'),
        plot.background = element_rect(fill = 'white'),
        plot.title = element_text(size = 20,
                                  hjust = 0.5),
        plot.caption = element_text(size = 20,
                                    face = 'bold'),
        legend.position = 'none') +
  labs(x = 'Best Of',
       y = 'Win Percentage',
       title = 'Side-by-side Box Plots of Win Percentage',
       caption = 'ATP')
```

```{r}
# bee swarm plot of win percentage by type of tournament
library(ggbeeswarm)

GSwinPercentage |>
  ggplot(aes(x = best_of,
             y = winPct,
             color = best_of)) +
  geom_beeswarm(cex = 3) +
  labs(x = "Best Of",
       y = "Win Percentage",
       title = "Bee Swarm Plot of Win Percentages by Grand Slam or Not",
       caption = "ATP") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = 'white'),
        panel.background = element_rect(fill = 'white'),
        plot.caption = element_text(size = 20,
                                    face = 'bold'),
        legend.position = "none")
```

