---
title: "tennis-testing"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
library(ggplot2)
library(broom)
library(modelr)
```

```{r}
men <- read_csv(here::here("esselt21/tennis_module/exploration/men.csv"))
```

```{r}
men <-
  men |>
  filter(Surface != "All")

names <-
  men |>
  group_by(Player) |>
  summarise(n = n()) |>
  filter(n == 3) |>
  pull(Player)

men <-
  men |>
  filter(Player %in% names)
```

```{r}
# check win percentage distribution, what is the shape, center, and spread, is there a a big difference between the three surfaces?
men |>
  ggplot(aes(x = WinPercentage)) +
  geom_histogram(colour = "black",
                 fill = "lightblue",
                 bins = 23,
                 aes(y=..density..)) +
  theme_minimal() +
  labs(x = "Win Percentage",
       title = "Histogram of Win Percentages by Surface",
       y = "Density") +
  facet_grid(~Surface,
             scales = "free") +
  theme(
    axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   vjust = 1),
    plot.title = element_text(hjust = .5)
  )
```

```{r}
# five number summary and standard deviation
cWPercentage <-
  men |>
  filter(Surface == 'Clay') |>
  pull(WinPercentage)

hWPercentage <-
  men |>
  filter(Surface == 'Hard') |>
  pull(WinPercentage)

gWPercentage <-
  men |>
  filter(Surface == 'Grass') |>
  pull(WinPercentage)

claySummary <- summary(cWPercentage)
hardSummary <- summary(hWPercentage)
grassSummary <- summary(gWPercentage)

claySummary
grassSummary
hardSummary
```

```{r}
men |>
  group_by(Surface) |>
  summarise(N = n())
```

```{r}
# approximate the median, iqr, and range for each surface
men |>
  ggplot(aes(x = Surface,
             y = WinPercentage,
             fill = Surface)) +
  stat_boxplot(geom = 'errorbar') +
  geom_boxplot() +
  theme_minimal() +
  labs(y = "Win Percentage",
       title = "Box Plots of Win Percentages by Surface") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))
```



```{r}
# regression test to see difference
model <- lm(WinPercentage ~ Surface + ReturnPointsWonPercentage + EloRank,
            data = tennis)
summary(model)
aug <-
  augment(model)
```

```{r}
# plotting regression model
aug |>
  ggplot(aes(x = ReturnPointsWonPercentage,
             y = .fitted,
             colour = Surface)) +
  geom_smooth(method = 'lm',
              se = FALSE) +
  geom_point(data = tennis,
             aes(x = ReturnPointsWonPercentage,
                 y = WinPercentage),
             alpha = 0.4) +
  theme_minimal() +
  labs(y = 'Win Percentage',
       x = 'Return Points Won Percentage',
       title = 'Predictions vs. Actual Values of Win Percentages')
```

```{r}
# does this meet the assumptions for a multiple linear regression model?
plot(model)
```

```{r}
women <- read_csv(here::here("esselt21/tennis_module/exploration/women.csv"))
```

```{r}
women <-
  women |>
  filter(Surface != "All") |>
  filter(Player %in% names)
```

```{r}
names <-
  women |>
  group_by(Player) |>
  summarise(n = n()) |>
  filter(n == 3) |>
  pull(Player) 
```

```{r}
women |>
  ggplot(aes(x = Matches,
             y = WinPercentage,
             color = Surface)) +
  geom_jitter() +
  geom_smooth() +
  labs(title = "Women") +
  facet_grid(~Surface,
             scales = "free_x")
```

```{r}
men <- read_csv(here::here("esselt21/tennis_module/exploration/men.csv"))
```

```{r}
men <-
  men |>
  filter(Surface != "All" & EloRank <= 100)
```

```{r}
men |>
  ggplot(aes(x = Matches,
             y = WinPercentage,
             colour = Surface)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Men") +
  facet_grid(~Surface)
```

```{r}
women |>
  ggplot(aes(x = Surface,
             y = WinPercentage,
             fill = Surface)) +
  stat_boxplot(geom = 'errorbar') +
  geom_boxplot() +
  theme_minimal() +
  labs(y = "Win Percentage",
       title = "Box Plots of Win Percentages by Surface") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))
```

```{r}
men |>
  ggplot(aes(x = Surface,
             y = WinPercentage,
             fill = Surface)) +
  stat_boxplot(geom = 'errorbar') +
  geom_boxplot() +
  theme_minimal() +
  labs(y = "Win Percentage",
       title = "Box Plots of Win Percentages by Surface") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))
```

```{r}
eliteModel <- lm(WinPercentage ~ Surface + ReturnPointsWonPercentage + EloRank,
            data = elite)

summary(eliteModel)

eliteAug <-
  augment(eliteModel)
```

```{r}
# plotting regression model
eliteAug |>
  ggplot(aes(x = ReturnPointsWonPercentage,
             y = .fitted,
             colour = Surface)) +
  geom_smooth(method = 'lm',
              se = FALSE) +
  geom_point(data = elite,
             aes(x = ReturnPointsWonPercentage,
                 y = WinPercentage),
             alpha = 0.4) +
  theme_minimal() +
  labs(y = 'Win Percentage',
       x = 'Return Points Won Percentage',
       title = 'Predictions vs. Actual Values of Win Percentages',
       subtitle = 'Only top 20 ranked players included')
# talk about differences between overall and elite players
```


