---
title: "Joining"
format: html
editor: visual
---

Load Canoe Data
```{r}
library(readr)
event_101_leg_5_results <- read_csv("sampeacock23/canoe_results/event_101_leg_5_results.csv")
event_102_leg_12_results <- read_csv("sampeacock23/canoe_results/event_102_leg_12_results.csv")
event_103_leg_19_results <- read_csv("sampeacock23/canoe_results/event_103_leg_19_results.csv")
event_104_leg_26_results <- read_csv("sampeacock23/canoe_results/event_104_leg_26_results.csv")
event_105_leg_33_results <- read_csv("sampeacock23/canoe_results/event_105_leg_33_results.csv")
event_106_leg_40_results <- read_csv("sampeacock23/canoe_results/event_106_leg_40_results.csv")
event_107_leg_47_results <- read_csv("sampeacock23/canoe_results/event_107_leg_47_results.csv")
event_108_leg_54_results <- read_csv("sampeacock23/canoe_results/event_108_leg_54_results.csv")
event_109_leg_61_results <- read_csv("sampeacock23/canoe_results/event_109_leg_61_results.csv")
event_110_leg_68_results <- read_csv("sampeacock23/canoe_results/event_110_leg_68_results.csv")
event_111_leg_75_results <- read_csv("sampeacock23/canoe_results/event_111_leg_75_results.csv")
```

Load Downhill Data
```{r}
event_101_leg_2_results <- read_csv("sampeacock23/downhill_results/event_101_leg_2_results.csv")
event_102_leg_9_results <- read_csv("sampeacock23/downhill_results/event_102_leg_9_results.csv")
event_103_leg_16_results <- read_csv("sampeacock23/downhill_results/event_103_leg_16_results.csv")
event_104_leg_23_results <- read_csv("sampeacock23/downhill_results/event_104_leg_23_results.csv")
event_105_leg_30_results <- read_csv("sampeacock23/downhill_results/event_105_leg_30_results.csv")
event_106_leg_37_results <- read_csv("sampeacock23/downhill_results/event_106_leg_37_results.csv")
event_107_leg_44_results <- read_csv("sampeacock23/downhill_results/event_107_leg_44_results.csv")
event_108_leg_51_results <- read_csv("sampeacock23/downhill_results/event_108_leg_51_results.csv")
event_109_leg_58_results <- read_csv("sampeacock23/downhill_results/event_109_leg_58_results.csv")
event_110_leg_65_results <- read_csv("sampeacock23/downhill_results/event_110_leg_65_results.csv")
event_111_leg_72_results <- read_csv("sampeacock23/downhill_results/event_111_leg_72_results.csv")
```

Load Kayak Data
```{r}
event_101_leg_7_results <- read_csv("sampeacock23/kayak_results/event_101_leg_7_results.csv")
event_102_leg_14_results <- read_csv("sampeacock23/kayak_results/event_102_leg_14_results.csv")
event_103_leg_21_results <- read_csv("sampeacock23/kayak_results/event_103_leg_21_results.csv")
event_104_leg_28_results <- read_csv("sampeacock23/kayak_results/event_104_leg_28_results.csv")
event_105_leg_35_results <- read_csv("sampeacock23/kayak_results/event_105_leg_35_results.csv")
event_106_leg_42_results <- read_csv("sampeacock23/kayak_results/event_106_leg_42_results.csv")
event_107_leg_49_results <- read_csv("sampeacock23/kayak_results/event_107_leg_49_results.csv")
event_108_leg_56_results <- read_csv("sampeacock23/kayak_results/event_108_leg_56_results.csv")
event_109_leg_63_results <- read_csv("sampeacock23/kayak_results/event_109_leg_63_results.csv")
event_110_leg_70_results <- read_csv("sampeacock23/kayak_results/event_110_leg_70_results.csv")
event_111_leg_77_results <- read_csv("sampeacock23/kayak_results/event_111_leg_77_results.csv")
```

