---
title: "Ski to Sea: Working File"
format: html
editor: visual
---

Scraping data from Ski to Sea

```{r}
library(rvest)
```

Overall 2019

```{r}
## provide the URL and name it something (in this case, url).
url <- "https://skitosea.pacificmultisports.com/events/111/results"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h %>% html_nodes("table")

#
test <- tab %>% html_table()

overall_2019 <- test[[1]]
```

XC Skiing 2019

```{r}
## provide the URL and name it something (in this case, url).
url <- "https://skitosea.pacificmultisports.com/events/111/results/leg/71"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h %>% html_nodes("table")

#
test <- tab %>% html_table()

#
xc_ski_2019 <- test[[1]]
```

While Loop

```{r}
library(rvest)
library(dplyr)
library(httr)

base_url <- "https://skitosea.pacificmultisports.com/events/"
event <- 101
isEvent <- TRUE

while (isEvent) {
  url <- paste0(base_url, event, "/results")
  response <- GET(url)
  if (response$status_code == 200) {
    
    # scrape the data
    h <- read_html(url)
    tab <- h %>% html_nodes("table")
    test <- tab %>% html_table()
    data <- test[[1]]
    
    # save the data to a CSV file
    write.csv(data, file = paste0("sampeacock23/overall_results/event_", event, "_results.csv"))
    
    # append event number
    event <- event + 1
    Sys.sleep(2)
    
  } else {
    isEvent <- FALSE
  }
}
```
