---
title: "wnba_team_models"
format: html
editor: visual
---

```{r}
wnba_team <- read_csv("kevari20/wnba_team_data.csv")
```

```{r}
# Load Packages
library(tidyverse)
library(ggplot2)
library(lubridate)
```

## Does mid season record predict season record?

### Linear Regression Model

```{r}
model <- lm(total_win_percent ~ half_win_percent, data = wnba_team) 
summary(model)
```

### Plot it

```{r}
library(ggplot2)
wnba_team %>% ggplot(aes(half_win_percent, total_win_percent)) + 
  geom_point(color = "blue") + 
  theme_bw() + 
  labs(
    title = "Win Percentage vs. Half Percentage",
    x = "Half Percentage",
    y = "Win Percentage"
  ) 
```

## Does mid season record predict rank?

### Linear Regression Model

```{r}
model2 <- lm(final_rank ~ half_win_percent, data = wnba_team)
summary(model2)
```

```{r}
# Separate plot for each season -> do they all look linear? 
wnba_team %>% ggplot(aes(half_win_percent, final_rank)) + 
  geom_point(color = "blue") + 
  theme_bw() + 
  labs(
    title = "Rank vs. Half Percentage",
    x = "Half Percentage",
    y = "Rank"
  ) +
  scale_y_reverse() + 
  facet_wrap(~ season)
```

# Does rank predict whether a team makes playoffs?

## Logistic Regression Model

```{r}
model3 <- glm(playoff ~ final_rank, data = wnba_team, family = binomial)
summary(model3)
```

# Two way table for each team and whether they make the playoffs

```{r}
# Two way table for rank and whether they make the playoffs
wnba_team %>% 
  select(final_rank, playoff) %>% 
  table()
```
