---
title: "Clinton Canoe Regatta: Looking at Normality in Distributions"
format: html
---

```{r}
## load required packages
library(tidyverse)
library(ggplot2)
library(dplyr)
## read in data
clinton <- read.csv("phoebechar/canoeing/clinton/data_repo_submission/full_clinton.csv")

clinton <- full_clinton

## filter to include each boat ONLY once
clinton <- clinton |> group_by(year, bib) |> slice(1)
## remove DNF/DNS/non-recorded times
clinton <- clinton |> filter(time != 0)

## create dataset with just the pro teams
clinton_pro <- clinton |> mutate(pro = if_else(grepl("pro", classID), 1, 0)) |>
  filter(pro == 1)

## create dataset with all non-pro canoes
clinton_canoe <- clinton |> 
  mutate(pro = if_else(grepl("pro", classID), 1, 0)) |>
  filter(pro == 0) |> mutate(canoe = if_else(grepl("oc", classID), 1, 0)) |> filter(canoe == 1)

## create dataset with all non-pro canoes
clinton_canoe <- clinton |> 
  mutate(pro = if_else(grepl("pro", classID), 1, 0)) |>
  #filter(pro == 0) |> 
  mutate(canoe = if_else(grepl("oc", classID), 1, 0)) |>
  filter(canoe == 1) |>
  mutate(n_paddlers = parse_number(classID))

clinton_canoe <- clinton_canoe |>
  select(year, classID, place, time, overall, pro, n_paddlers)


clinton_canoe |> write_csv(file = "clinton_canoes.csv")
```

```{r}
## graph times for pro canoes
ggplot(clinton_pro, aes(x = time)) +
  geom_histogram(binwidth = 600, colour = "royalblue4", fill = "royalblue3") +
  xlim(25000, 55000) +
  ylim(0, 70) +
  labs(x = "Time to Complete the Race (in sec)",
       y = "Count (number of boats)",
       title = "Time distribution for pro canoes at the Clinton") +
  theme_minimal()
```

```{r}
## graph times for non-pro canoes
ggplot(clinton_canoe, aes(x = time)) +
  geom_histogram(binwidth = 600, colour = "royalblue4", fill = "royalblue3")+
  xlim(25000, 55000) +
  ylim(0, 70) +
  labs(x = "Time to Complete the Race (in sec)",
       y = "Count (number of boats)",
       title = "Time distribution for non-pro canoes at the Clinton") +
  theme_minimal()
```

```{r}
pro_merge <- clinton_pro |> ungroup() |> select(time, pro)
canoe_merge <- clinton_canoe |> ungroup() |> select(time, pro)

merge <- full_join(pro_merge, canoe_merge)

merge <- merge |> mutate(pro_char = if_else(pro == 0, "non-pro", "pro"))

ggplot(merge, aes(y = time, x = pro_char, group = pro_char)) +
  geom_boxplot(outliers = FALSE) +
  theme_minimal() +
  labs(x = "Class",
       y = "Time (in seconds")
  
```


```{r}
## find the summary statistics for the two datasets

## min, Q1, median, Q3, max
quantiles <- c(0, 0.25, 0.5, 0.75, 1)

## create and print table with mean, standard deviation, min, Q1, median, Q3, and max 
## for non-pro canoes
canoe_sum <- tibble(value = c(mean(clinton_canoe$time), sd(clinton_canoe$time),
                              quantile(clinton_canoe$time, quantiles)
                              ), 
                    stat = c("Mean", "SD", "Min", "Q1", "Median", "Q3", "Max"))
canoe_sum <- canoe_sum |> tidyr::pivot_wider(names_from = stat, values_from = value) |>
  knitr::kable()

## for pro canoes
pro_sum <- tibble(value = c(mean(clinton_pro$time), sd(clinton_pro$time),
                              quantile(clinton_pro$time, quantiles)
                              ), 
                    stat = c("Mean", "SD", "Min", "Q1", "Median", "Q3", "Max"))
pro_sum <- pro_sum |> tidyr::pivot_wider(names_from = stat, values_from = value) |>
  knitr::kable()

```

In 2025, Adam Blanchard and Rebecca Sutton placed first in the C2 Stock (not pro) Mixed class with a time of 8 hours, 32 minutes, and 21 seconds (30741 seconds). In the same year, Dean Brown & Chris Prater placed 40th in the pro class with a time of 8 hours, 3 minutes and 11 seconds (28991 seconds). Which of these times is better relatively?
