---
title: "Modeling the Impact of Age on Powerlifting"
author: "Phoebe Jones, Cooper Olney, Faith Rhinehart" 
date: "June 9th, 2025" 
format: html
categories:
  - Nonlinear Least Squares Modeling
  - Confidence Intervals (Bootstrap)
---

## Motivation
Powerlifting is a strength sport where participants compete to lift the heaviest weight. Competitors compete within weight classes, so their opponents are around the same weight as them. The sport consists of three different lifts: Squat, Bench, and Deadlift. Squat lifts require lifters to squat so that their hips are below their knees and lift the weight to a specific depth. Bench lifts are done while the lifter is lying on a bench. Bench lifters start with the bar weight being held in the air and must lower the bar down to their body. Once the bar touches their body, lifters wait for the command to lift the bar back into the air with their elbows fully extended. Deadlifting, like squats, start with the lifter standing up. The lifter must lift the bar off the ground and get into the position where their shoulders are back and knees are locked. Competitors are overseen by three judges who determine whether the lift follows the rules of the events. If a judge believes the lifter followed the rules, they will turn on a white light. In order for a lift to count, competitors must receive at least two white lights.

<iframe width="560" height="315" src="https://www.youtube.com/embed/XAcjcFGY_Uc?si=-08ToeR9dV7JIjSE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Data

The `sample_powerlift_female.csv` data set contains observed performances from female powerlifters. Each row represents a different powerlifter. 

| Variables | Description   

| Id        | Powerlifters' ID
| Name      | Powerlifters' name
| Event     | SBD (squat, benchpress, deadlift - combined into one)
| Equipment | equipment class (raw and single ply)
| Age       | Age of powerlifter
| Age Class | Reported age class ex. 24-25, 80+
| Birth year class | Birth year group organized by IPF affiliates
| Division  | Division label (open, juniors, masters)
| Body Weight kg | Body weight of powerlifter in kg
| Actual body weight at weigh in in kg | weight at weight in (kg)
| Weight class kg | weight class competited in 
| Best3Squatkg | best squat from best 3 attempts
| Best3Benchkg | best bench from best 3 attempts
| Best3Deadliftkg | best deadlift from best 3 attempts
| Total kg | total of best squat, bench, deadlift in kg
| Place | Placing in meet, numeric, g, dq, etc.
| Dots | bodyweight adjusted score "modern wilks alternative"
| wilks | traditional wilks score
| Glossbrenner | Score used by gpc affilated feds
| Goodlift | IPF GL points (IPF performance standard)
| Tested | If meet was drug tested or not
| Country | Lifters' home country
| State | Lifters' home state, providence, or region
| Federation | Hosting federation (USAPL or WRPF)
| Parentfederation | Sanctioning Parent body (IPF)
| Date | Meet start date (yyyy-mm-dd)
| MeetCountry | Country where meet occured
| MeetState | State or region where meet occurred
| MeetName | Name of the meet with no year or federation
| Sanction | Yes if meet is offically recognized


: [sample_powerlift_female.csv](read_csv("frhinehart/Powerlifting/data_repo_submission/sample_powerliftemale.csv"))

Similar tidying was done to male competitors with the same variables.

: [sample_powerlift_male.csv](read_csv("frhinehart/Powerlifting/data_repo_submission/sample_powerlift_male.csv"))


## 

1. Graph a scatterplot to explore the relationship between age and best deadlift. 
2. Fit a nonlinear least squares regression model using a shifted gamma function, use bootstrap confidence interval to find peak age
3. Fit a nonlinear least squares regression model using reparameterized double exponential function, use bootstrap confidence interval to find peak age
4. Compare the models using residual sum of squares and AIC

## References

[Open Powerlifting Data Service](https://openpowerlifting.gitlab.io/opl-csv/bulk-csv-docs.html){target="_blank"}

The data set for this module was extracted from OpenPowerlifting Data Service. It contains over 3.6 million observations with 43 different variables containing the classifications and totals for an individual lifter. 