---
title: "concussion_exploration"
author: "eric seltzer"
format: html
---

```{r}
library(tidyverse)
```

```{r}
concussion <- read_csv(here::here("esselt21/concussion_module/exploration/concussion.csv"))
```

```{r}
# cleaning data into format I want
concussion <-
  concussion|>
  mutate(Position = as_factor(Position),
         `Reported Injury Type` = as_factor(`Reported Injury Type`)) |>
  filter(`Pre-Season Injury?` == 'No') |>
  select(-c(ID, Game, Season, `Pre-Season Injury?`, `Unknown Injury?`, `Winning Team?`, `Opposing Team`, `Week of Injury`, `Weeks Injured`, `Total Snaps`)) |>
  na.omit()

concussion <-
  concussion |>
  mutate(`Play Time After Injury` = parse_number(`Play Time After Injury`, na = "Did not return from injury"),
         `Average Playtime Before Injury` = parse_number(`Average Playtime Before Injury`),
         `Play Time After Injury` = replace_na(`Play Time After Injury`, 0))
```

```{r}
# looking into individual teams
teams <-
  concussion |>
  mutate(Team = as_factor(Team))

teams <-
  teams |>
  group_by(Team) |>
  summarise(totalConcussions = n(),
            avgDownsAfter = mean(`Play Time After Injury`),
            avgGamesMissed = mean(`Games Missed`))

teams |>
  ggplot(aes(x = fct_reorder(Team,
                             totalConcussions,
                             .desc = FALSE),
             y = totalConcussions,
             fill = Team)) +
  geom_col(alpha = 0.5) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "NFL Teams",
       y = "Number of Concussions",
       title = "Total Number of Concussions by Team")

teams |>
  ggplot(aes(x = fct_reorder(Team,
                             avgDownsAfter,
                             .desc = FALSE),
             y = avgDownsAfter,
             fill = Team)) +
  geom_col(alpha = 0.5) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "NFL Teams",
       y = "Average Downs Played",
       title = "Average Downs Played After a Concussion")

teams |>
  ggplot(aes(x = fct_reorder(Team,
                             avgGamesMissed,
                             .desc = FALSE),
             y = avgGamesMissed,
             fill = Team)) +
  geom_col(alpha = 0.5) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0)) +
  labs(y = "Average Games Missed",
       x= "NFL Teams",
       title = "Average Games Missed After a Concussion by NFL Team")
```

```{r}
# adding offense and defense variable
concussion <-
  concussion |>
  mutate(Offense = if_else(Position %in% c("Wide Receiver", "Offensive Tackle", "Center", "Running Back", "Guard", "Tight End", "Quarterback", "Full Back"), "Offense", "Defense"),
         Skilled = if_else(Position %in% c("Wide Receiver", "Running Back", "Tight End", "Quarterback", "Full Back"), "Skilled", "Non-Skilled"))
```

```{r}
concussion |>
  ggplot(aes(x = `Play Time After Injury`,
             color = Position)) +
  geom_density(aes(fill = Position),
               alpha = 0.2) +
  theme_minimal() +
  labs(y = "Density") +
  facet_wrap(~Offense)
```

```{r}
# looking into anova, according to report, effect of position on play time after injury is significant and medium
# need to look into assumptions
library(AICcmodavg)
library(report)
one.way <- aov(`Play Time After Injury` ~ Position,
               data = concussion)
plot(one.way)
# doesn't look normal,
# variance looks good
# independent is true
summary(one.way)
report(one.way)
```

```{r}
# tukey
TukeyHSD(one.way)
```

```{r}
concussion |>
  ggplot(aes(x = Position,
             `Play Time After Injury`,
             fill = Position,
             alpha = .3)) +
  geom_boxplot() +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") 
```

