---
title: World Athletics Race Walking Team Championships 2024
author: Abigail Smith
date: June 18, 2024
description: Comparing both the 10 and 20k speeds and records for racers and countries in the 2024 World Athletics Race Walking Team Championships in Antalya, Turkey. 
categories:

  
editor: 
  markdown: 
    wrap: 72
---
## Motivation

Race walking is a competitive individual sport with a similar layout to cross country running, except instead of running, competitors walk. Athletes utilize a swift walking motion which involves a lot of movement of the hips and arms, enabling them to move faster. Just like in running the first participant to cross the finish line wins. According to [Olympic rules](https://olympics.com/en/news/all-you-need-to-know-about-race-walking){target="_blank"}. The main rule in racewalking is that racewalkers **must** maintain contact with the ground at all times, unlike in running when the stride often involves both feet being off the ground. Additionally, racewalkers can not bend their leading knee when they are walking. Judges are posititoned throughout courses to ensure these rules are withheld. If an athlete violates either of the rules, judges show them a "warning paddle". Three warning paddles result in a red paddle which means the athlete is disqualified from the event. These rules provide an added challenge to the sport. 

The World Athletics Race Walking Team Championships are an international race walking event hosted annually in different cities. After events are completed, total medals are tallied for each country competing, which is why they are considered the "team" championships.In addition to winning medals for 1st, 2nd, and 3rd place respectively, athletes can also set new records for both themselves as well as others.The [2024 championship](https://worldathletics.org/competitions/world-athletics-race-walking-team-championshi/world-athletics-race-walking-team-championshi-7199325){target="_blank"} was hosted in Antalya, Turkey and consisted of four events, a women's 10 and 20k, and a men's 10 and 20k. 

Analyzing podium finishes, records, and speeds in long (20k) and shorter (10k) distance races can provide insight on patterns in either event, such as which countries dominate. Additionally, comparing the speeds between the distances can show if there is a difference in pacing approaches in a long race versus a shorter race. Assessing the number of records can further discern whether or not certain approaches are more successful than others. 

## Data

In the data set there are 41 medalling nations that competed in 25 different events. Each row represents a nation and their `total_medals` and `total_points` which are cumulative from all rowing Olympics between 1900 and 2022. In total, there are 41 rows with 3 variables. In the original dataset, there were 101 nations in rowing, but the data has been adjusted to include only nations that medalled. 

| Variable | Description                                                                                                                |
|-------------------|-----------------------------------------------------|
| `NOC` | National Olympic Committee or the nation competing. |
| `total_medals` | The total number of medals for that country. |
| `total_points` | The total number of points for that country. The points are scaled with a gold medal counting for 3 points, a silver for 2, and a bronze for 1. |
| `total_gold` | The total number of gold medals for that country. |
| `total_silver` | The total number of silver medals for that country. |
| `total_bronze` | The total number of bronze medals for that country. |

: [rowing_medals.csv](rowing_medals.csv){target="_blank"}


## Questions

1.    Describe the distribution of total_points for all countries. Is there a skew, if so, what is it and what does it mean?

2.    Obtain the summary statistics for total_points. 

3.    The UK has 154 total_points in the dataset, determine whether or not that is an outlier. Use calculations to justify your answer.

4.    Based on the distribution of total_medals amongst the countries in the dataset, would it be fair to assume that poverty is a confounding variable? Explain why or why not

5.    What could be a reason for the distribution of medals and points being so heavily skewed towards certain nations winning more than others?

6.    There is a lot of debate about how to best weigh the points for the different types of medals, what is a method you think would be best for weighing these medals? How would the new method alter the data?

## References

[Kaggle Original Dataset](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results?resource=download){target="_blank"}

[Olympic Medal Weighing Methods](https://www.topendsports.com/events/summer/medal-tally/rankings-weighted.htm){target="_blank"}
