---
title: "data-exploration"
author: "Brendan Karadenes"
format: html
---

```{r}
library(tidyverse)
library(here)
batting <- read.csv(here("bkaradenes/NGL_Module/exploration/ngl_batting.csv"))
```

```{r}
ggplot(data = batting, mapping = aes(x = OPS_plus, y = Pos)) +
  geom_boxplot()
```

```{r}
batting_mod <- batting %>%
  filter(!is.na(OPS & OPS_plus & wOBA & BB_K_ratio & ISO))
model <- lm(R ~ SB + OPS_plus + homerun_rate + `BB_K_ratio` + RBI, data = batting)
summary(model)
```

```{r}
install.packages("GGally")
library(GGally)
ggpairs(data = batting_mod, columns = c("R", "SB", "BB_K_ratio", "OPS_plus", "homerun_rate", "RBI"))
```

```{r}
install.packages("car")
library(car)
vif(model)
```

```{r}
anova(model)
```

```{r}
slunova=function(model){
  numpred=model$rank-1
  dferror=df.residual(model)
  dfmodel=numpred
  dftotal=dfmodel+dferror
  sse=sum(model$residual^2)
  ssmodel=sum(model$effects[2:(numpred+1)]^2)
  sstotal=ssmodel+sse
  msmodel=ssmodel/dfmodel
  mse=sse/dferror
  fstat=msmodel/mse
  pvalue=1-pf(fstat,dfmodel,dferror)
  df=c(dfmodel,dferror,dftotal)
  ss=c(ssmodel,sse,sstotal)
  ms=c(msmodel,mse,0)
  f=c(fstat,0,0)
  p=c(pvalue,0,0)
  table=data.frame(df,ss,ms,f,p)
  table[2,4:5]=NA
  table[3,3:5]=NA

colnames(table)=c("Df","Sum Sq","Mean Sq","F value","P(>F)")
  row.names(table)=c("Model","Error","Total")
  class(table)=c("anova","data.frame")
  structure(table,
            heading=c("ANOVA Table",                            paste("Model:", formula(model)[2],formula(model)[1],formula(model)[3],"\n")))
}
```

```{r}
slunova(model)
```

```{r}
model2 <- lm(R ~ , data = batting)
```

```{r}
slunova(model2)
```

