---
title: "Andrei Vasilevskiy 2019-2021 Save Percentage"
author: "Cooper Olney"
date: "July 23, 2025"

categories:
  - Summary Statistics
  - Histograms
---


## Motivation

The Tampa Bay Lightning established themselves as one of the best modern NHL teams by winning back-to-back Stanley Cup Championships in the 2019-20 and 2020-21 seasons. The NHL playoffs are structured as four round, best of seven series tournament: the First Round, Second Round, Conference Finals, and the Stanley Cup Final. To win the championship, a team must win 16 games over the course of multiple high stakes series, facing the toughest opponents in rapid succession.

At the core of the Lightning's run was Andrei Vasilevskiy, the team's starting goaltender. Known for his athleticism, composure, and consistency, Vasilevskiy played a crucial role in Tampa Bay's title runs. In the 2020-21 playoffs, he posted on of the most dominant performances by a goalie in recent memory and was awarded the Conn Smythe Trophy as the most valuable player of the postseason. His ability to perform under pressure, especially in elimination games, helped solidify his reputation as one of the best goaltenders of his era.

This module allows us to explore how statistical tools (such as [StatKey](https://www.lock5stat.com/StatKey/){target="_blank"}) can be used to simulate real-world scenarios. By treating Vasilevskiy's game-by-game save percentages from the 2019-20 and 2020-21 regular seasons as the population, we can model specific playoff situations by drawing random samples of different sizes. These simulations help us understand how much variation we might expect in his performances and how likely different playoff outcomes are based on his regular season save percentages.


## Data
The `vasilevskiy_save_percentage.csv` dataset contains 94 rows and 1 column. Each row represents a regular season game that Andrei Vasilevskiy played during the 2019-20 and 2020-21 NHL seasons.

Download Data: [vasilevskiy_save_percentage.csv](vasilevskiy_save_percentage.csv)

<details>

<summary><b>Variable Description</b></summary>

| Variable | Description                                                         |
|----------|---------------------------------------------------------------------|
| save_percentage   | The proportion of shots on goal that Vasilevskiy saved in a given game. |

</details>


## Questions

1. What does Vasilevskiy's 2019-2021 regular season save percentage distribution look like in terms of shape, center and spread?

2. What is the typical variation in save percentage in a game for Vasilevskiy?


## References

Andrei Vasilevskiy 2019-20 Game Log. (n.d.). Hockey-Reference.Com. Retrieved from https://www.hockey-reference.com/players/v/vasilan02/gamelog/2020

Andrei Vasilevskiy 2020-21 Game Log. (n.d.). Hockey-Reference.Com. Retrieved from https://www.hockey-reference.com/players/v/vasilan02/gamelog/2021

