---
title: "World Athletics Race Walking Team Championships 2024"
author:
  - name: Abigail Smith
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: June 21, 2024
description: Comparing both the 10 and 20k speeds and records for racers and countries in the 2024 World Athletics Race Walking Team Championships in Antalya, Turkey.
categories:
 -  Distribution and skewness
 -  Two-Sample t.test
 -  Two-Way ANOVA for difference in means
 -  Odds, predicted odds and log(odds)
 -  G-test for overall fit 
---

### Welcome video

{{< video  title="World Athletics Race Walking Team Championships 2024" >}}

### Introduction

This activity examines the speeds, records and podium finishes of race walkers at the [World Athletics Race Walking Team Championships 2024](https://worldathletics.org/competitions/world-athletics-race-walking-team-championshi/world-athletics-race-walking-team-championshi-7199325){target="_blank"}. 

[Race walking](https://en.wikipedia.org/wiki/Racewalking){target="_blank"} is a competitive individual sport with a similar layout to cross country running, except instead of running, competitors walk. Athletes utilize a swift walking motion which involves a lot of movement of the hips and arms, enabling them to move faster. Just like in running the first participant to cross the finish line wins. According to [Olympic rules](https://olympics.com/en/news/all-you-need-to-know-about-race-walking){target="_blank"}. The main rule in racewalking is that racewalkers **must** maintain contact with the ground at **all times**, unlike in running when the stride often involves both feet being off the ground. Additionally, racewalkers can not bend their leading knee when they are walking. Judges are positioned throughout courses to ensure these rules are withheld. If an athlete violates either of the rules, judges show them a "warning paddle". Three warning paddles result in a red paddle which means the athlete is disqualified from the event. These rules provide an added challenge to the sport. 

The World Athletics Race Walking Team Championships are an international race walking event hosted annually in different cities. After events are completed, total medals are tallied for each country competing, which is why they are considered the "team" championships.In addition to winning medals for 1st, 2nd, and 3rd place respectively, athletes can also set new records for both themselves as well as others.The 2024 championship was hosted in Antalya, Turkey and consisted of four events, a women's 10 and 20k, and a men's 10 and 20k. 

Analyzing podium finishes, records, and speeds in long (20k) and shorter (10k) distance races can provide insight on patterns in either event, such as which countries dominate. Additionally, comparing the speeds between the distances can show if there is a difference in pacing approaches in a long race versus a shorter race. Assessing the number of records can further discern whether or not certain approaches are more successful than others.

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity could be used as a cumulative quiz or take home assignment for final exam prep. 
:::



::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, students will be able to:

1.  Assess the difference in means for two groups
2.  Evaluate the difference in means across two factors
3.  Fit a multiple logistic regression model
4.  Calculate odds, log(odds), and predicted odds for a multiple logistic regression model
5.  Evaluate the overall fit of a multiple logistic regression model
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Students will use a basic understanding of histograms and boxplots to assess the distribution of grouped data. Students will further assess the difference in groups, using a t.test as well as a two-way ANOVA test for a difference in means. Additionally, students will use multiple logistic regression to calculate the odds, predicted odds, and log(odds) of a binary response variable. 
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
The normal worksheet will only require the use of basic statistical software for one question. The tech worksheet however, will require the use of more complicated statistical software such as R. 
:::

### Data

In the dataset there are 237 cases with 10 variables. Each case is a male or female athlete in either the 10k or the 20k. There are 98 walkers in the men's 10k and 47 in the women's. There are 63 walkers in the women's 20k and 76 in the men's. The dataset only includes athletes who completed the race, no disqualified or did not finish walkers are in the dataset. There are no walkers that competed in more than one event. 

Download data: 

: [racewalking.csv](racewalking.csv){target="_blank"}

<details>
<summary><b>Variable Descriptions</b></summary>

| Variable          | Description                                                                                                                                                                                                                   |
|--------------------|----------------------------------------------------|
| `POS` | The position the athlete finished in. |
| `COUNTRY` | The country the athlete is from. |
| `ATHLETE` | The name of the athlete in `first name, last name` order. |
| `RECORD` | The record the athlete made if any. The record types are as follows: Personal Best (`PB`), Season's Best (`SB`), National Record (`NR`), Area Under 20 Record (`AU20R`), National Under 20 Record (`NU20R`)|
| `DISTANCE` | The distance of the race the athlete competed in, either `10000`m or `20000`m.|
| `GENDER` | The gender of the athlete, either `Man` or `Woman`. |
| `TIME` | The total time it took the athlete to complete the race, measured in minutes. |
| `SPEED` | The average speed of the athlete for the race, measured in meters/minute. |
| `REC` | If the athlete made a record in the race, binary variable where `TRUE` means they did and `FALSE` means they did not.|
| `PODIUM` | If the athlete had a podium finish in the race, binary variable where `TRUE` means they did and `FALSE` means they did not. A podium finish means the athletes `POS` was 1st, 2nd, or 3rd. |



**Data Source**

[Original Dataset](https://worldathletics.org/competitions/world-athletics-race-walking-team-championshi/world-athletics-race-walking-team-championshi-7199325){target="_blank"}

**More information on the rules**

[Olympic Racewalking Rules](https://olympics.com/en/news/all-you-need-to-know-about-race-walking){target="_blank"}

[Athletic Abbreviations](https://en.wikipedia.org/wiki/Athletics_abbreviations){target="_blank"}

[Race walking Wikipedia](https://en.wikipedia.org/wiki/Racewalking){target="_blank"}

</details>

### Materials

We provide editable MS Word handouts along with their solutions.

[Tech Worksheet](racewalking_tech_worksheet.docx)

[Tech Worksheet Answers](racewalking_worksheet_tech_KEY.docx)

[No Tech Worksheet](racewalking_worksheet.docx)

[No Tech Worksheet Answers](racewalking_worksheet_KEY.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
After finishing this activity, students should discern whether or not there are any clear patterns in the data. These patterns can relate to differences in mean speeds based on distance and/or gender. The patterns can also relate to the predictability of whether or not an athlete will make a record in the event. 
:::
