---
title: Power Lifting Statistics
author: Sarah Weaver
date: June 21, 2023
description: Data on power lifting competitors spanning many years.
categories:
  - simple regression
  - multiple regression
  - correlation
  - scatterplots
---

## Motivation

Suppose you wanted to look at different power lifting events and find correlation,
run a linear regression, or see if there is any relation between body weight and 
the amount one can bench, squat, or dead lift. This data set contains male and female 
competitors and their stats based on their performances in tournaments.

## Data

The data set has 295,877 rows with 7 columns. Each row represents a power lifting
competitor and their respective personal information.

| Variable | Description |
|----|-------------|
| Name | The competitor's name |
| Sex | The competitor's sex |
| Age | The competitor's age |
| BodyweightKg | The competitor's body weight in kilograms |
| BenchKg | The total weight a competitor can bench in kilograms |
| SquatKg | The total weight a competitor can squat in kilograms |
| DeadliftKg | The total weight a competitor can dead lift in kilograms |

: [powerliftingregression.csv](../data/powerliftingregression.csv)

## subsets of data can be used to model examples like correlation and
## simple or multiple regression
```{r}
# eval: false
opl_female <- opl_class |> filter(Sex == "F") |> filter(Age == 25.0)
```

: [opl_female.csv](../data/opl_female.csv)



## Questions

The data set is designed to help model a multiple linear regression example. 
The size of the data set allows for subsets to be created which can be used for
correlation or simple linear regression. These are just some of the applications
for this data set.


## References

Powerlifting rankings. OpenPowerlifting. (n.d.). 
<https://www.openpowerlifting.org/> 
