---
title: "The Impact of Outliers: The Raisin River Canoe Race"
format: html
---

Downriver racing is a sport where competitors take their watercraft (usually a canoe, kayak, or stand-up paddle board) down a race course in competition with other paddlers, sometimes navigating rapids, in an attempt to get the fastest time either overall or in their class (classes are split up by boat and paddler type). The Raisin River Canoe race has been running for over 50 years on the Raisin River in Eastern Ontario. The usual race course is 30 km (~18.6 miles) and contains rapids that fluctuate in difficulty with the water level.
In race results, a DNF (did not finish) refers to a boat that did not make it to the finish line. Most of the time, these boats are paddlers who at some point decided to drop out of the race. This is most common in longer races (like Raisin River) or races with dangerous rapids. While the rapids on the Raisin River course are not too intimidating, as water level increases, the difficulty (or, more importantly, the fear factor) increases as well.
Race directors are responsible for keeping track of their competitors and making sure they get off the river safely, so it is important that race officials are aware of possible DNFs. Having a way to predict the ratio of participants that may DNF the race based on the water level (information that is known ahead of time) could be very useful.
For this activity we will be using data containing DNF and water level measures from the Raisin River Race from 2005-2025 to look at how outliers can impact a model.

```{r}
library(tidyverse)
library(dplyr)
library(broom)

RR_dnf_data <- read_csv("phoebechar/raisin_river/module/raisin_river_DNF.csv")
```

This data set contains flow measurements (indicative of water level) in ft^3/sec and the ratio of DNFs (# of DNFs/total participants) from the Raisin River Race from 2005-2025 (excluding, 2020 and 2021, when the race didn't run, and 2019, which has incomplete data).

#### 1. Graph a scatterplot that shows flow rate as a predictor for rate of DNF

##### a) What do you notice?


#### 2. Fit a model using flow rate as a predictor for ratio of DNFs

###### a) Comment on the usefulness of the model


#### 3. Use the augment function to add the model's residuals into the dataset

##### a) Do any observations have unusual leverage? standardized residual? influence?

In 2017, the water level was too high for the race to start where it usually does. Because of this, the race course that year was about 4 miles shorter than the regular course. This is most likely the reason that there are much fewer DNFs.

#### 4. Remove the influential observation from the data set.


#### 5. Regraph the scatterplot without the influential observation and add a smoother.


#### 6. Refit the model with the new version of the data set.

##### a) Meaningfully interpret the slope coefficient.
2
##### b) If the flow level is 1100 ft\^3/sec and there are 200 competitors about how many DNFs can we expect?



