---
title: "rowing_start"
format: html
---

I am playing around with this Olympics data set I found on [Kaggle](https://www.kaggle.com/code/kalilurrahman/olympic-games-eda){}. I want to look specifically at rowing and medals. The data set contains data from the 1896 Olympics to the 2022 Olympics. 

# Loading the packages and reading in the data

```{r}
library(tidyverse)
library(forcats)
library(readr)
library(stringr)
```

```{r}
athletes_df <- read_csv("athlete_events.csv")
```

```{r}
medals_df <- read_csv("rowing_medals.csv")
```

# Worksheet questions

```{r}
#Question 1
medals_hist <- medals_df |> filter(points >= 5) |> arrange(desc(points)) 

ggplot(medals_df, aes(x = points)) + geom_histogram(fill = "lightblue", colour = "black", bins = 20) + theme_minimal() + labs(title = "Histogram of points for all countries in all events")
```

```{r}
#Question 2
#a)
summary(medals_df$points)
#b)
medals_df |> arrange(desc(points)) |> head()
```

```{r}
#Question 3
ggplot(data = medals_df, aes(x = points)) + geom_boxplot() + theme_minimal()
```


```{r, fig.height= 7, fig.width=2}
# Question 4
sum_medals <- medals_df |> group_by(NOC) |> summarise(medals = sum(medals)) 

medals_reordered <- sum_medals |> mutate(NOC = fct_reorder(NOC, medals))

ggplot(data = medals_reordered, aes(x = NOC, y = medals)) + geom_col(fill = "lightblue", colour = "grey") + coord_flip() + theme_minimal() + labs(title = "Barplot of NOC ranked by medals")
```


#Considering adding a question

```{r}
summary(medals_df$total_points)
IQR(medals_df$total_points)
1.5*IQR(medals_df$total_points)
57.00 + (1.5*IQR(medals_df$total_points))
6.00 - (1.5*IQR(medals_df$total_points))
```

```{r}
points <- medals_df |> arrange(desc(total_points))
head(points)
tail(points)
```

```{r}
medals_df |> filter(total_points >=133.5)
```

```{r}
summary(medals_df$total_medals)
IQR(medals_df$total_medals)
1.5*IQR(medals_df$total_medals)
31.00 + (1.5*IQR(medals_df$total_medals))
4.00 - (1.5*IQR(medals_df$total_medals))
```

```{r}
medals <- medals_df |> arrange(desc(total_medals))
head(medals)
tail(medals)
```

```{r}
medals_df |> filter(total_medals >=71.5)
```
****is there an event that is more coveted than others****
```{r}
events <- country_event |> mutate(n_point= case_when(Medal == "Gold" ~ 3, Medal == "Silver" ~ 2, Medal == "Bronze" ~ 1)) |> group_by(NOC, Event) |> summarise(total_medals = n(), total_points = sum(n_point))
```

```{r}
medals_df |> arrange(total_medals) 
```

```{r}
usa <- events |> filter(NOC == "NOR" | NOC == "USA") |> mutate(Event = fct_reorder(Event, total_medals))
ggplot(data = usa, aes(y = total_medals, x = Event, fill = NOC)) + geom_col(position = "dodge") + coord_flip()
```

```{r}
event_df <- events |> group_by(NOC, Event) |> summarise(n = n()) 
```

```{r}
event <- event_df |> group_by(Event) |> summarise(n = n())
order_event <-event |> mutate(Event = fct_reorder(Event, n))
ggplot(order_event, aes(x = Event, y = n)) + geom_col() + coord_flip()
```

```{r}
medals_df |> arrange(desc(total_medals))
## make a variable for the top 5
```

```{r}
top5 <- events |> mutate(top5 = if_else(NOC =="USA" | NOC == "GBR" | NOC == "GER" | NOC == "GDR" | NOC == "ITA", true = 1, false = 0))
```

```{r}
eight <- events |> mutate(eight = if_else(Event =="Rowing Men's Coxed Eights" | Event == "Rowing Women's Coxed Eights", true = 1, false = 0))
```

```{r}
#use stringr to see if its coxed
coxed <- events |> mutate(coxed = str_detect(Event, "Coxed", negate = FALSE))
```

```{r}
mod <- lm(total_medals ~ coxed, data = coxed)
summary(mod)
```

```{r}
plot <- coxed |> group_by(NOC) |> summarise(n_coxed = sum(coxed), total_medals = sum(total_medals))
```

```{r}
ggplot(plot, aes(x = n_coxed, y = total_medals)) + geom_col()
```

```{r}
full <- left_join(coxed, top5)
```

```{r}
mod <- lm(total_medals ~  coxed, data = coxed)
summary(mod)
```

```{r}
t.test(total_medals~coxed, var.equal=TRUE, data=coxed)
```

```{r}
summary(coxed$coxed)
```

```{r}
ggplot(data = coxed, aes(x = coxed, y = total_medals)) + geom_boxplot() + theme_minimal()
```

```{r}
ggplot(data = medals_df, aes(x = total_points)) + geom_boxplot() + theme_minimal()
```

```{r}
summary(medals_df$total_medals)
```

```{r}
medals_df |> arrange(desc(total_points)) |> head()
```


