---
title: "Short Track Speed Skating"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(here)
```

```{r}
speed_skating <- read.csv("/Users/Gavin Cassidy/Desktop/GitHub/stat_289_score/gacass21/Speed Skating/m500_lap_time_rank_ver5.csv")
speed_skating
```

```{r}
speed_skating |> summary()
```
 

```{r}
ggplot(data = speed_skating, aes(x = Rank_In_Group, y = Time)) +
  geom_jitter(aes(color = rank_lap1))
```

```{r}
speed_skating |>  
  group_by(rank_lap1) |>
  summarise(avg_finish = mean(Rank_In_Group, na.rm = TRUE), n())
```

```{r}
speed_skating |> group_by(Season) |> summarise(n())
```

```{r}
time_outliers <- speed_skating |> filter(Time < 60)
```


```{r}
ggplot(data = time_outliers, aes(x = Time)) +
  geom_histogram()
```

```{r}
speed_skating |> group_by(Name) |> summarise(races = n()) |> arrange(desc(races))
```


```{r}
time_outliers |> group_by(Round) |> summarise(mean = mean(Time, na.rm = TRUE), n()) |> arrange(desc(mean))
```


```{r}
speed_skating |> group_by(Year) |> summarise(mean = mean(Time, na.rm = TRUE), n())
```


```{r}
speed_skating |> filter(Year == 2015, Month > 7) |> summarise(mean = mean(Time, na.rm = TRUE))
```

```{r}
speed_skating |> group_by(Name) |> summarise(mean = mean(Time, na.rm = TRUE), n()) |> arrange(desc(mean))
```

```{r}
speed_skating |> group_by(Name) |> filter(Time == min(Time)) |> ungroup() |> group_by(Nationality) |> summarise(mean = mean(Time, na.rm = TRUE), athletes = n()) |> arrange(athletes)
```

```{r}
lap1_slow <- speed_skating |> filter(time_lap1 < 9)
ggplot(data = lap1_slow, aes(x = time_lap1)) +
  geom_histogram(bins = 50, fill = "darkblue")
```

```{r}
speed_skating |> group_by(Name) |> filter(!is.na(Time)) |> summarise(pr = min(Time)) |> arrange(pr) |> slice(1:20) |> select(Name) |>
  write.csv()
```

```{r}
fast_skater <- speed_skating |> filter(Name == "HAMELIN Charles" |
                                       Name ==  "GIRARD Samuel" | 
                                       Name =="WU Dajing" ) |>
                                  filter(Time < 44, Year >= 2015)
  

ggplot(data = fast_skater, aes(y = Time, x = Time_Event)) +
  geom_point(aes(color = Name))

fast_skater |> arrange(desc(Time_Event)) |> slice(1:25) |> select(Name, Time) |> arrange(Time)
```

```{r}
wu_improvement <- speed_skating |> filter(Name == "Freek van der WART" |
                                            Name == "WU Dajing" | 
                                            Name == "HAMELIN Charles" |
                                            Name == "LIU Shaoang", Time <= 50) |> group_by(Time_Event, Name) |> filter(Time == min(Time)) |> ungroup()

ggplot(data = wu_improvement, aes(x = Time_Event, y = Time)) +
  geom_point(aes(color = Name)) +
  geom_line(aes(color = Name))
```


```{r}
home_field <- speed_skating |> filter(Country == Nationality, Time < 60) |> 
  group_by(City, Year) |> 
  summarise(advantage = mean(Time, na.rm = TRUE)) 

away_event <- speed_skating |> filter(Country != Nationality, Time < 60) |> 
  group_by(City, Year) |> 
  summarise(advantage = mean(Time, na.rm = TRUE)) 
```

```{r}
speed_skating |> group_by(City) |> 
  summarise(location_time = mean(Time, na.rm = TRUE), 
            fastest = min(Time, na.rm = TRUE), 
            total_sk8r = n()) |> 
  arrange(location_time)
```

```{r}
speed_skating |> group_by(Time_Event, Name) |> 
  filter(!is.na(Time)) |> 
  filter(Time == min(Time)) |> 
  ungroup() |>
  group_by(Time_Event, City) |>
  summarise(participants = n()) |>
  arrange(desc(participants))
```

```{r}
speed_skating |> group_by(Time_Event) |> 
  filter(!is.na(Time)) |> 
  filter(!is.na(Qualification)) |>
  summarise(avg_time = mean(Time)) |>
  arrange(avg_time)
```


```{r}
speed_skating |> filter(Round == "Preliminaries" | Round == "PrePreliminaries") |>
  filter(!is.na(Time)) |>
  summarise(avg_time = mean(Time), total = n())
```

```{r}
speed_skating |> filter(Round == "FinalA" | Round == "FinalB") |>
  filter(!is.na(Time)) |>
  summarise(avg_time = mean(Time), total = n())
```

```{r}
speed_skating |> filter(Country == "GER", Year == 2013, Round == "FinalA"| Round == "FinalB") |> arrange(Time)
```

```{r}
speed_skating |> group_by(Name) |>
  filter(!is.na(Time)) |>
  arrange(Time) |> slice(1:10) |>
  summarise(top_10 = mean(Time)) |>
  arrange(top_10)
```

```{r}
speed_skating |> filter(Round == "FinalA"| Round == "FinalB") |>
  group_by(Round) |>
  summarise(avg_time = mean(Time, na.rm = TRUE), racers = n())
```

```{r}
speed_skating |> group_by(Start_Position) |>
  summarise(avg_time = mean(Time, na.rm = TRUE), 
            tot = n(), 
            avg_finish = mean(Rank_In_Group, na.rm = TRUE))
```


```{r}
speed_skating |> filter(!is.na(time_lap1)) |> filter(time_lap1 == min(time_lap1))
speed_skating |> filter(!is.na(time_lap2)) |> filter(time_lap2 == min(time_lap2))
speed_skating |> filter(!is.na(time_lap3)) |> filter(time_lap3 == min(time_lap3))
speed_skating |> filter(!is.na(time_lap4)) |> filter(time_lap4 == min(time_lap4))
speed_skating |> filter(!is.na(time_lap5)) |> filter(time_lap5 == min(time_lap5))
```

