---
  title: "2024 College Ultimate Championship Statistics"
author:
  - name: Gavin Cassidy
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name:
    email: 
    affiliation:
      - ref:
date: June 26, 2024
description: Statistics from the 2024 College Ultimate Championships to be tidied and plotted.
categories:
  - Data Cleaning
  - Joining
  - Data Visualization
---

## Module

### Introduction

Ultimate, also commonly known as Ultimate Frisbee, is a non contact sport where 2 teams of 7 players see who can reach the target score. College Ultimate has games played to 15 points, or to a time limit where the winning team has to score 1 more point to win the game. Points are scored when a team successfully throws the Frisbee to the opposing teams end zone and a teammate catches the Frisbee. Each point of Ultimate starts with both teams in their end zone. The defensive team pulls the Frisbee to the offensive team, and the offensive team tries to score without dropping the Frisbee. Players cannot move when they have possession of the Frisbee, so the defensive team tries to block their ability to pass, or intercept a pass to receivers. The defensive teams goal is to stop the offense from scoring and to pick up the Frisbee and score on them. The team that scores becomes the defensive team for the next point, and pull to the offensive team. Teams also switch ends of the field each point to prevent any wind advantage.

The 2024 College Ultimate Championships took place May 18th-20th for [Division 3](https://play.usaultimate.org/events/2024-USA-Ultimate-D-3-College-Championships/), and May 24th-27th for [Division 1](https://play.usaultimate.org/events/2024-USA-Ultimate-D-1-College-Championships/). 16 teams competed for the Division 3 titles, while 20 teams battled to win the Division 1 title. The weekends were full of exciting games and wild weather, as teams battled to win their groups, and advance to the bracket. The data from the weekends includes statistics for each player, along with the number of games their team played.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
The learning objectives associated with this module are:

-   Being able to tidy and clean data sets

-   Using dplyr and ggplot functions to visualize the data
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
-   The worksheet provides 2 .csv files with data from the 2024 College Ultimate Championships.

-   Use R Studio to clean and tidy the data files and complete the worksheet
:::

### Data

This data comes from the 2024 Division 1 and 3 Men's and Women's College Ultimate Championships. It contains scoring and defensive statistics for players from each game played at the two tournaments. There are 2 tables, the first one contains player statistics. This table has 8325 rows and 8 columns, 5 rows for each player in the data set.

[ultimate_total.csv](ultimate_total.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable               | Description                                                                       |
|--------------------------|----------------------------------------------|
| Player                 | player name                                                                       |
| Measure Names          | the statistic measured by Measure Values (Points, Assists, Turns, Ds, Plus Minus) |
| Competition Level      | The level that the player was competing at                                        |
| Full Division Name     | level and gender of the competing player's division                               |
| Full Team Name Correct | full name of the players team(Same as Full Team Name)                             |
| Full Team Name         | full name of the players team                                                     |
| Gender Division        | gender of the player's division                                                   |
| Measure Values         | the measured value of the statistic from Measure Name                             |

::: {.callout-note collapse="true" title="Measured Statistics" appearance="minimal"}
-   Points: number of points the player scored
-   Assists: number of assists the player scored
-   Turns: number of turnovers the player threw
-   Ds: number of defensive blocks the player made
-   Plus Minus: the point differential while the player was on offense(Note: defensive points do not contribute to plus minus)
:::

The 2nd table contains the total games played by each player in the College Ultimate Championships. It has 1665 rows and 8 columns. There is only 1 row for each player and it contains the data for games played.

[ultimate_per_game.csv](ultimate_per_game.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable               | Description                                                                |
|--------------------------|----------------------------------------------|
| Player                 | player name                                                                |
| Measure Names          | the statistic measured by Measure Values (Only Total Games for this Table) |
| Competition Level      | The level that the player was competing at                                 |
| Full Division Name     | level and gender of the competing player's division                        |
| Full Team Name Correct | full name of the players team(Same as Full Team Name)                      |
| Full Team Name         | full name of the players team                                              |
| Gender Division        | gender of the player's division                                            |
| Measure Values         | the measured value of the statistic from Measure Name                      |

**Data Source**

The data is obtained from a data visualization found on [tableau](https://public.tableau.com/app/profile/ben.ayres7024/viz/USAU2024CollegeNationals/Dashboard1), originally found on [USA Ultimate](https://play.usaultimate.org/).

</details>

### Materials

Data Files found on the [SCORE Sports Data Repository](https://data.scorenetwork.org/)

[ultimate_total.csv](ultimate_total.csv) - Total event statistics

[ultimate_per_game.csv](ultimate_per_game.csv) - Total games played for each player's team

[ultimate_worksheet.qmd](ultimate_worksheet.qmd) - Worksheet with data tidying and visualization questions.

[ultimate_worksheet_ans.qmd](ultimate_worksheet_ans.qmd) - Answer key/guide for the worksheet
