---
title: "nba-exploration"
author: "eric seltzer"
format: html
---

```{r}
regularSeason <- read_csv("esselt21/nba_players/data/regular-season.csv")
regularSeason <-
  regularSeason |>
  select(-1)
```

```{r}
regularSeason <-
  regularSeason |>
  mutate(Tm = as.factor(Tm))

regularSeason <-
  regularSeason |>
  separate(Pos,
           sep = "-",
           into = c("Pos", "Fake")) |>
  select(-Fake) |>
  mutate(Pos = as.factor(Pos))
```

```{r}
write.csv(regularSeason, 
          "regular-season.csv",
          row.names = FALSE)
```

```{r}
one.way <- aov(PF ~ Pos,
               data = regularSeason)

summary(one.way)

report(one.way)
```

```{r}
two.way <- aov(PF ~ Pos + Age,
               data = regularSeason)

summary(two.way)

report(two.way)
```

one way anova of number of fouls based on position

two way anova of number of fouls based on position and age

```{r}
# describe the shape of the distribution
regularSeason |>
  ggplot(aes(x = PTS)) +
  geom_histogram(color = "black",
                 fill = "lightblue")
```

```{r}
# 5 number summary and standard deviation
regularSeason |>
  pull(PTS) |>
  summary()

regularSeason |>
  pull(PTS) |>
  sd()
```

```{r}
regularSeason |>
  ggplot(aes(x = Pos,
             y = PTS)) +
  geom_boxplot()
```

```{r}
# check if there is a difference based on position

```

