---
title: "2025 NCAA Women's Track Running"
author: "Phoebe Jones" 
date: "July 2, 2025" 
format:
    html:
      embed-resources: true
categories:
  - Mutating
  - Transformations
  - Simple Linear Regression
---

## Motivation

In outdoor track, runners run on a track and compete to complete the distance in the shortest time. There are many different events (distinguished by length, measured in meters) and runners typically have a specialty between distance or sprint. Distance runners need to think about pacing themselves and strategically overtaking competitors. Sprinters need to get a good start and maintain their highest speed for a short period of time. NCAA Women's Division 1 track runners compete at a very high level, and their times are recorded throughout the season to track the top individual achievements.

## Data

Each row in the `NCAA_track` data set represents one of the 50 fastest times in a given event for the 2025 NCAA Women's Division 1 East outdoor track season (with only a runner's fastest time included, no runner is included more than once for a single event). If a time was achieved by more than one runner, each runner will be present, and they will all have the same number in the `Place` column. Each event includes exactly 50 runners, with the exception the 200 meters event, which has two runners tied in 50th place. If a runner had a top 50 time in more than one event, they will have a row in the data set for each event they were in the top 50 for.

There are 351 rows observed over 8 variables.

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable    | Description                                             |
|-------------|---------------------------------------------------------|
| Place       | The runner's place for this event                       |
| Athlete     | The runner's name (Last, First)                         |
| Year        | The runner's class year                                 |
| Team        | The team the runner represents                          |
| Time        | The runner's time for this event                        |
| Meet        | The meet the time was achieved at                       |
| Meet.Date   | The date of the meet the time was achieved at           |
| Event       | What event the time is from (how many meters)           |

</details>

**Download Running Data:** [NCAA_track.csv](NCAA_track.csv){target="_blank"}

## Questions

1. Can we separate `Athlete` into first and last name variables?
2. Can we create a speed variable to observe the relationship between distance and speed?
3. Do some meets produce irregular times?

## References

The data are compiled from TFRRS (Track and Field Results Reporting System), an online database of track and field results. 

[TFRRS: 2025 NCAA East Individual Results](https://www.tfrrs.org/ncaad1east/outdoortrack/women)


